In [ ]:
import json
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
import re
import os

In [3]:
java_sard_df = pd.read_pickle('dataset\SARD_Java.pkl')
java_sard_df.head()

   label                                               code
0      1  public void bad() throws IOException \n    {\n...
1      1  public void bad(HttpServletRequest request, Ht...
2      0  private void goodG2B(HttpServletRequest reques...
3      0  private void goodB2G(HttpServletRequest reques...
4      1  public void bad(HttpServletRequest request, Ht...

In [4]:
java_sard_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202911 entries, 0 to 202910
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   label   202911 non-null  int64
 1   code    202911 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.1+ MB

In [5]:
java_sard_df[java_sard_df['label'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 48241 entries, 0 to 202908
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   48241 non-null  int64
 1   code    48241 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.1+ MB

In [ ]:
shuffled_df = java_sard_df.sample(frac=1, random_state=42).reset_index(drop=True)

train_df = shuffled_df.iloc[:183275]
val_df = shuffled_df.iloc[183275:193093]
test_df = shuffled_df.iloc[193093:]

print("Train:", train_df.shape)
print("Val:", val_df.shape)
print("Test:", test_df.shape)

Train: (183275, 2)
Val: (9818, 2)
Test: (9818, 2)

In [6]:
train_df.to_pickle("dataset/java_train_origin_data.pkl")
test_df.to_pickle("dataset/java_test_data.pkl")
val_df.to_pickle("dataset/java_val_data.pkl")

In [ ]:
train_origin_df = pd.read_pickle("dataset/java_train_data.pkl")
train_origin_df.info()
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183275 entries, 0 to 183274
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   label   183275 non-null  int64
 1   code    183275 non-null  object
dtypes: int64(1), object(1)
memory usage: 2.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9818 entries, 193093 to 202910
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   9818 non-null   int64
 1   code    9818 non-null   object
dtypes: int64(1), object(1)
memory usage: 153.5+ KB

In [16]:
undersampled_java_df = pd.read_pickle("dataset/undersampled_java.pkl")
undersampled_java_df

       label                                               code
0          1  public void bad() throws Throwable\n    {\n   ...
1          1  public void bad() throws Throwable\n    {\n   ...
2          0  private void goodG2B(HttpServletRequest reques...
3          1  public void bad() throws Throwable\n    {\n   ...
4          1  public void bad() throws Throwable\n    {\n   ...
...      ...                                                ...
96477      0  private void goodB2G1() throws Throwable\n    ...
96478      1  public void bad() throws Throwable\n    {\n   ...
96479      1  public void bad() throws Throwable\n    {\n   ...
96480      0  public void goodG2BSink(String data , HttpServ...
96481      0  private void goodB2G1() throws Throwable\n    ...

[96482 rows x 2 columns]

In [ ]:
shuffled_df = undersampled_java_df.sample(frac=1, random_state=42).reset_index(drop=True)

train_df = shuffled_df.iloc[:66081]
val_df = shuffled_df.iloc[66082:81282]
test_df = shuffled_df.iloc[81282:]

print("Train:", train_df.shape)
print("Val:", val_df.shape)
print("Test:", test_df.shape)

Train: (66081, 2)
Val: (15200, 2)
Test: (15200, 2)

In [20]:
train_df.to_pickle("dataset/java_train_data.pkl")
test_df.to_pickle("dataset/java_test_data.pkl")
val_df.to_pickle("dataset/java_val_data.pkl")

In [18]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 6000 to 6999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   1000 non-null   int64
 1   code    1000 non-null   object
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [21]:
float(len(train_df[train_df['label'] == 1]) / len(train_df[train_df['label'] == 0]))

1.0

In [8]:
cpp_df = pd.read_pickle("dataset/dataset.pkl")
cpp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264822 entries, 0 to 264821
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   label   264822 non-null  int64
 1   code    264822 non-null  object
dtypes: int64(1), object(1)
memory usage: 4.0+ MB

In [10]:
cpp_df['label'] = cpp_df['label'].apply(lambda x: 1 if x != 0 else 0)
cpp_df.head(25)

    label                                               code
0       0  static void good1 ( ) { if ( 0 ) { printLine (...
1       0  static void good1 ( ) { if ( 5 != 5 ) { printL...
2       1  void CWE546_Suspicious_Comment__BUG_04_bad ( )...
3       0  static void good1 ( ) { if ( STATIC_CONST_FALS...
4       0  static void good1 ( ) { if ( staticFalse ) { p...
5       1  void CWE546_Suspicious_Comment__BUG_06_bad ( )...
6       0  static void good1 ( ) { if ( STATIC_CONST_FIVE...
7       1  void CWE546_Suspicious_Comment__BUG_07_bad ( )...
8       0  static void good1 ( ) { if ( staticFive != 5 )...
9       1  void CWE546_Suspicious_Comment__BUG_08_bad ( )...
10      0  static void good1 ( ) { if ( staticReturnsFals...
11      1  void CWE546_Suspicious_Comment__BUG_09_bad ( )...
12      0  static void good1 ( ) { if ( GLOBAL_CONST_FALS...
13      0  static void good1 ( ) { if ( globalFalse ) { p...
14      1  void CWE546_Suspicious_Comment__BUG_11_bad ( )...
15      0  static void good1 ( ) { if ( globalReturnsFals...
16      1  void CWE546_Suspicious_Comment__BUG_12_bad ( )...
17      0  static void good1 ( ) { if ( globalReturnsTrue...
18      1  void CWE546_Suspicious_Comment__BUG_13_bad ( )...
19      0  static void good1 ( ) { if ( GLOBAL_CONST_FIVE...
20      1  void CWE546_Suspicious_Comment__BUG_14_bad ( )...
21      0  static void good1 ( ) { if ( globalFive != 5 )...
22      1  void CWE546_Suspicious_Comment__BUG_15_bad ( )...
23      0  static void good1 ( ) { switch ( 5 ) { case 6 ...
24      0  static void good2 ( ) { switch ( 6 ) { case 6 ...

In [ ]:
df_majority = cpp_df[cpp_df['label'] == 0]
df_minority = cpp_df[cpp_df['label'] == 1]

n_samples = len(df_minority)
df_majority_downsampled = resample(df_majority, 
                                   replace=False,    
                                   n_samples=n_samples,     
                                   random_state=42)  

cpp_df = pd.concat([df_majority_downsampled, df_minority])

cpp_df = cpp_df.sample(frac=1, random_state=42).reset_index(drop=True)

cpp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196362 entries, 0 to 196361
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   label   196362 non-null  int64
 1   code    196362 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.0+ MB

In [18]:
float(len(cpp_df[cpp_df['label'] == 1]) / len(cpp_df[cpp_df['label'] == 0]))

1.0

In [14]:
cpp_df.to_pickle("dataset/cpp_train_data.pkl")

In [ ]:
cpp_train_df = pd.read_pickle("subtrees/mutrvd/cpp_train_block.pkl")
java_dev_df = pd.read_pickle("subtrees/mutrvd/java_dev_block.pkl")
java_test_df = pd.read_pickle("subtrees/mutrvd/java_test_block.pkl")

[[4, [89, [88]], [61], [32, [59], [40, [13], [12]]]], [3, [26], [10, [124, [124]], [25], [11]], [10, [124], [37], [11]], [5, [14, [25], [17], [36]], [11]], [5, [14, [25], [17], [35]], [11]], [5, [14, [33, [37], [45], [29]], [17], [25]], [11]], [5, [6, [69], [8, [13], [37], [12]]], [11]], [24]], [26], [10, [124, [124]], [25], [11]], [10, [124], [37], [11]], [5, [14, [25], [17], [36]], [11]], [5, [14, [25], [17], [35]], [11]], [5, [14, [33, [37], [45], [29]], [17], [25]], [11]], [5, [6, [69], [8, [13], [37], [12]]], [11]], [24]]
[[124, [124, [124]], [61], [59], [124, [13], [12]], [124, [124], [25]]], [124, [26], [124, [124, [65]], [124, [37], [17], [124, [44, [13], [124, [110], [69], [8, [13], [12]]], [12]], [45], [87], [8, [13], [12]]]], [11]], [124, [124, [65]], [124, [35], [17], [28, [13], [124, [65]], [12], [44, [13], [77, [106], [37]], [12]]]], [11]], [5, [124, [29], [45], [94], [8, [13], [9, [92, [56], [56]], [84], [35]], [12]]], [11]], [24]], [26], [124, [124, [65]], [124, [37], [17], [124, [44, [13], [124, [110], [69], [8, [13], [12]]], [12]], [45], [87], [8, [13], [12]]]], [11]], [124, [124, [65]], [124, [35], [17], [28, [13], [124, [65]], [12], [44, [13], [77, [106], [37]], [12]]]], [11]], [5, [124, [29], [45], [94], [8, [13], [9, [92, [56], [56]], [84], [35]], [12]]], [11]], [24]]
[[124, [124, [124]], [61], [59], [124, [13], [12]], [124, [124], [25]]], [124, [26], [124, [124, [65]], [124, [37]], [11]], [5, [14, [37], [17], [72]], [11]], [124, [124, [35], [124, [68], [29], [76]]], [124, [49], [17], [124, [110], [124, [35], [124, [68], [29], [76]]], [8, [13], [12]]]], [11]], [5, [124, [49], [45], [69], [8, [13], [36], [23], [37], [12]]], [11]], [5, [124, [49], [45], [69], [8, [13], [27], [23], [37], [12]]], [11]], [5, [124, [49], [45], [69], [8, [13], [72], [23], [37], [12]]], [11]], [5, [124, [44, [13], [124, [110], [87], [8, [13], [12]]], [12]], [45], [94], [8, [13], [49], [12]]], [11]], [24]], [26], [124, [124, [65]], [124, [37]], [11]], [5, [14, [37], [17], [72]], [11]], [124, [124, [35], [124, [68], [29], [76]]], [124, [49], [17], [124, [110], [124, [35], [124, [68], [29], [76]]], [8, [13], [12]]]], [11]], [5, [124, [49], [45], [69], [8, [13], [36], [23], [37], [12]]], [11]], [5, [124, [49], [45], [69], [8, [13], [27], [23], [37], [12]]], [11]], [5, [124, [49], [45], [69], [8, [13], [72], [23], [37], [12]]], [11]], [5, [124, [44, [13], [124, [110], [87], [8, [13], [12]]], [12]], [45], [94], [8, [13], [49], [12]]], [11]], [24]]

In [17]:
sard_java_df = pd.read_pickle("dataset/SARD_Java.pkl")
sard_java_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202911 entries, 0 to 202910
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   label   202911 non-null  int64
 1   code    202911 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.1+ MB

In [18]:
cpp_data_df = pd.read_pickle("dataset/dataset.pkl")
cpp_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264822 entries, 0 to 264821
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   label   264822 non-null  int64
 1   code    264822 non-null  object
dtypes: int64(1), object(1)
memory usage: 4.0+ MB

In [ ]:
df_majority = cpp_data_df[cpp_data_df['label'] == 0]
df_minority = cpp_data_df[cpp_data_df['label'] == 1]

n_samples = len(df_minority)
df_majority_downsampled = resample(df_majority, 
                                   replace=False,    
                                   n_samples=n_samples,    
                                   random_state=42)  

cpp_data_df = pd.concat([df_majority_downsampled, df_minority])

cpp_data_df = cpp_data_df.sample(frac=1, random_state=42).reset_index(drop=True)

cpp_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15200 entries, 0 to 15199
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   15200 non-null  int64
 1   code    15200 non-null  object
dtypes: int64(1), object(1)
memory usage: 237.6+ KB

In [15]:
cpp_train_onl = pd.read_pickle("dataset_online/cpp_train_data.pkl")
java_train_onl = pd.read_pickle("dataset_online/java_train_data.pkl")
java_test_onl = pd.read_pickle("dataset_online/java_test_data.pkl")
java_val_onl = pd.read_pickle("dataset_online/java_val_data.pkl")

In [ ]:

java_train_onl['code'] = java_train_onl['code'].apply(remove_comments_java)
java_test_onl['code'] = java_test_onl['code'].apply(remove_comments_java)
java_val_onl['code'] = java_val_onl['code'].apply(remove_comments_java)

In [19]:
java_train_onl.to_pickle("dataset_online/java_train_nocomment.pkl")
java_test_onl.to_pickle("dataset_online/java_test_nocomment.pkl")
java_val_onl.to_pickle("dataset_online/java_val_nocomment.pkl")

In [23]:
java_no_comment_df = java_train_onl + java_test_onl + java_val_onl
java_no_comment_df.info()
java_no_comment_df.to_pickle("dataset_online/java_no_comment_df.pkl")

<class 'pandas.core.frame.DataFrame'>
Index: 202911 entries, 0 to 202910
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   0 non-null      float64
 1   code    0 non-null      object
dtypes: float64(1), object(1)
memory usage: 4.6+ MB

In [ ]:
java_under_no_comment_df = java_train_onl[:50000]

df_majority = java_under_no_comment_df[java_under_no_comment_df['label'] == 0]
df_minority = java_under_no_comment_df[java_under_no_comment_df['label'] == 1]

n_samples = len(df_minority)
df_majority_downsampled = resample(df_majority, 
                                   replace=False,   
                                   n_samples=n_samples,     
                                   random_state=42)  

java_under_no_comment_df = pd.concat([df_majority_downsampled, df_minority])

java_under_no_comment_df = java_under_no_comment_df.sample(frac=1, random_state=42).reset_index(drop=True)

java_under_no_comment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23470 entries, 0 to 23469
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   23470 non-null  int64
 1   code    23470 non-null  object
dtypes: int64(1), object(1)
memory usage: 366.8+ KB

In [25]:
java_under_no_comment_df.to_pickle("dataset_online/java_under_no_comment_df.pkl")

In [26]:
java_under_no_comment_df.to_csv("dataset_online/java_under_no_comment_df.csv")
java_test_onl.to_csv("dataset_online/java_test_nocomment.csv")
java_val_onl.to_csv("dataset_online/java_val_nocomment.csv")

In [29]:
java_val_onl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9818 entries, 183275 to 193092
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   9818 non-null   int64
 1   code    9818 non-null   object
dtypes: int64(1), object(1)
memory usage: 153.5+ KB

In [48]:
train_mega = pd.read_csv("dataset/JavaMegaVul/train.csv")
val_mega = pd.read_csv("dataset/JavaMegaVul/validation.csv")
test_mega = pd.read_csv("dataset/JavaMegaVul/test.csv")
full_df = pd.merge(pd.merge(train_mega, val_mega, how='outer'), test_mega, how='outer')
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42190 entries, 0 to 42189
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    42190 non-null  object
 1   code_raw  42190 non-null  object
 2   abs_code  42190 non-null  object
 3   label     42190 non-null  int64
dtypes: int64(1), object(3)
memory usage: 1.3+ MB

In [56]:
train_new_mega = full_df[:40000]
val_new_mega = full_df[40000:41095]
test_new_mega = full_df[41095:]
test_new_mega.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 41095 to 42189
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    1095 non-null   object
 1   code_raw  1095 non-null   object
 2   abs_code  1095 non-null   object
 3   label     1095 non-null   int64
dtypes: int64(1), object(3)
memory usage: 34.3+ KB

In [ ]:
train_java_meaga_under = train_new_mega

df_majority = train_java_meaga_under[train_java_meaga_under['label'] == 0]
df_minority = train_java_meaga_under[train_java_meaga_under['label'] == 1]

n_samples = len(df_minority)
df_majority_downsampled = resample(df_majority, 
                                   replace=False,    
                                   n_samples=n_samples,     
                                   random_state=42)  

train_java_meaga_under = pd.concat([df_majority_downsampled, df_minority])

train_java_meaga_under = train_java_meaga_under.sample(frac=1, random_state=42).reset_index(drop=True)

train_java_meaga_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    4722 non-null   object
 1   code_raw  4722 non-null   object
 2   abs_code  4722 non-null   object
 3   label     4722 non-null   int64
dtypes: int64(1), object(3)
memory usage: 147.7+ KB

In [61]:
train_java_meaga_under.to_pickle("dataset/JavaMegaVul/train_java_mega_under.pkl")
val_new_mega.to_pickle("dataset/JavaMegaVul/val_java_mega.pkl")
test_new_mega.to_pickle("dataset/JavaMegaVul/test_java_mega.pkl")

In [60]:
len(train_java_meaga_under[train_java_meaga_under['label'] == 1]) / len(train_java_meaga_under[train_java_meaga_under['label'] == 0])

1.0

In [2]:
train_java_mega = pd.read_csv("dataset/JavaMegaVul/train.csv")
test_java_mega = pd.read_csv("dataset/JavaMegaVul/test.csv")
val_java_mega = pd.read_csv("dataset/JavaMegaVul/validation.csv")
full_df = pd.concat([train_java_mega, val_java_mega, test_java_mega], ignore_index=True)
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41949 entries, 0 to 41948
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    41949 non-null  object
 1   code_raw  41949 non-null  object
 2   abs_code  41949 non-null  object
 3   label     41949 non-null  int64
dtypes: int64(1), object(3)
memory usage: 1.3+ MB

In [3]:
train_df = full_df[:33559]
val_df = full_df[33559:37754]
test_df = full_df[37754:]
train_df.info()
val_df.info()
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33559 entries, 0 to 33558
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    33559 non-null  object
 1   code_raw  33559 non-null  object
 2   abs_code  33559 non-null  object
 3   label     33559 non-null  int64
dtypes: int64(1), object(3)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4195 entries, 33559 to 37753
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    4195 non-null   object
 1   code_raw  4195 non-null   object
 2   abs_code  4195 non-null   object
 3   label     4195 non-null   int64
dtypes: int64(1), object(3)
memory usage: 131.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4195 entries, 37754 to 41948
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    4195 non-null   object
 1   code_raw  4195 non-null   object
 2   abs_code  4195 non-null   object
 3   label     4195 non-null   int64
dtypes: int64(1), object(3)
memory usage: 131.2+ KB

In [ ]:
train_java_meaga_under = train_df

df_majority = train_java_meaga_under[train_java_meaga_under['label'] == 0]
df_minority = train_java_meaga_under[train_java_meaga_under['label'] == 1]

n_samples = len(df_minority)
df_majority_downsampled = resample(df_majority, 
                                   replace=False,    
                                   n_samples=n_samples,    
                                   random_state=42)  

train_java_meaga_under = pd.concat([df_majority_downsampled, df_minority])

train_java_meaga_under = train_java_meaga_under.sample(frac=1, random_state=42).reset_index(drop=True)

train_java_meaga_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3902 entries, 0 to 3901
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CWE_ID    3902 non-null   object
 1   code_raw  3902 non-null   object
 2   abs_code  3902 non-null   object
 3   label     3902 non-null   int64
dtypes: int64(1), object(3)
memory usage: 122.1+ KB

In [9]:
train_java_meaga_under.to_pickle("dataset/JavaMegaVul/train_java_mega_under2b.pkl")
val_df.to_pickle("dataset/JavaMegaVul/val_java_mega2b.pkl")
test_df.to_pickle("dataset/JavaMegaVul/test_java_mega2b.pkl")

In [2]:
jtr = pd.read_pickle("3a/dataset/java_train_under_nor2b.pkl")
jtr[jtr['label'] == 1].head(5)

,CWE_ID,code_raw,abs_code,label,code
1,['CWE-787'],@Deprecated // v2.15\n public static Object...,@Deprecated /* COMMENT_0 */\n public static...,1,@Deprecated public static VAR1 FUN1( final IO...
2,['CWE-611'],@Test\n public void testWithMaliciousReques...,@Test\n public void testWithMaliciousReques...,1,"@Test public void FUN1() throws VAR1, VAR2 { F..."
3,['CWE-20'],@Override\n public void setAccountManagemen...,@Override\n public void setAccountManagemen...,1,"@Override public void FUN1(ComponentName VAR1,..."
10,['CWE-862'],public void visitUris(@NonNull Consumer<Uri> v...,public void visitUris(@NonNull Consumer<Uri> V...,1,public void FUN1(@NonNull VAR1<VAR2> VAR3) { V...
11,['CWE-20'],@Override\n public void setShortSupportMess...,@Override\n public void setShortSupportMess...,1,@Override public void FUN1(@NonNull ComponentN...

In [3]:
jtr[jtr['label'] == 0].head(5)

,CWE_ID,code_raw,abs_code,label,code
0,['CWE-241'],private static XmlSaxParserContext\n newInsta...,private static XmlSaxParserContext\n newInsta...,0,"private static VAR1 FUN1(final Ruby VAR2, fina..."
4,['CWE-284'],@Override\n public String toString() {\...,@Override\n public String toString() {\...,0,"@Override public VAR1 FUN1() { return """" + VAR..."
5,['CWE-862'],public boolean getHintLaunchesActivity() {\n ...,public boolean getHintLaunchesActivity() {\n ...,0,public boolean FUN1() { return (VAR1 & VAR2) !...
6,['CWE-Other'],int getDelegateUid() {\n return mTa...,int getDelegateUid() {\n return VAR...,0,int FUN1() { return VAR1; }
7,['CWE-1021'],public void clearSelection() {\n mImeAd...,public void clearSelection() {\n VAR_0....,0,public void FUN1() { VAR1.FUN2(); }

In [3]:
embedded_jtr = pd.read_pickle("3a/dataset/java_train_block.pkl")
embedded_jtr[embedded_jtr['label'] == 1].head(5)

,CWE_ID,code_raw,abs_code,label,code
1,['CWE-787'],@Deprecated // v2.15\n public static Object...,@Deprecated /* COMMENT_0 */\n public static...,1,"[[3, [143, [220, [227], [504]], [218], [94]], ..."
2,['CWE-611'],@Test\n public void testWithMaliciousReques...,@Test\n public void testWithMaliciousReques...,1,"[[3, [143, [220, [227], [478]], [218]], [56], ..."
3,['CWE-20'],@Override\n public void setAccountManagemen...,@Override\n public void setAccountManagemen...,1,"[[3, [143, [220, [227], [266]], [218]], [56], ..."
10,['CWE-862'],public void visitUris(@NonNull Consumer<Uri> v...,public void visitUris(@NonNull Consumer<Uri> V...,1,"[[3, [143, [218]], [56], [53], [35, [12], [138..."
11,['CWE-20'],@Override\n public void setShortSupportMess...,@Override\n public void setShortSupportMess...,1,"[[3, [143, [220, [227], [266]], [218]], [56], ..."

In [5]:
embedded_jtr[embedded_jtr['label'] == 0].head(5)

,CWE_ID,code_raw,abs_code,label,code
0,['CWE-241'],private static XmlSaxParserContext\n newInsta...,private static XmlSaxParserContext\n newInsta...,0,"[[3, [143, [280], [94]], [22], [53], [35, [12]..."
4,['CWE-284'],@Override\n public String toString() {\...,@Override\n public String toString() {\...,0,"[[3, [143, [220, [227], [266]], [218]], [22], ..."
5,['CWE-862'],public boolean getHintLaunchesActivity() {\n ...,public boolean getHintLaunchesActivity() {\n ...,0,"[[3, [143, [218]], [258], [53], [35, [12], [13..."
6,['CWE-Other'],int getDelegateUid() {\n return mTa...,int getDelegateUid() {\n return VAR...,0,"[[3, [67, [67]], [53], [35, [12], [13]], [2, [..."
7,['CWE-1021'],public void clearSelection() {\n mImeAd...,public void clearSelection() {\n VAR_0....,0,"[[3, [143, [218]], [56], [53], [35, [12], [13]..."

In [2]:
train_sven = pd.read_parquet("C:/hienlt/treesitter/dataset/python_dataset/train-sven.parquet")
val_sven = pd.read_parquet("C:/hienlt/treesitter/dataset/python_dataset/val-sven.parquet")

train_sven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   func_name        720 non-null    object
 1   func_src_before  720 non-null    object
 2   func_src_after   720 non-null    object
 3   line_changes     720 non-null    object
 4   char_changes     720 non-null    object
 5   commit_link      720 non-null    object
 6   file_name        720 non-null    object
 7   vul_type         720 non-null    object
dtypes: object(8)
memory usage: 45.1+ KB

In [4]:
sven_full = pd.concat([train_sven, val_sven], ignore_index=True)
sven_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   func_name        803 non-null    object
 1   func_src_before  803 non-null    object
 2   func_src_after   803 non-null    object
 3   line_changes     803 non-null    object
 4   char_changes     803 non-null    object
 5   commit_link      803 non-null    object
 6   file_name        803 non-null    object
 7   vul_type         803 non-null    object
dtypes: object(8)
memory usage: 50.3+ KB

In [6]:
sven_full.to_csv("C:/hienlt/treesitter/dataset/python_dataset/sven_full.csv")

In [7]:
sven_full.head(35)

,func_name,func_src_before,func_src_after,line_changes,char_changes,commit_link,file_name,vul_type
0,dd_get_item_size,"long dd_get_item_size(struct dump_dir *dd, con...","long dd_get_item_size(struct dump_dir *dd, con...","{'deleted': [], 'added': [{'line_no': 3, 'char...","{'deleted': [], 'added': [{'char_start': 67, '...",github.com/abrt/libreport/commit/239c4f7d1f472...,src/lib/dump_dir.c,cwe-022
1,zmi_page_request,"def zmi_page_request(self, *args, **kwargs...","def zmi_page_request(self, *args, **kwargs...","{'deleted': [{'line_no': 26, 'char_start': 131...","{'deleted': [], 'added': [{'char_start': 1322,...",github.com/zms-publishing/zms4/commit/3f28620d...,ZMSItem.py,cwe-022
2,nntp_hcache_namer,"static int nntp_hcache_namer(const char *path,...","static int nntp_hcache_namer(const char *path,...","{'deleted': [{'line_no': 3, 'char_start': 77, ...","{'deleted': [{'char_start': 79, 'char_end': 81...",github.com/neomutt/neomutt/commit/9bfab3552230...,newsrc.c,cwe-022
3,TarFileReader::extract,std::string TarFileReader::extract(const strin...,std::string TarFileReader::extract(const strin...,"{'deleted': [{'line_no': 6, 'char_start': 180,...","{'deleted': [], 'added': [{'char_start': 222, ...",github.com/CauldronDevelopmentLLC/cbang/commit...,src/cbang/tar/TarFileReader.cpp,cwe-022
4,handle_method_call,static void handle_method_call(GDBusConnection...,static void handle_method_call(GDBusConnection...,"{'deleted': [], 'added': [{'line_no': 259, 'ch...","{'deleted': [], 'added': [{'char_start': 9086,...",github.com/abrt/abrt/commit/7a47f57975be0d285a...,src/dbus/abrt-dbus.c,cwe-022
5,_inject_file_into_fs,"def _inject_file_into_fs(fs, path, contents):\...","def _inject_file_into_fs(fs, path, contents, a...","{'deleted': [{'line_no': 5, 'char_start': 212,...","{'deleted': [{'char_start': 67, 'char_end': 69...",github.com/openstack/nova/commit/2427d4a99bed3...,nova/virt/disk/api.py,cwe-022
6,set_interface_var,"set_interface_var(const char *iface,\n\t\t co...","set_interface_var(const char *iface,\n\t\t co...","{'deleted': [], 'added': [{'line_no': 10, 'cha...","{'deleted': [], 'added': [{'char_start': 240, ...",github.com/reubenhwk/radvd/commit/92e22ca23e52...,device-linux.c,cwe-022
7,cut,"def cut(self, key):\n try:\n ...","def cut(self, key):\n try:\n ...","{'deleted': [{'line_no': 3, 'char_start': 37, ...","{'deleted': [{'char_start': 66, 'char_end': 79...",github.com/latchset/custodia/commit/785fc87f38...,custodia/store/etcdstore.py,cwe-022
8,wiki_handle_http_request,wiki_handle_http_request(HttpRequest *req)\n{\...,wiki_handle_http_request(HttpRequest *req)\n{\...,"{'deleted': [{'line_no': 54, 'char_start': 135...","{'deleted': [{'char_start': 1357, 'char_end': ...",github.com/yarolig/didiwiki/commit/5e5c796617e...,src/wiki.c,cwe-022
9,candidate_paths_for_url,"def candidate_paths_for_url(self, url):\n ...","def candidate_paths_for_url(self, url):\n ...","{'deleted': [{'line_no': 4, 'char_start': 129,...","{'deleted': [{'char_start': 145, 'char_end': 1...",github.com/evansd/whitenoise/commit/4d8a3ab1e9...,whitenoise/base.py,cwe-022
10,updateKey,"def updateKey(client):\n\t""""""Updates the conte...","def updateKey(client):\n\t""""""Updates the conte...","{'deleted': [{'line_no': 9, 'char_start': 233,...","{'deleted': [{'char_start': 233, 'char_end': 2...",github.com/Mimickal/FoxLock/commit/7c665e55698...,impl.py,cwe-022
11,create_basename_core,def create_basename_core(basename):\n try:\...,def create_basename_core(basename):\n try:\...,"{'deleted': [{'line_no': 7, 'char_start': 143,...","{'deleted': [{'char_start': 158, 'char_end': 1...",github.com/syegulalp/mercury/commit/3f7c7442fa...,MeTal/core/utils.py,cwe-022
12,get,"def get(self, key):\n try:\n ...","def get(self, key):\n try:\n ...","{'deleted': [{'line_no': 3, 'char_start': 37, ...","{'deleted': [{'char_start': 72, 'char_end': 85...",github.com/latchset/custodia/commit/785fc87f38...,custodia/store/etcdstore.py,cwe-022
13,PHYSICALPATH_FUNC,PHYSICALPATH_FUNC(mod_alias_physical_handler) ...,PHYSICALPATH_FUNC(mod_alias_physical_handler) ...,"{'deleted': [], 'added': [{'line_no': 29, 'cha...","{'deleted': [], 'added': [{'char_start': 931, ...",github.com/lighttpd/lighttpd1.4/commit/2105dae...,src/mod_alias.c,cwe-022
14,download_check_files,"def download_check_files(self, filelist):\...","def download_check_files(self, filelist):\...","{'deleted': [{'line_no': 9, 'char_start': 383,...","{'deleted': [], 'added': [{'char_start': 395, ...",github.com/devsnd/cherrymusic/commit/62dec34a1...,cherrymusicserver/httphandler.py,cwe-022
15,get_files,"def get_files(self, submit_id, password=No...","def get_files(self, submit_id, password=No...","{'deleted': [{'line_no': 14, 'char_start': 574...","{'deleted': [{'char_start': 631, 'char_end': 6...",github.com/cuckoosandbox/cuckoo/commit/168cabf...,cuckoo/core/submit.py,cwe-022
16,handle,"def handle(self, keepalive=True, initial_t...","def handle(self, keepalive=True, initial_t...","{'deleted': [{'line_no': 53, 'char_start': 174...","{'deleted': [{'char_start': 1773, 'char_end': ...",github.com/fkmclane/python-fooster-web/commit/...,fooster/web/web.py,cwe-022
17,dd_delete_item,"int dd_delete_item(struct dump_dir *dd, const ...","int dd_delete_item(struct dump_dir *dd, const ...","{'deleted': [], 'added': [{'line_no': 6, 'char...","{'deleted': [], 'added': [{'char_start': 149, ...",github.com/abrt/libreport/commit/239c4f7d1f472...,src/lib/dump_dir.c,cwe-022
18,render,"\tdef render(self, request):\n\t\taction = ""do...","\tdef render(self, request):\n\t\taction = ""do...","{'deleted': [{'line_no': 7, 'char_start': 149,...","{'deleted': [{'char_start': 186, 'char_end': 2...",github.com/E2OpenPlugins/e2openplugin-OpenWebi...,plugin/controllers/file.py,cwe-022
19,_inject_net_into_fs,"def _inject_net_into_fs(net, fs, execute=None)...","def _inject_net_into_fs(net, fs, execute=None)...","{'deleted': [{'line_no': 6, 'char_start': 181,...","{'deleted': [{'char_start': 194, 'char_end': 2...",github.com/openstack/nova/commit/2427d4a99bed3...,nova/virt/disk/api.py,cwe-022
20,canonicalize,"def canonicalize(self):\n """"""::\n\n...","def canonicalize(self):\n """"""::\n\n...","{'deleted': [{'line_no': 6, 'char_start': 83, ...","{'deleted': [{'char_start': 110, 'char_end': 1...",github.com/dex4er/Pyjoyment/commit/e4b115bc80c...,Pyjo/Path.py,cwe-022
21,CWebSock::GetSkinPath,CString CWebSock::GetSkinPath(const CString& s...,CString CWebSock::GetSkinPath(const CString& s...,"{'deleted': [{'line_no': 2, 'char_start': 58, ...","{'deleted': [{'char_start': 124, 'char_end': 1...",github.com/znc/znc/commit/a4a5aeeb17d32937d8c7...,src/WebModules.cpp,cwe-022
22,addKey,"def addKey(client):\n\t""""""Adds a new key with ...","def addKey(client):\n\t""""""Adds a new key with ...","{'deleted': [{'line_no': 9, 'char_start': 210,...","{'deleted': [{'char_start': 210, 'char_end': 2...",github.com/Mimickal/FoxLock/commit/7c665e55698...,impl.py,cwe-022
23,dd_save_text,"void dd_save_text(struct dump_dir *dd, const c...","void dd_save_text(struct dump_dir *dd, const c...","{'deleted': [], 'added': [{'line_no': 6, 'char...","{'deleted': [], 'added': [{'char_start': 166, ...",github.com/abrt/libreport/commit/239c4f7d1f472...,src/lib/dump_dir.c,cwe-022
24,misc_file_checks,def misc_file_checks(self):\n\n pri...,def misc_file_checks(self):\n\n pri...,"{'deleted': [{'line_no': 39, 'char_start': 126...","{'deleted': [], 'added': [{'char_start': 1153,...",github.com/YunoHost/package_linter/commit/f6e9...,package_linter.py,cwe-022
25,dd_save_binary,"void dd_save_binary(struct dump_dir* dd, const...","void dd_save_binary(struct dump_dir* dd, const...","{'deleted': [], 'added': [{'line_no': 6, 'char...","{'deleted': [], 'added': [{'char_start': 183, ...",github.com/abrt/libreport/commit/239c4f7d1f472...,src/lib/dump_dir.c,cwe-022
26,pascal_case,def pascal_case(value: str) -> str:\n retur...,def pascal_case(value: str) -> str:\n retur...,"{'deleted': [{'line_no': 2, 'char_start': 36, ...","{'deleted': [], 'added': [{'char_start': 69, '...",github.com/openapi-generators/openapi-python-c...,openapi_python_client/utils.py,cwe-022
27,cleanup_pathname,cleanup_pathname(struct archive_write_disk *a)...,cleanup_pathname(struct archive_write_disk *a)...,"{'deleted': [{'line_no': 17, 'char_start': 336...","{'deleted': [], 'added': [{'char_start': 353, ...",github.com/libarchive/libarchive/commit/593571...,libarchive/archive_write_disk_posix.c,cwe-022
28,create_dump_dir_from_problem_data,struct dump_dir *create_dump_dir_from_problem_...,struct dump_dir *create_dump_dir_from_problem_...,"{'deleted': [{'line_no': 90, 'char_start': 274...","{'deleted': [{'char_start': 2709, 'char_end': ...",github.com/abrt/libreport/commit/239c4f7d1f472...,src/lib/create_dump_dir.c,cwe-022
29,list,"def list(self, keyfilter='/'):\n pa...","def list(self, keyfilter='/'):\n pa...","{'deleted': [{'line_no': 2, 'char_start': 35, ...","{'deleted': [{'char_start': 50, 'char_end': 63...",github.com/latchset/custodia/commit/785fc87f38...,custodia/store/etcdstore.py,cwe-022
30,process,local void process(char *path)\n{\n int met...,local void process(char *path)\n{\n int met...,"{'deleted': [{'line_no': 224, 'char_start': 80...","{'deleted': [{'char_start': 8052, 'char_end': ...",github.com/madler/pigz/commit/fdad1406b3ec809f...,pigz.c,cwe-022
31,imap_hcache_open,header_cache_t *imap_hcache_open(struct ImapDa...,header_cache_t *imap_hcache_open(struct ImapDa...,"{'deleted': [], 'added': [{'line_no': 19, 'cha...","{'deleted': [], 'added': [{'char_start': 415, ...",github.com/neomutt/neomutt/commit/57971dba0634...,imap/util.c,cwe-022
32,_normalize,"def _normalize(self, metaerrors):\n ...","def _normalize(self, metaerrors):\n ...","{'deleted': [{'line_no': 7, 'char_start': 183,...","{'deleted': [], 'added': [{'char_start': 195, ...",github.com/DamnWidget/anaconda_go/commit/d3db9...,plugin/handlers_go/anagonda/context/gometalint...,cwe-022
33,dd_load_text_ext,char* dd_load_text_ext(const struct dump_dir *...,char* dd_load_text_ext(const struct dump_dir *...,"{'deleted': [], 'added': [{'line_no': 6, 'char...","{'deleted': [], 'added': [{'char_start': 179, ...",github.com/abrt/libreport/commit/239c4f7d1f472...,src/lib/dump_dir.c,cwe-022
34,_download_file,@staticmethod\n def _download_file(buck...,@staticmethod\n def _download_file(buck...,"{'deleted': [{'line_no': 4, 'char_start': 110,...","{'deleted': [], 'added': [{'char_start': 159, ...",github.com/openstack/nova/commit/76363226bd853...,nova/image/s3.py,cwe-022

In [8]:
py_file_condition = sven_full['file_name'].str.endswith('.py')
sven_full_py = sven_full[py_file_condition]
sven_full_py.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 1 to 761
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   func_name        380 non-null    object
 1   func_src_before  380 non-null    object
 2   func_src_after   380 non-null    object
 3   line_changes     380 non-null    object
 4   char_changes     380 non-null    object
 5   commit_link      380 non-null    object
 6   file_name        380 non-null    object
 7   vul_type         380 non-null    object
dtypes: object(8)
memory usage: 26.7+ KB

In [13]:
processed_sven = pd.DataFrame()
for index, row in sven_full_py.iterrows():
    safe_code = row['func_src_after']
    safe_label = 0
    vulnerable_code = row['func_src_before']
    vulnerable_label = 1
    
    # Process the code as needed (e.g., remove comments, normalize, etc.)
    # For demonstration, we'll just keep the code as is.
    
    processed_sven = pd.concat([processed_sven, pd.DataFrame([{
        'code': safe_code,  
        'label': safe_label
    }])], ignore_index=True)
    processed_sven = pd.concat([processed_sven, pd.DataFrame([{
        'code': vulnerable_code,  
        'label': vulnerable_label
    }])], ignore_index=True)

processed_sven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    760 non-null    object
 1   label   760 non-null    int64
dtypes: int64(1), object(1)
memory usage: 12.0+ KB

In [14]:
processed_sven.head()

                                                code  label
0      def zmi_page_request(self, *args, **kwargs...      0
1      def zmi_page_request(self, *args, **kwargs...      1
2  def _inject_file_into_fs(fs, path, contents, a...      0
3  def _inject_file_into_fs(fs, path, contents):\...      1
4      def cut(self, key):\n        try:\n       ...      0

In [15]:
processed_sven.to_csv("C:/hienlt/treesitter/dataset/python_dataset/python_sven.csv")

In [2]:
nor_python_data = pd.read_pickle("C:/hienlt/treesitter/dataset/python_dataset/python_full_nor.pkl")
nor_python_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  760 non-null    int64
 1   code        760 non-null    object
 2   label       760 non-null    int64
dtypes: int64(2), object(1)
memory usage: 17.9+ KB

In [3]:
nor_python_data.iloc[759]['code']

'def FUN1(VAR1, VAR2, VAR3, VAR4): """""" VAR5 = FUN2(VAR3, VAR4) VAR6 = FUN3(VAR1, VAR2)  # Check if the source table is allready filled and this is not the first checkup VAR7 = len(VAR6) > 100  for old_source in VAR6: if source_table_is_filled and old_source not in VAR5: VAR8 = "" % VAR9 FUN4(VAR8)  for current_source in VAR5: if current_source not in VAR6: VAR8 = "" % current_source if VAR7: FUN4(VAR8) else: logging.FUN5(VAR8) VAR10 = "" % current_source VAR2.FUN6(VAR10) VAR1.FUN7() '

In [5]:
python_data = pd.read_csv("C:/hienlt/treesitter/dataset/python_dataset/python_sven.csv")
python_data.iloc[759]['code']

'def update_sources(conn, sqlite, k10plus, ai):\n    """\n    Update the source table.\n    """\n    current_sources = get_all_current_sources(k10plus, ai)\n    old_sources = get_all_old_sources(conn, sqlite)\n\n    # Check if the source table is allready filled and this is not the first checkup\n    source_table_is_filled = len(old_sources) > 100\n\n    for old_source in old_sources:\n        if source_table_is_filled and old_source not in current_sources:\n            message = "Die SID %s ist im aktuellen Import nicht mehr vorhanden.\\nWenn dies beabsichtigt ist, bitte die SID aus der Datenbank loeschen." % old_source\n            send_message(message)\n\n    for current_source in current_sources:\n        if current_source not in old_sources:\n            message = "The source %s is new in Solr." % current_source\n            if source_table_is_filled:\n                send_message(message)\n            else:\n                logging.info(message)\n            sql = "INSERT INTO source (source) VALUES (%s)" % current_source\n            sqlite.execute(sql)\n            conn.commit()'

In [3]:
go_train = pd.read_csv("C:/hienlt/treesitter/dataset/mul_go_train.csv")
go_val = pd.read_csv("C:/hienlt/treesitter/dataset/mul_go_val.csv")
go_test = pd.read_csv("C:/hienlt/treesitter/dataset/mul_go_test.csv")

go_full = pd.concat([go_train, go_val, go_test], ignore_index=True)

In [6]:
cwes = go_full['CWE'].unique()

In [7]:
bigVul_go = pd.read_csv("C:/hienlt/treesitter/dataset/bigVul_goCWE.csv")

In [9]:
bigVul_go['CWE ID'].unique()

array(['CWE-119', 'CWE-732', 'CWE-415', 'CWE-287', 'CWE-20', 'CWE-200',
       'CWE-264', 'CWE-787', 'CWE-1021', 'CWE-284', 'CWE-79', 'CWE-476',
       'CWE-190', 'CWE-89', 'CWE-362', 'CWE-400', 'CWE-59', 'CWE-22',
       'CWE-835', 'CWE-269', 'CWE-134', 'CWE-281', 'CWE-285', 'CWE-354',
       'CWE-311', 'CWE-754', 'CWE-74', 'CWE-78', 'CWE-668', 'CWE-346',
       'CWE-295', 'CWE-601', 'CWE-862', 'CWE-532', 'CWE-330', 'CWE-918',
       'CWE-682', 'CWE-770', 'CWE-347', 'CWE-352', 'CWE-426', 'CWE-755',
       'CWE-522', 'CWE-209'], dtype=object)

In [16]:
bigVul_go_1 = bigVul_go[bigVul_go['label'] == 1]

In [15]:
bigVul_go[bigVul_go['label'] == 0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 107951 entries, 0 to 113986
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      107951 non-null  int64
 1   CVE ID          107951 non-null  object
 2   CVE Page        107951 non-null  object
 3   CWE ID          107951 non-null  object
 4   codeLink        107951 non-null  object
 5   commit_id       107951 non-null  object
 6   commit_message  93626 non-null   object
 7   func_after      107951 non-null  object
 8   func_before     107951 non-null  object
 9   lang            107951 non-null  object
 10  project         107951 non-null  object
 11  vul             107951 non-null  int64
 12  code            107951 non-null  object
 13  label           107951 non-null  int64
dtypes: int64(3), object(11)
memory usage: 12.4+ MB

In [17]:
bigVul_go_0 = bigVul_go[bigVul_go['label'] == 0].head(6036)

In [18]:
bigVul_balanced = pd.concat([bigVul_go_1, bigVul_go_0], ignore_index=True)
bigVul_balanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12072 entries, 0 to 12071
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      12072 non-null  int64
 1   CVE ID          12072 non-null  object
 2   CVE Page        12072 non-null  object
 3   CWE ID          12072 non-null  object
 4   codeLink        12072 non-null  object
 5   commit_id       12072 non-null  object
 6   commit_message  10656 non-null  object
 7   func_after      12072 non-null  object
 8   func_before     12072 non-null  object
 9   lang            12072 non-null  object
 10  project         12072 non-null  object
 11  vul             12072 non-null  int64
 12  code            12072 non-null  object
 13  label           12072 non-null  int64
dtypes: int64(3), object(11)
memory usage: 1.3+ MB

In [19]:
bigVul_balanced = bigVul_balanced.sample(frac=1, random_state=42).reset_index(drop=True)
bigVul_balanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12072 entries, 0 to 12071
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      12072 non-null  int64
 1   CVE ID          12072 non-null  object
 2   CVE Page        12072 non-null  object
 3   CWE ID          12072 non-null  object
 4   codeLink        12072 non-null  object
 5   commit_id       12072 non-null  object
 6   commit_message  10656 non-null  object
 7   func_after      12072 non-null  object
 8   func_before     12072 non-null  object
 9   lang            12072 non-null  object
 10  project         12072 non-null  object
 11  vul             12072 non-null  int64
 12  code            12072 non-null  object
 13  label           12072 non-null  int64
dtypes: int64(3), object(11)
memory usage: 1.3+ MB

In [21]:
bigVul_balanced.to_csv("./dataset/bigVul_go_balanced.csv", index=False)

In [22]:
cpg_bigVul = pd.read_csv("C:/hienlt/treesitter/dataset/cpp(go)_train_nor_cpg.csv")
cpg_bigVul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12072 entries, 0 to 12071
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    12072 non-null  int64
 1   Unnamed: 0      12072 non-null  int64
 2   CVE ID          12072 non-null  object
 3   CVE Page        12072 non-null  object
 4   CWE ID          12072 non-null  object
 5   codeLink        12072 non-null  object
 6   commit_id       12072 non-null  object
 7   commit_message  10656 non-null  object
 8   func_after      12072 non-null  object
 9   func_before     12072 non-null  object
 10  lang            12072 non-null  object
 11  project         12072 non-null  object
 12  vul             12072 non-null  int64
 13  code            12072 non-null  object
 14  label           12072 non-null  int64
dtypes: int64(4), object(11)
memory usage: 1.4+ MB

In [ ]:

with open('./dataset/function.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27318 entries, 0 to 27317
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   project    27318 non-null  object
 1   commit_id  27318 non-null  object
 2   target     27318 non-null  int64
 3   func       27318 non-null  object
dtypes: int64(1), object(3)
memory usage: 853.8+ KB

In [3]:
df['label'] = df['target']
df['code'] = df['func']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27318 entries, 0 to 27317
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   project    27318 non-null  object
 1   commit_id  27318 non-null  object
 2   target     27318 non-null  int64
 3   func       27318 non-null  object
 4   label      27318 non-null  int64
 5   code       27318 non-null  object
dtypes: int64(2), object(4)
memory usage: 1.3+ MB

In [6]:
train_df.to_csv("./dataset/train_codexglue.csv", index=False)
val_df.to_csv("./dataset/val_codexglue.csv", index=False)
test_df.to_csv("./dataset/test_codexglue.csv", index=False)

In [5]:
import os
from pathlib import Path
import pandas as pd

def load_java_dataset(base_path):
    """
    Load Java vulnerability dataset from the folder structure.
    
    Args:
        base_path: Path to the JAVA dataset folder
        
    Returns:
        pandas.DataFrame with columns: code, label, cwe_id
    """
    data = []
    base_path = Path(base_path)
    
    # Iterate through each CWE folder
    for cwe_folder in base_path.iterdir():
        if not cwe_folder.is_dir():
            continue
            
        cwe_id = cwe_folder.name  # e.g., 'CWE-074'
        
        # Iterate through 'bad' and 'good' subfolders
        for label_folder in ['bad', 'good']:
            label_path = cwe_folder / label_folder
            
            if not label_path.exists():
                continue
            
            # Determine label: 1 for bad (vulnerable), 0 for good (safe)
            label = 1 if label_folder == 'bad' else 0
            
            # Iterate through all .txt files in the folder
            for file_path in label_path.glob('*.txt'):
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    # Extract code (everything before the separator line)
                    # The separator is a line with ^^^^^ or similar pattern
                    lines = content.split('\n')
                    code_lines = []
                    
                    for line in lines:
                        if line.strip().startswith('^'):
                            break
                        code_lines.append(line)
                    
                    code = '\n'.join(code_lines).strip()
                    
                    if code:  # Only add if there's actual code
                        data.append({
                            'code': code,
                            'label': label,
                            'cwe_id': cwe_id
                        })
                        
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")
    
    # Create DataFrame
    df = pd.DataFrame(data)
    return df

# Usage
base_path = r'c:/hienlt/treesitter/dataset/JAVA'
df = load_java_dataset(base_path)

# Display info about the dataset
print(f"Total samples: {len(df)}")
print(f"\nLabel distribution:")
print(df['label'].value_counts())
print(f"\nCWE-ID distribution:")
print(df['cwe_id'].value_counts())
print(f"\nDataFrame shape: {df.shape}")
print(f"\nFirst few rows:")
print(df.head())

Total samples: 167496

Label distribution:
label
0    122049
1     45447
Name: count, dtype: int64

CWE-ID distribution:
cwe_id
CWE-074    42081
CWE-190    28479
CWE-191    23005
CWE-089    15009
CWE-369    12504
CWE-400     8003
CWE-665     7461
CWE-079     6343
CWE-668     6011
CWE-704     6002
CWE-091     3004
CWE-601     2622
CWE-078     2120
CWE-077     2120
CWE-090     2116
CWE-573      384
CWE-404      232
Name: count, dtype: int64

DataFrame shape: (167496, 3)

First few rows:
                                                code  label   cwe_id
0  public void badSink(HashMap<Integer,String> da...      1  CWE-074
1  public void badSink(String data) throws Throwa...      1  CWE-074
2  public void bad(HttpServletRequest request,Htt...      1  CWE-074
3  public void badSink(CWE643_Xpath_Injection__Fi...      1  CWE-074
4  public void bad(HttpServletRequest request,Htt...      1  CWE-074

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167496 entries, 0 to 167495
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   code    167496 non-null  object
 1   label   167496 non-null  int64
 2   cwe_id  167496 non-null  object
dtypes: int64(1), object(2)
memory usage: 3.8+ MB

In [7]:
df.to_csv("./dataset/babel_java.csv", index=False)

In [8]:
df['cwe_id'].unique()

array(['CWE-074', 'CWE-077', 'CWE-078', 'CWE-079', 'CWE-089', 'CWE-090',
       'CWE-091', 'CWE-190', 'CWE-191', 'CWE-369', 'CWE-400', 'CWE-404',
       'CWE-573', 'CWE-601', 'CWE-665', 'CWE-668', 'CWE-704'],
      dtype=object)

In [9]:
for cwe_id in df['cwe_id'].unique():
    data_tmp = df[df['cwe_id'] == cwe_id]
    data_tmp.to_csv(f"./dataset/java_babel_{cwe_id}.csv", index=False)

In [ ]:
train_df = pd.read_csv("./dataset/train_codexglue.csv")
val_df = pd.read_csv("./dataset/val_codexglue.csv")
test_df = pd.read_csv("./dataset/test_codexglue.csv")
codexglue_df = pd.concat([train_df, val_df, test_df], ignore_index=True)
codexglue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27318 entries, 0 to 27317
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   project    27318 non-null  object
 1   commit_id  27318 non-null  object
 2   target     27318 non-null  int64
 3   func       27318 non-null  object
 4   label      27318 non-null  int64
 5   code       27318 non-null  object
dtypes: int64(2), object(4)
memory usage: 1.3+ MB

In [2]:
codexglue_df.head()

,project,commit_id,target,func,label,code
0,FFmpeg,b6ae0866821df5f3b83f6b7f5c281d9a3e36b7ee,1,"static void dv_decode_ac(GetBitContext *gb, Bl...",1,"static void dv_decode_ac(GetBitContext *gb, Bl..."
1,qemu,698235aab6f55e960203dc2ef9a3a580982dae2f,1,"static int get_physical_address(CPUState *env,...",1,"static int get_physical_address(CPUState *env,..."
2,qemu,4f4321c11ff6e98583846bfd6f0e81954924b003,1,"static int usb_net_handle_data(USBDevice *dev,...",1,"static int usb_net_handle_data(USBDevice *dev,..."
3,FFmpeg,725353525e73bbe5b6b4d01528252675f2417a02,1,static av_cold int ulti_decode_init(AVCodecCon...,1,static av_cold int ulti_decode_init(AVCodecCon...
4,qemu,9ed5726c043958359b0f1fa44ab3e4f25f9d9a47,1,target_ulong helper_emt(target_ulong arg1)\n\n...,1,target_ulong helper_emt(target_ulong arg1)\n\n...

In [ ]:
data_train = []
with open(r'C:/hienlt/treesitter/dataset/train_primevul.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

primevul_train_df = pd.DataFrame(data_train)
primevul_train_df.info()

data_val = []
with open(r'C:/hienlt/treesitter/dataset/val_primevul.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

primevul_val_df = pd.DataFrame(data_val)
primevul_val_df.info()


data_test = []
with open(r'C:/hienlt/treesitter/dataset/test_primevul.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_test.append(record)

primevul_test_df = pd.DataFrame(data_test)
primevul_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7889 non-null   object
 4   commit_url      7889 non-null   object
 5   commit_message  7889 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       7889 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7889 non-null   object
 13  cve_desc        7889 non-null   object
 14  nvd_url         7889 non-null   object
dtypes: int64(2), object(13)
memory usage: 924.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             986 non-null    int64
 1   project         986 non-null    object
 2   commit_id       986 non-null    object
 3   project_url     986 non-null    object
 4   commit_url      986 non-null    object
 5   commit_message  986 non-null    object
 6   target          986 non-null    int64
 7   func            986 non-null    object
 8   func_hash       986 non-null    object
 9   file_name       986 non-null    object
 10  file_hash       600 non-null    float64
 11  cwe             986 non-null    object
 12  cve             986 non-null    object
 13  cve_desc        986 non-null    object
 14  nvd_url         986 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 115.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             987 non-null    int64
 1   project         987 non-null    object
 2   commit_id       987 non-null    object
 3   project_url     987 non-null    object
 4   commit_url      987 non-null    object
 5   commit_message  987 non-null    object
 6   target          987 non-null    int64
 7   func            987 non-null    object
 8   func_hash       987 non-null    object
 9   file_name       987 non-null    object
 10  file_hash       583 non-null    float64
 11  cwe             987 non-null    object
 12  cve             987 non-null    object
 13  cve_desc        987 non-null    object
 14  nvd_url         987 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 115.8+ KB

In [8]:
primevul_df = pd.concat([primevul_train_df, primevul_val_df, primevul_test_df], ignore_index=True)
primevul_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9862 entries, 0 to 9861
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             9862 non-null   int64
 1   project         9862 non-null   object
 2   commit_id       9862 non-null   object
 3   project_url     9862 non-null   object
 4   commit_url      9862 non-null   object
 5   commit_message  9862 non-null   object
 6   target          9862 non-null   int64
 7   func            9862 non-null   object
 8   func_hash       9862 non-null   object
 9   file_name       9862 non-null   object
 10  file_hash       5882 non-null   object
 11  cwe             9862 non-null   object
 12  cve             9862 non-null   object
 13  cve_desc        9862 non-null   object
 14  nvd_url         9862 non-null   object
dtypes: int64(2), object(13)
memory usage: 1.1+ MB

In [18]:
primevul_df['cwe'].explode().unique()
cwe_77_df = primevul_df[primevul_df['cwe'].apply(lambda x: 'CWE-77' in x)]
cwe_77_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 29 to 7992
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             6 non-null      int64
 1   project         6 non-null      object
 2   commit_id       6 non-null      object
 3   project_url     6 non-null      object
 4   commit_url      6 non-null      object
 5   commit_message  6 non-null      object
 6   target          6 non-null      int64
 7   func            6 non-null      object
 8   func_hash       6 non-null      object
 9   file_name       6 non-null      object
 10  file_hash       3 non-null      object
 11  cwe             6 non-null      object
 12  cve             6 non-null      object
 13  cve_desc        6 non-null      object
 14  nvd_url         6 non-null      object
dtypes: int64(2), object(13)
memory usage: 768.0+ bytes

In [20]:
cwe78_df = pd.read_csv("./dataset/java_babel_CWE-078.csv")
cwe78_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    2120 non-null   object
 1   label   2120 non-null   int64
 2   cwe_id  2120 non-null   object
dtypes: int64(1), object(2)
memory usage: 49.8+ KB

In [21]:
cwe79_df = pd.read_csv("./dataset/java_babel_CWE-079.csv")
cwe79_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6343 entries, 0 to 6342
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    6343 non-null   object
 1   label   6343 non-null   int64
 2   cwe_id  6343 non-null   object
dtypes: int64(1), object(2)
memory usage: 148.8+ KB

In [22]:
cwe89_df = pd.read_csv("./dataset/java_babel_CWE-089.csv")
cwe89_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15009 entries, 0 to 15008
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    15009 non-null  object
 1   label   15009 non-null  int64
 2   cwe_id  15009 non-null  object
dtypes: int64(1), object(2)
memory usage: 351.9+ KB

In [38]:
primevul_df['cwe'].explode().unique()
cwe_89_df = primevul_df[primevul_df['cwe'].apply(lambda x: 'CWE-89' in x)]
cwe_89_df.head(10)

,idx,project,commit_id,project_url,commit_url,commit_message,target,func,func_hash,file_name,file_hash,cwe,cve,cve_desc,nvd_url
3488,4082,domoticz,ee70db46f81afa582c96b887b73bcd2a86feda00,https://github.com/domoticz/domoticz,https://github.com/domoticz/domoticz/commit/ee...,Fixed possible SQL Injection Vulnerability (Th...,1,\t\tvoid CWebServer::GetFloorplanImage(WebEmSe...,126919339259422647630024323951648713830,WebServer.cpp,148825033982485358559631690571371975396,[CWE-89],CVE-2019-10664,Domoticz before 4.10578 allows SQL Injection v...,https://nvd.nist.gov/vuln/detail/CVE-2019-10664
4758,216944,server,3c209bfc040ddfc41ece8357d772547432353fd2,https://github.com/MariaDB/server,https://github.com/MariaDB/server/commit/3c209...,MDEV-25994: Crash with union of my_decimal typ...,1,bool Item_singlerow_subselect::fix_length_and_...,239302885543348234166613869839510299585,None,None,[CWE-89],CVE-2022-27380,An issue in the component my_decimal::operator...,https://nvd.nist.gov/vuln/detail/CVE-2022-27380
5655,216943,server,e4e25d2bacc067417c35750f5f6c44cad10c81de,https://github.com/MariaDB/server,https://github.com/MariaDB/server/commit/e4e25...,MDEV-26423 MariaDB server crash in Create_tmp_...,1,Field *get_tmp_table_field() { return 0; },148596351366272767736593772933238846337,None,None,[CWE-89],CVE-2022-27378,An issue in the component Create_tmp_table::fi...,https://nvd.nist.gov/vuln/detail/CVE-2022-27378
6442,1395,mapserver,3a10f6b829297dae63492a8c63385044bc6953ed,https://github.com/mapserver/mapserver,https://github.com/mapserver/mapserver/commit/...,Fix potential SQL Injection with postgis TIME ...,1,"int msPostGISLayerSetTimeFilter(layerObj *lp, ...",92160701703090280340745521839872003209,mappostgis.c,273968548871858847268137762771601338564,[CWE-89],CVE-2013-7262,SQL injection vulnerability in the msPostGISLa...,https://nvd.nist.gov/vuln/detail/CVE-2013-7262
7480,195332,postgres,28e24125541545483093819efae9bca603441951,https://github.com/postgres/postgres,https://github.com/postgres/postgres/commit/28...,Reject extraneous data after SSL or GSS encryp...,1,"ProcessStartupPacket(Port *port, bool ssl_done...",307208757848729877909324360800164434195,postmaster.c,159297942961047386558328631987288020893,[CWE-89],CVE-2021-23214,When the server is configured to use trust aut...,https://nvd.nist.gov/vuln/detail/CVE-2021-23214

In [39]:
cwes = ['CWE-74', 'CWE-89', 'CWE-78', 'CWE-79', 'CWE-90', 'CWE-91', 'CWE-190', 'CWE-191', 'CWE-369', 'CWE-400'
        , 'CWE-404', 'CWE-573', 'CWE-601', 'CWE-665', 'CWE-668', 'CWE-704']

In [41]:
primevul_df['cwe'].explode().unique()
filtered_df = primevul_df[primevul_df['cwe'].apply(lambda x: any(cwe in x for cwe in cwes))]
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 706 entries, 28 to 9850
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             706 non-null    int64
 1   project         706 non-null    object
 2   commit_id       706 non-null    object
 3   project_url     706 non-null    object
 4   commit_url      706 non-null    object
 5   commit_message  706 non-null    object
 6   target          706 non-null    int64
 7   func            706 non-null    object
 8   func_hash       706 non-null    object
 9   file_name       706 non-null    object
 10  file_hash       431 non-null    object
 11  cwe             706 non-null    object
 12  cve             706 non-null    object
 13  cve_desc        706 non-null    object
 14  nvd_url         706 non-null    object
dtypes: int64(2), object(13)
memory usage: 88.2+ KB

In [43]:
float(len(filtered_df[filtered_df['target'] == 1])) / len(filtered_df[filtered_df['target'] == 0])

1.255591054313099

In [45]:
filtered_df_label_1 = filtered_df[filtered_df['target'] == 1]
filtered_df_label_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 393 entries, 56 to 9850
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             393 non-null    int64
 1   project         393 non-null    object
 2   commit_id       393 non-null    object
 3   project_url     393 non-null    object
 4   commit_url      393 non-null    object
 5   commit_message  393 non-null    object
 6   target          393 non-null    int64
 7   func            393 non-null    object
 8   func_hash       393 non-null    object
 9   file_name       393 non-null    object
 10  file_hash       283 non-null    object
 11  cwe             393 non-null    object
 12  cve             393 non-null    object
 13  cve_desc        393 non-null    object
 14  nvd_url         393 non-null    object
dtypes: int64(2), object(13)
memory usage: 49.1+ KB

In [46]:
primevul_df_label_0 = primevul_df[primevul_df['target'] == 0]
primevul_df_label_0 = primevul_df_label_0.sample(frac=1, random_state=42).reset_index(drop=True)
primevul_df_label_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             5000 non-null   int64
 1   project         5000 non-null   object
 2   commit_id       5000 non-null   object
 3   project_url     5000 non-null   object
 4   commit_url      5000 non-null   object
 5   commit_message  5000 non-null   object
 6   target          5000 non-null   int64
 7   func            5000 non-null   object
 8   func_hash       5000 non-null   object
 9   file_name       5000 non-null   object
 10  file_hash       2523 non-null   object
 11  cwe             5000 non-null   object
 12  cve             5000 non-null   object
 13  cve_desc        5000 non-null   object
 14  nvd_url         5000 non-null   object
dtypes: int64(2), object(13)
memory usage: 586.1+ KB

In [47]:
filtered_df_cwe = pd.concat([filtered_df_label_1, primevul_df_label_0[:len(filtered_df_label_1)]], ignore_index=True)
filtered_df_cwe = filtered_df_cwe.sample(frac=1, random_state=42).reset_index(drop=True)
filtered_df_cwe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786 entries, 0 to 785
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             786 non-null    int64
 1   project         786 non-null    object
 2   commit_id       786 non-null    object
 3   project_url     786 non-null    object
 4   commit_url      786 non-null    object
 5   commit_message  786 non-null    object
 6   target          786 non-null    int64
 7   func            786 non-null    object
 8   func_hash       786 non-null    object
 9   file_name       786 non-null    object
 10  file_hash       507 non-null    object
 11  cwe             786 non-null    object
 12  cve             786 non-null    object
 13  cve_desc        786 non-null    object
 14  nvd_url         786 non-null    object
dtypes: int64(2), object(13)
memory usage: 92.2+ KB

In [48]:
float(len(filtered_df_cwe[filtered_df_cwe['target'] == 1])) / len(filtered_df_cwe[filtered_df_cwe['target'] == 0])

1.0

In [49]:
filtered_df_cwe['code'] = filtered_df_cwe['func']
filtered_df_cwe['label'] = filtered_df_cwe['target']
filtered_df_cwe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786 entries, 0 to 785
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             786 non-null    int64
 1   project         786 non-null    object
 2   commit_id       786 non-null    object
 3   project_url     786 non-null    object
 4   commit_url      786 non-null    object
 5   commit_message  786 non-null    object
 6   target          786 non-null    int64
 7   func            786 non-null    object
 8   func_hash       786 non-null    object
 9   file_name       786 non-null    object
 10  file_hash       507 non-null    object
 11  cwe             786 non-null    object
 12  cve             786 non-null    object
 13  cve_desc        786 non-null    object
 14  nvd_url         786 non-null    object
 15  code            786 non-null    object
 16  label           786 non-null    int64
dtypes: int64(3), object(14)
memory usage: 104.5+ KB

In [50]:
filtered_df_cwe.to_csv("./dataset/primevul_filtered_cwe.csv", index=False)

In [52]:
primevul_cpg_df = pd.read_csv("./dataset/cpp(primevul)_train_cpg.csv")
primevul_cpg_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786 entries, 0 to 785
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             786 non-null    int64
 1   project         786 non-null    object
 2   commit_id       786 non-null    object
 3   project_url     781 non-null    object
 4   commit_url      786 non-null    object
 5   commit_message  581 non-null    object
 6   target          786 non-null    int64
 7   func            786 non-null    object
 8   func_hash       786 non-null    object
 9   file_name       507 non-null    object
 10  file_hash       507 non-null    object
 11  cwe             786 non-null    object
 12  cve             786 non-null    object
 13  cve_desc        786 non-null    object
 14  nvd_url         786 non-null    object
 15  code            786 non-null    object
 16  label           786 non-null    int64
dtypes: int64(3), object(14)
memory usage: 104.5+ KB

In [56]:
primevul_cpg_df_label_1 = primevul_cpg_df[primevul_cpg_df['label'] == 1]
primevul_cpg_df_label_0 = primevul_cpg_df[primevul_cpg_df['label'] == 0]
primevul_cpg_df_label_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 393 entries, 1 to 785
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             393 non-null    int64
 1   project         393 non-null    object
 2   commit_id       393 non-null    object
 3   project_url     388 non-null    object
 4   commit_url      393 non-null    object
 5   commit_message  343 non-null    object
 6   target          393 non-null    int64
 7   func            393 non-null    object
 8   func_hash       393 non-null    object
 9   file_name       283 non-null    object
 10  file_hash       283 non-null    object
 11  cwe             393 non-null    object
 12  cve             393 non-null    object
 13  cve_desc        393 non-null    object
 14  nvd_url         393 non-null    object
 15  code            393 non-null    object
 16  label           393 non-null    int64
dtypes: int64(3), object(14)
memory usage: 55.3+ KB

In [57]:
primevul_cpg_train_1 = primevul_cpg_df_label_1[:273]
primevul_cpg_train_0 = primevul_cpg_df_label_0[:273]
primevul_cpg_val_1 = primevul_cpg_df_label_1[273:273+63]
primevul_cpg_val_0 = primevul_cpg_df_label_0[273:273+60]
primevul_cpg_test_1 = primevul_cpg_df_label_1[273+63:]
primevul_cpg_test_0 = primevul_cpg_df_label_0[273+60:]

In [58]:
primevul_cpg_train = pd.concat([primevul_cpg_train_1, primevul_cpg_train_0], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
primevul_cpg_val = pd.concat([primevul_cpg_val_1, primevul_cpg_val_0], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
primevul_cpg_test = pd.concat([primevul_cpg_test_1, primevul_cpg_test_0], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)

In [62]:
primevul_cpg_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             123 non-null    int64
 1   project         123 non-null    object
 2   commit_id       123 non-null    object
 3   project_url     122 non-null    object
 4   commit_url      123 non-null    object
 5   commit_message  91 non-null     object
 6   target          123 non-null    int64
 7   func            123 non-null    object
 8   func_hash       123 non-null    object
 9   file_name       74 non-null     object
 10  file_hash       74 non-null     object
 11  cwe             123 non-null    object
 12  cve             123 non-null    object
 13  cve_desc        123 non-null    object
 14  nvd_url         123 non-null    object
 15  code            123 non-null    object
 16  label           123 non-null    int64
dtypes: int64(3), object(14)
memory usage: 16.5+ KB

In [63]:
float(len(primevul_cpg_train[primevul_cpg_train['target'] == 1])) / len(primevul_cpg_train[primevul_cpg_train['target'] == 0])

1.0

In [64]:
primevul_cpg_train.to_csv("./dataset/primevul_cpg_train.csv", index=False)
primevul_cpg_val.to_csv("./dataset/primevul_cpg_val.csv", index=False)
primevul_cpg_test.to_csv("./dataset/primevul_cpg_test.csv", index=False)

In [ ]:
data_train = []
with open(r'C:/hienlt/treesitter/dataset/train_primevul.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

primevul_train_df = pd.DataFrame(data_train)
primevul_train_df.info()

data_val = []
with open(r'C:/hienlt/treesitter/dataset/val_primevul.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

primevul_val_df = pd.DataFrame(data_val)
primevul_val_df.info()


data_test = []
with open(r'C:/hienlt/treesitter/dataset/test_primevul.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_test.append(record)

primevul_test_df = pd.DataFrame(data_test)
primevul_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7889 non-null   object
 4   commit_url      7889 non-null   object
 5   commit_message  7889 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       7889 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7889 non-null   object
 13  cve_desc        7889 non-null   object
 14  nvd_url         7889 non-null   object
dtypes: int64(2), object(13)
memory usage: 924.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             986 non-null    int64
 1   project         986 non-null    object
 2   commit_id       986 non-null    object
 3   project_url     986 non-null    object
 4   commit_url      986 non-null    object
 5   commit_message  986 non-null    object
 6   target          986 non-null    int64
 7   func            986 non-null    object
 8   func_hash       986 non-null    object
 9   file_name       986 non-null    object
 10  file_hash       600 non-null    float64
 11  cwe             986 non-null    object
 12  cve             986 non-null    object
 13  cve_desc        986 non-null    object
 14  nvd_url         986 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 115.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             987 non-null    int64
 1   project         987 non-null    object
 2   commit_id       987 non-null    object
 3   project_url     987 non-null    object
 4   commit_url      987 non-null    object
 5   commit_message  987 non-null    object
 6   target          987 non-null    int64
 7   func            987 non-null    object
 8   func_hash       987 non-null    object
 9   file_name       987 non-null    object
 10  file_hash       583 non-null    float64
 11  cwe             987 non-null    object
 12  cve             987 non-null    object
 13  cve_desc        987 non-null    object
 14  nvd_url         987 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 115.8+ KB

In [2]:
primevul_train_df.to_csv("./dataset/primevul_train.csv", index=False)
primevul_val_df.to_csv("./dataset/primevul_val.csv", index=False)
primevul_test_df.to_csv("./dataset/primevul_test.csv", index=False)

In [3]:
primevul_train_df['code'] = primevul_train_df['func']
primevul_train_df['label'] = primevul_train_df['target']
primevul_val_df['code'] = primevul_val_df['func']
primevul_val_df['label'] = primevul_val_df['target']
primevul_test_df['code'] = primevul_test_df['func']
primevul_test_df['label'] = primevul_test_df['target']

In [4]:
primevul_train_df.to_csv("./dataset/primevul_train.csv", index=False)
primevul_val_df.to_csv("./dataset/primevul_val.csv", index=False)
primevul_test_df.to_csv("./dataset/primevul_test.csv", index=False)

In [ ]:
train_df = pd.read_csv("./dataset/primevul_train.csv")
val_df = pd.read_csv("./dataset/primevul_val.csv")
test_df = pd.read_csv("./dataset/primevul_test.csv")
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7759 non-null   object
 4   commit_url      7887 non-null   object
 5   commit_message  5460 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       4699 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7888 non-null   object
 13  cve_desc        7888 non-null   object
 14  nvd_url         7889 non-null   object
 15  code            7889 non-null   object
 16  label           7889 non-null   int64
dtypes: int64(3), object(14)
memory usage: 1.0+ MB

In [2]:
filtered_df = pd.read_csv("./dataset/primevul_filtered_cwe.csv")
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786 entries, 0 to 785
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             786 non-null    int64
 1   project         786 non-null    object
 2   commit_id       786 non-null    object
 3   project_url     781 non-null    object
 4   commit_url      786 non-null    object
 5   commit_message  581 non-null    object
 6   target          786 non-null    int64
 7   func            786 non-null    object
 8   func_hash       786 non-null    object
 9   file_name       507 non-null    object
 10  file_hash       507 non-null    object
 11  cwe             786 non-null    object
 12  cve             786 non-null    object
 13  cve_desc        786 non-null    object
 14  nvd_url         786 non-null    object
 15  code            786 non-null    object
 16  label           786 non-null    int64
dtypes: int64(3), object(14)
memory usage: 104.5+ KB

In [8]:
primevul_cpg_train_df = pd.read_csv("./dataset/primevul_cpg_train.csv")
primevul_cpg_train_df[primevul_cpg_train_df['label'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 273 entries, 1 to 545
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             273 non-null    int64
 1   project         273 non-null    object
 2   commit_id       273 non-null    object
 3   project_url     270 non-null    object
 4   commit_url      273 non-null    object
 5   commit_message  243 non-null    object
 6   target          273 non-null    int64
 7   func            273 non-null    object
 8   func_hash       273 non-null    object
 9   file_name       206 non-null    object
 10  file_hash       206 non-null    object
 11  cwe             273 non-null    object
 12  cve             273 non-null    object
 13  cve_desc        273 non-null    object
 14  nvd_url         273 non-null    object
 15  code            273 non-null    object
 16  label           273 non-null    int64
dtypes: int64(3), object(14)
memory usage: 38.4+ KB

In [9]:
primevul_cpg_val_df = pd.read_csv("./dataset/primevul_cpg_val.csv")
primevul_cpg_val_df[primevul_cpg_val_df['label'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, 0 to 121
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             63 non-null     int64
 1   project         63 non-null     object
 2   commit_id       63 non-null     object
 3   project_url     62 non-null     object
 4   commit_url      63 non-null     object
 5   commit_message  54 non-null     object
 6   target          63 non-null     int64
 7   func            63 non-null     object
 8   func_hash       63 non-null     object
 9   file_name       42 non-null     object
 10  file_hash       42 non-null     object
 11  cwe             63 non-null     object
 12  cve             63 non-null     object
 13  cve_desc        63 non-null     object
 14  nvd_url         63 non-null     object
 15  code            63 non-null     object
 16  label           63 non-null     int64
dtypes: int64(3), object(14)
memory usage: 8.9+ KB

In [10]:
primevul_cpg_test_df = pd.read_csv("./dataset/primevul_cpg_test.csv")
primevul_cpg_test_df[primevul_cpg_test_df['label'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 57 entries, 0 to 115
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             57 non-null     int64
 1   project         57 non-null     object
 2   commit_id       57 non-null     object
 3   project_url     56 non-null     object
 4   commit_url      57 non-null     object
 5   commit_message  46 non-null     object
 6   target          57 non-null     int64
 7   func            57 non-null     object
 8   func_hash       57 non-null     object
 9   file_name       35 non-null     object
 10  file_hash       35 non-null     float64
 11  cwe             57 non-null     object
 12  cve             57 non-null     object
 13  cve_desc        57 non-null     object
 14  nvd_url         57 non-null     object
 15  code            57 non-null     object
 16  label           57 non-null     int64
dtypes: float64(1), int64(3), object(13)
memory usage: 8.0+ KB

In [19]:
len(primevul_cpg_test_df['func_hash'].unique())

117

In [21]:
train_func_hashes = set(primevul_cpg_train_df['func_hash'].unique())
val_func_hashes = set(primevul_cpg_val_df['func_hash'].unique())
test_func_hashes = set(primevul_cpg_test_df['func_hash'].unique())
print(f"Unique function hashes in train: {len(train_func_hashes)}")
print(f"Unique function hashes in val: {len(val_func_hashes)}")
print(f"Unique function hashes in test: {len(test_func_hashes)}")

Unique function hashes in train: 546
Unique function hashes in val: 123
Unique function hashes in test: 117

In [22]:
filtered_train_df = filtered_df[filtered_df['func_hash'].isin(train_func_hashes)]
filtered_val_df = filtered_df[filtered_df['func_hash'].isin(val_func_hashes)]
filtered_test_df = filtered_df[filtered_df['func_hash'].isin(test_func_hashes)]
print(f"Filtered train samples: {len(filtered_train_df)}")
print(f"Filtered val samples: {len(filtered_val_df)}")
print(f"Filtered test samples: {len(filtered_test_df)}")

Filtered train samples: 546
Filtered val samples: 123
Filtered test samples: 117

In [23]:
filtered_train_df.to_csv("./dataset/primevul_filtered_cwe_train.csv", index=False)
filtered_val_df.to_csv("./dataset/primevul_filtered_cwe_val.csv", index=False)
filtered_test_df.to_csv("./dataset/primevul_filtered_cwe_test.csv", index=False)

In [ ]:

with open('./dataset/primevul_filtered_cwe_train.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in filtered_train_df.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'target': row['target'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')


with open('./dataset/primevul_filtered_cwe_val.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in filtered_val_df.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'target': row['target'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')


with open('./dataset/primevul_filtered_cwe_test.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in filtered_test_df.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'target': row['target'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')

In [25]:
primevul_train_df = pd.read_csv("./dataset/primevul_train.csv")
primevul_val_df = pd.read_csv("./dataset/primevul_val.csv")
primevul_test_df = pd.read_csv("./dataset/primevul_test.csv")
primevul_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7759 non-null   object
 4   commit_url      7887 non-null   object
 5   commit_message  5460 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       4699 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7888 non-null   object
 13  cve_desc        7888 non-null   object
 14  nvd_url         7889 non-null   object
 15  code            7889 non-null   object
 16  label           7889 non-null   int64
dtypes: int64(3), object(14)
memory usage: 1.0+ MB

In [26]:
with open('./dataset/primevul_train.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in primevul_train_df.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')


with open('./dataset/primevul_val.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in primevul_val_df.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')


with open('./dataset/primevul_test.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in primevul_test_df.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             986 non-null    int64
 1   project         986 non-null    object
 2   commit_id       986 non-null    object
 3   project_url     977 non-null    object
 4   commit_url      986 non-null    object
 5   commit_message  684 non-null    object
 6   target          986 non-null    int64
 7   func            986 non-null    object
 8   func_hash       986 non-null    object
 9   file_name       600 non-null    object
 10  file_hash       600 non-null    float64
 11  cwe             986 non-null    object
 12  cve             986 non-null    object
 13  cve_desc        986 non-null    object
 14  nvd_url         986 non-null    object
 15  code            986 non-null    object
 16  label           986 non-null    int64
dtypes: float64(1), int64(3), object(13)
memory usage: 131.1+ KB

In [29]:
java_cwe_78_df = pd.read_csv("./dataset/java_babel_CWE-078.csv")
java_cwe_78_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    2120 non-null   object
 1   label   2120 non-null   int64
 2   cwe_id  2120 non-null   object
dtypes: int64(1), object(2)
memory usage: 49.8+ KB

In [30]:
java_cwe_79_df = pd.read_csv("./dataset/java_babel_CWE-079.csv")
java_cwe_79_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6343 entries, 0 to 6342
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    6343 non-null   object
 1   label   6343 non-null   int64
 2   cwe_id  6343 non-null   object
dtypes: int64(1), object(2)
memory usage: 148.8+ KB

In [31]:
java_cwe_78_df['func'] = java_cwe_78_df['code']
java_cwe_78_df['target'] = java_cwe_78_df['label']
java_cwe_79_df['func'] = java_cwe_79_df['code']
java_cwe_79_df['target'] = java_cwe_79_df['label']
java_cwe_78_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    2120 non-null   object
 1   label   2120 non-null   int64
 2   cwe_id  2120 non-null   object
 3   func    2120 non-null   object
 4   target  2120 non-null   int64
dtypes: int64(2), object(3)
memory usage: 82.9+ KB

In [32]:
with open('./dataset/primevul_cwe_078_java.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in java_cwe_78_df.iterrows():
        record = {
            'func': row['func'],
            'cwe_id': row['cwe_id'],
            'code': row['code'],
            'label': int(row['label']),
            'target': int(row['target'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')

In [33]:
with open('./dataset/primevul_cwe_079_java.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in java_cwe_79_df.iterrows():
        record = {
            'func': row['func'],
            'cwe_id': row['cwe_id'],
            'code': row['code'],
            'label': int(row['label']),
            'target': int(row['target'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')

In [36]:
primevul_train = pd.read_csv("./dataset/primevul_train.csv")
primevul_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7759 non-null   object
 4   commit_url      7887 non-null   object
 5   commit_message  5460 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       4699 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7888 non-null   object
 13  cve_desc        7888 non-null   object
 14  nvd_url         7889 non-null   object
 15  code            7889 non-null   object
 16  label           7889 non-null   int64
dtypes: int64(3), object(14)
memory usage: 1.0+ MB

In [37]:
primevul_val = pd.read_csv("./dataset/primevul_val.csv")
primevul_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             986 non-null    int64
 1   project         986 non-null    object
 2   commit_id       986 non-null    object
 3   project_url     977 non-null    object
 4   commit_url      986 non-null    object
 5   commit_message  684 non-null    object
 6   target          986 non-null    int64
 7   func            986 non-null    object
 8   func_hash       986 non-null    object
 9   file_name       600 non-null    object
 10  file_hash       600 non-null    float64
 11  cwe             986 non-null    object
 12  cve             986 non-null    object
 13  cve_desc        986 non-null    object
 14  nvd_url         986 non-null    object
 15  code            986 non-null    object
 16  label           986 non-null    int64
dtypes: float64(1), int64(3), object(13)
memory usage: 131.1+ KB

In [38]:
with open('./dataset/primevul_train_raw.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in primevul_train.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')


with open('./dataset/primevul_val_raw.jsonl', 'w', encoding='utf-8') as f:
    for idx, row in primevul_val.iterrows():
        record = {
            'idx': int(row['idx']),
            'project': row['project'],
            'commit_id': row['commit_id'],
            'func': row['func'],
            'func_hash': row['func_hash'],
            'cwe': row['cwe'],
            'cve': row['cve'],
            'code': row['code'],
            'label': int(row['label'])
        }
        f.write(json.dumps(record, ensure_ascii=False) + '\n')

In [2]:
import json
import pandas as pd
cwe_78_java_data = pd.read_csv(r"C:/hienlt/treesitter/dataset/java(cwe078)_test_cpg.csv")
cwe_78_java_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    2120 non-null   object
 1   label   2120 non-null   int64
 2   cwe_id  2120 non-null   object
dtypes: int64(1), object(2)
memory usage: 49.8+ KB

In [3]:
cwe_78_java_data.iloc[0]['code']

'{\n  "function_name": "badSink",\n  "entry_node_ids": [\n    0\n  ],\n  "exit_node_ids": [\n    1\n  ],\n  "cfg_nodes": {\n    "0": {\n      "cfg_node_id": 0,\n      "node_type": "ENTRY",\n      "source_text": "badSink",\n      "successors": [\n        2\n      ],\n      "predecessors": [],\n      "edge_labels": {},\n      "ast_root_id": "0__ast_185100448",\n      "metadata": {\n        "function_calls": [],\n        "variable_definitions": [\n          "data"\n        ],\n        "variable_uses": []\n      }\n    },\n    "1": {\n      "cfg_node_id": 1,\n      "node_type": "EXIT",\n      "source_text": "badSink",\n      "successors": [],\n      "predecessors": [\n        8\n      ],\n      "edge_labels": {},\n      "ast_root_id": "1__ast_188991280",\n      "metadata": {\n        "function_calls": [],\n        "variable_definitions": [],\n        "variable_uses": []\n      }\n    },\n    "2": {\n      "cfg_node_id": 2,\n      "node_type": "STATEMENT",\n      "source_text": "String osCommand;",\n      "successors": [\n        3\n      ],\n      "predecessors": [\n        0\n      ],\n      "edge_labels": {},\n      "ast_root_id": "2__ast_185926496",\n      "metadata": {\n        "function_calls": [],\n        "variable_definitions": [\n          "osCommand"\n        ],\n        "variable_uses": []\n      }\n    },\n    "3": {\n      "cfg_node_id": 3,\n      "node_type": "CONDITION",\n      "source_text": "(System.getProperty(\\"os.name\\").toLowerCase().indexOf(\\"win\\") >= 0)",\n      "successors": [\n        5,\n        6\n      ],\n      "predecessors": [\n        2\n      ],\n      "edge_labels": {\n        "5": "true",\n        "6": "false"\n      },\n      "ast_root_id": "3__ast_185752296",\n      "metadata": {\n        "function_calls": [\n          "indexOf",\n          "toLowerCase",\n          "getProperty"\n        ],\n        "variable_definitions": [],\n        "variable_uses": []\n      }\n    },\n    "5": {\n      "cfg_node_id": 5,\n      "node_type": "STATEMENT",\n      "source_text": "osCommand=\\"c:\\\\\\\\WINDOWS\\\\\\\\SYSTEM32\\\\\\\\cmd.exe /c dir \\";",\n      "successors": [\n        7\n      ],\n      "predecessors": [\n        3\n      ],\n      "edge_labels": {},\n      "ast_root_id": "5__ast_189859712",\n      "metadata": {\n        "function_calls": [],\n        "variable_definitions": [\n          "osCommand"\n        ],\n        "variable_uses": []\n      }\n    },\n    "6": {\n      "cfg_node_id": 6,\n      "node_type": "STATEMENT",\n      "source_text": "osCommand=\\"/bin/ls \\";",\n      "successors": [\n        7\n      ],\n      "predecessors": [\n        3\n      ],\n      "edge_labels": {},\n      "ast_root_id": "6__ast_190166944",\n      "metadata": {\n        "function_calls": [],\n        "variable_definitions": [\n          "osCommand"\n        ],\n        "variable_uses": []\n      }\n    },\n    "7": {\n      "cfg_node_id": 7,\n      "node_type": "STATEMENT",\n      "source_text": "Process process=Runtime.getRuntime().exec(osCommand + data);",\n      "successors": [\n        8\n      ],\n      "predecessors": [\n        5,\n        6\n      ],\n      "edge_labels": {},\n      "ast_root_id": "7__ast_191618800",\n      "metadata": {\n        "function_calls": [\n          "exec",\n          "getRuntime"\n        ],\n        "variable_definitions": [\n          "process"\n        ],\n        "variable_uses": [\n          "osCommand",\n          "data"\n        ]\n      }\n    },\n    "8": {\n      "cfg_node_id": 8,\n      "node_type": "STATEMENT",\n      "source_text": "process.waitFor();",\n      "successors": [\n        1\n      ],\n      "predecessors": [\n        7\n      ],\n      "edge_labels": {},\n      "ast_root_id": "8__ast_191312928",\n      "metadata": {\n        "function_calls": [\n          "waitFor"\n        ],\n        "variable_definitions": [],\n        "variable_uses": []\n      }\n    }\n  },\n  "ast_nodes": {\n    "0__ast_185100448": {\n      "node_id": "0__ast_185100448",\n      "node_type": "identifier",\n      "text": "badSink",\n      "start_byte": 33,\n      "end_byte": 40,\n      "parent_id": null,\n      "children_ids": []\n    },\n    "1__ast_188991280": {\n      "node_id": "1__ast_188991280",\n      "node_type": "}",\n      "text": "}",\n      "start_byte": 348,\n      "end_byte": 349,\n      "parent_id": null,\n      "children_ids": []\n    },\n    "2__ast_185910752": {\n      "node_id": "2__ast_185910752",\n      "node_type": "type_identifier",\n      "text": "String",\n      "start_byte": 75,\n      "end_byte": 81,\n      "parent_id": "2__ast_185926496",\n      "children_ids": []\n    },\n    "2__ast_186981168": {\n      "node_id": "2__ast_186981168",\n      "node_type": "identifier",\n      "text": "osCommand",\n      "start_byte": 82,\n      "end_byte": 91,\n      "parent_id": "2__ast_186526848",\n      "children_ids": []\n    },\n    "2__ast_186526848": {\n      "node_id": "2__ast_186526848",\n      "node_type": "init_declarator",\n      "text": "osCommand",\n      "start_byte": 82,\n      "end_byte": 91,\n      "parent_id": "2__ast_185926496",\n      "children_ids": [\n        "2__ast_186981168"\n      ]\n    },\n    "2__ast_185926496": {\n      "node_id": "2__ast_185926496",\n      "node_type": "declaration",\n      "text": "String osCommand;",\n      "start_byte": 75,\n      "end_byte": 92,\n      "parent_id": null,\n      "children_ids": [\n        "2__ast_185910752",\n        "2__ast_186526848"\n      ]\n    },\n    "3__ast_185922560": {\n      "node_id": "3__ast_185922560",\n      "node_type": "identifier",\n      "text": "System",\n      "start_byte": 99,\n      "end_byte": 105,\n      "parent_id": "3__ast_188535616",\n      "children_ids": []\n    },\n    "3__ast_186047648": {\n      "node_id": "3__ast_186047648",\n      "node_type": "identifier",\n      "text": "getProperty",\n      "start_byte": 106,\n      "end_byte": 117,\n      "parent_id": "3__ast_188535616",\n      "children_ids": []\n    },\n    "3__ast_188441304": {\n      "node_id": "3__ast_188441304",\n      "node_type": "string_fragment",\n      "text": "os.name",\n      "start_byte": 119,\n      "end_byte": 126,\n      "parent_id": "3__ast_185914688",\n      "children_ids": []\n    },\n    "3__ast_185914688": {\n      "node_id": "3__ast_185914688",\n      "node_type": "string_literal",\n      "text": "\\"os.name\\"",\n      "start_byte": 118,\n      "end_byte": 127,\n      "parent_id": "3__ast_186047656",\n      "children_ids": [\n        "3__ast_188441304"\n      ]\n    },\n    "3__ast_186047656": {\n      "node_id": "3__ast_186047656",\n      "node_type": "argument_list",\n      "text": "(\\"os.name\\")",\n      "start_byte": 117,\n      "end_byte": 128,\n      "parent_id": "3__ast_188535616",\n      "children_ids": [\n        "3__ast_185914688"\n      ]\n    },\n    "3__ast_188535616": {\n      "node_id": "3__ast_188535616",\n      "node_type": "call_expression",\n      "text": "System.getProperty(\\"os.name\\")",\n      "start_byte": 99,\n      "end_byte": 128,\n      "parent_id": "3__ast_188354816",\n      "children_ids": [\n        "3__ast_185922560",\n        "3__ast_186047648",\n        "3__ast_186047656"\n      ]\n    },\n    "3__ast_181998432": {\n      "node_id": "3__ast_181998432",\n      "node_type": "identifier",\n      "text": "toLowerCase",\n      "start_byte": 129,\n      "end_byte": 140,\n      "parent_id": "3__ast_188354816",\n      "children_ids": []\n    },\n    "3__ast_181998440": {\n      "node_id": "3__ast_181998440",\n      "node_type": "argument_list",\n      "text": "()",\n      "start_byte": 140,\n      "end_byte": 142,\n      "parent_id": "3__ast_188354816",\n      "children_ids": []\n    },\n    "3__ast_188354816": {\n      "node_id": "3__ast_188354816",\n      "node_type": "call_expression",\n      "text": "System.getProperty(\\"os.name\\").toLowerCase()",\n      "start_byte": 99,\n      "end_byte": 142,\n      "parent_id": "3__ast_188802944",\n      "children_ids": [\n        "3__ast_188535616",\n        "3__ast_181998432",\n        "3__ast_181998440"\n      ]\n    },\n    "3__ast_185931072": {\n      "node_id": "3__ast_185931072",\n      "node_type": "identifier",\n      "text": "indexOf",\n      "start_byte": 143,\n      "end_byte": 150,\n      "parent_id": "3__ast_188802944",\n      "children_ids": []\n    },\n    "3__ast_188347032": {\n      "node_id": "3__ast_188347032",\n      "node_type": "string_fragment",\n      "text": "win",\n      "start_byte": 152,\n      "end_byte": 155,\n      "parent_id": "3__ast_188062528",\n      "children_ids": []\n    },\n    "3__ast_188062528": {\n      "node_id": "3__ast_188062528",\n      "node_type": "string_literal",\n      "text": "\\"win\\"",\n      "start_byte": 151,\n      "end_byte": 156,\n      "parent_id": "3__ast_185931080",\n      "children_ids": [\n        "3__ast_188347032"\n      ]\n    },\n    "3__ast_185931080": {\n      "node_id": "3__ast_185931080",\n      "node_type": "argument_list",\n      "text": "(\\"win\\")",\n      "start_byte": 150,\n      "end_byte": 157,\n      "parent_id": "3__ast_188802944",\n      "children_ids": [\n        "3__ast_188062528"\n      ]\n    },\n    "3__ast_188802944": {\n      "node_id": "3__ast_188802944",\n      "node_type": "call_expression",\n      "text": "System.getProperty(\\"os.name\\").toLowerCase().indexOf(\\"win\\")",\n      "start_byte": 99,\n      "end_byte": 157,\n      "parent_id": "3__ast_188361792",\n      "children_ids": [\n        "3__ast_188354816",\n        "3__ast_185931072",\n        "3__ast_185931080"\n      ]\n    },\n    "3__ast_187949616": {\n      "node_id": "3__ast_187949616",\n      "node_type": "number_literal",\n      "text": "0",\n      "start_byte": 161,\n      "end_byte": 162,\n      "parent_id": "3__ast_188361792",\n      "children_ids": []\n    },\n    "3__ast_188361792": {\n      "node_id": "3__ast_188361792",\n      "node_type": "binary_expression",\n      "text": "System.getProperty(\\"os.name\\").toLowerCase().indexOf(\\"win\\") >= 0",\n      "start_byte": 99,\n      "end_byte": 162,\n      "parent_id": "3__ast_185752296",\n      "children_ids": [\n        "3__ast_188802944",\n        "3__ast_187949616"\n      ]\n    },\n    "3__ast_185752296": {\n      "node_id": "3__ast_185752296",\n      "node_type": "condition",\n      "text": "(System.getProperty(\\"os.name\\").toLowerCase().indexOf(\\"win\\") >= 0)",\n      "start_byte": 98,\n      "end_byte": 163,\n      "parent_id": null,\n      "children_ids": [\n        "3__ast_188361792"\n      ]\n    },\n    "5__ast_188533872": {\n      "node_id": "5__ast_188533872",\n      "node_type": "identifier",\n      "text": "osCommand",\n      "start_byte": 170,\n      "end_byte": 179,\n      "parent_id": "5__ast_189863680",\n      "children_ids": []\n    },\n    "5__ast_188628000": {\n      "node_id": "5__ast_188628000",\n      "node_type": "string_fragment",\n      "text": "c:",\n      "start_byte": 181,\n      "end_byte": 183,\n      "parent_id": "5__ast_188557200",\n      "children_ids": []\n    },\n    "5__ast_188628008": {\n      "node_id": "5__ast_188628008",\n      "node_type": "escape_sequence",\n      "text": "\\\\\\\\",\n      "start_byte": 183,\n      "end_byte": 185,\n      "parent_id": "5__ast_188557200",\n      "children_ids": []\n    },\n    "5__ast_190320880": {\n      "node_id": "5__ast_190320880",\n      "node_type": "string_fragment",\n      "text": "WINDOWS",\n      "start_byte": 185,\n      "end_byte": 192,\n      "parent_id": "5__ast_188557200",\n      "children_ids": []\n    },\n    "5__ast_190320888": {\n      "node_id": "5__ast_190320888",\n      "node_type": "escape_sequence",\n      "text": "\\\\\\\\",\n      "start_byte": 192,\n      "end_byte": 194,\n      "parent_id": "5__ast_188557200",\n      "children_ids": []\n    },\n    "5__ast_189653872": {\n      "node_id": "5__ast_189653872",\n      "node_type": "string_fragment",\n      "text": "SYSTEM32",\n      "start_byte": 194,\n      "end_byte": 202,\n      "parent_id": "5__ast_188557200",\n      "children_ids": []\n    },\n    "5__ast_189653880": {\n      "node_id": "5__ast_189653880",\n      "node_type": "escape_sequence",\n      "text": "\\\\\\\\",\n      "start_byte": 202,\n      "end_byte": 204,\n      "parent_id": "5__ast_188557200",\n      "children_ids": []\n    },\n    "5__ast_189191976": {\n      "node_id": "5__ast_189191976",\n      "node_type": "string_fragment",\n      "text": "cmd.exe /c dir",\n      "start_byte": 204,\n      "end_byte": 219,\n      "parent_id": "5__ast_188557200",\n      "children_ids": []\n    },\n    "5__ast_188557200": {\n      "node_id": "5__ast_188557200",\n      "node_type": "string_literal",\n      "text": "\\"c:\\\\\\\\WINDOWS\\\\\\\\SYSTEM32\\\\\\\\cmd.exe /c dir \\"",\n      "start_byte": 180,\n      "end_byte": 220,\n      "parent_id": "5__ast_189863680",\n      "children_ids": [\n        "5__ast_188628000",\n        "5__ast_188628008",\n        "5__ast_190320880",\n        "5__ast_190320888",\n        "5__ast_189653872",\n        "5__ast_189653880",\n        "5__ast_189191976"\n      ]\n    },\n    "5__ast_189863680": {\n      "node_id": "5__ast_189863680",\n      "node_type": "assignment_expression",\n      "text": "osCommand=\\"c:\\\\\\\\WINDOWS\\\\\\\\SYSTEM32\\\\\\\\cmd.exe /c dir \\"",\n      "start_byte": 170,\n      "end_byte": 220,\n      "parent_id": "5__ast_189859712",\n      "children_ids": [\n        "5__ast_188533872",\n        "5__ast_188557200"\n      ]\n    },\n    "5__ast_189859712": {\n      "node_id": "5__ast_189859712",\n      "node_type": "expression_statement",\n      "text": "osCommand=\\"c:\\\\\\\\WINDOWS\\\\\\\\SYSTEM32\\\\\\\\cmd.exe /c dir \\";",\n      "start_byte": 170,\n      "end_byte": 221,\n      "parent_id": null,\n      "children_ids": [\n        "5__ast_189863680"\n      ]\n    },\n    "6__ast_191887184": {\n      "node_id": "6__ast_191887184",\n      "node_type": "identifier",\n      "text": "osCommand",\n      "start_byte": 238,\n      "end_byte": 247,\n      "parent_id": "6__ast_190169712",\n      "children_ids": []\n    },\n    "6__ast_191837144": {\n      "node_id": "6__ast_191837144",\n      "node_type": "string_fragment",\n      "text": "/bin/ls",\n      "start_byte": 249,\n      "end_byte": 257,\n      "parent_id": "6__ast_189299120",\n      "children_ids": []\n    },\n    "6__ast_189299120": {\n      "node_id": "6__ast_189299120",\n      "node_type": "string_literal",\n      "text": "\\"/bin/ls \\"",\n      "start_byte": 248,\n      "end_byte": 258,\n      "parent_id": "6__ast_190169712",\n      "children_ids": [\n        "6__ast_191837144"\n      ]\n    },\n    "6__ast_190169712": {\n      "node_id": "6__ast_190169712",\n      "node_type": "assignment_expression",\n      "text": "osCommand=\\"/bin/ls \\"",\n      "start_byte": 238,\n      "end_byte": 258,\n      "parent_id": "6__ast_190166944",\n      "children_ids": [\n        "6__ast_191887184",\n        "6__ast_189299120"\n      ]\n    },\n    "6__ast_190166944": {\n      "node_id": "6__ast_190166944",\n      "node_type": "expression_statement",\n      "text": "osCommand=\\"/bin/ls \\";",\n      "start_byte": 238,\n      "end_byte": 259,\n      "parent_id": null,\n      "children_ids": [\n        "6__ast_190169712"\n      ]\n    },\n    "7__ast_187106768": {\n      "node_id": "7__ast_187106768",\n      "node_type": "type_identifier",\n      "text": "Process",\n      "start_byte": 266,\n      "end_byte": 273,\n      "parent_id": "7__ast_191618800",\n      "children_ids": []\n    },\n    "7__ast_187101088": {\n      "node_id": "7__ast_187101088",\n      "node_type": "identifier",\n      "text": "process",\n      "start_byte": 274,\n      "end_byte": 281,\n      "parent_id": "7__ast_191064768",\n      "children_ids": []\n    },\n    "7__ast_189816320": {\n      "node_id": "7__ast_189816320",\n      "node_type": "identifier",\n      "text": "Runtime",\n      "start_byte": 282,\n      "end_byte": 289,\n      "parent_id": "7__ast_191118848",\n      "children_ids": []\n    },\n    "7__ast_185856928": {\n      "node_id": "7__ast_185856928",\n      "node_type": "identifier",\n      "text": "getRuntime",\n      "start_byte": 290,\n      "end_byte": 300,\n      "parent_id": "7__ast_191118848",\n      "children_ids": []\n    },\n    "7__ast_185856936": {\n      "node_id": "7__ast_185856936",\n      "node_type": "argument_list",\n      "text": "()",\n      "start_byte": 300,\n      "end_byte": 302,\n      "parent_id": "7__ast_191118848",\n      "children_ids": []\n    },\n    "7__ast_191118848": {\n      "node_id": "7__ast_191118848",\n      "node_type": "call_expression",\n      "text": "Runtime.getRuntime()",\n      "start_byte": 282,\n      "end_byte": 302,\n      "parent_id": "7__ast_190281968",\n      "children_ids": [\n        "7__ast_189816320",\n        "7__ast_185856928",\n        "7__ast_185856936"\n      ]\n    },\n    "7__ast_188173632": {\n      "node_id": "7__ast_188173632",\n      "node_type": "identifier",\n      "text": "exec",\n      "start_byte": 303,\n      "end_byte": 307,\n      "parent_id": "7__ast_190281968",\n      "children_ids": []\n    },\n    "7__ast_190908544": {\n      "node_id": "7__ast_190908544",\n      "node_type": "identifier",\n      "text": "osCommand",\n      "start_byte": 308,\n      "end_byte": 317,\n      "parent_id": "7__ast_186523552",\n      "children_ids": []\n    },\n    "7__ast_190478560": {\n      "node_id": "7__ast_190478560",\n      "node_type": "identifier",\n      "text": "data",\n      "start_byte": 320,\n      "end_byte": 324,\n      "parent_id": "7__ast_186523552",\n      "children_ids": []\n    },\n    "7__ast_186523552": {\n      "node_id": "7__ast_186523552",\n      "node_type": "binary_expression",\n      "text": "osCommand + data",\n      "start_byte": 308,\n      "end_byte": 324,\n      "parent_id": "7__ast_188173640",\n      "children_ids": [\n        "7__ast_190908544",\n        "7__ast_190478560"\n      ]\n    },\n    "7__ast_188173640": {\n      "node_id": "7__ast_188173640",\n      "node_type": "argument_list",\n      "text": "(osCommand + data)",\n      "start_byte": 307,\n      "end_byte": 325,\n      "parent_id": "7__ast_190281968",\n      "children_ids": [\n        "7__ast_186523552"\n      ]\n    },\n    "7__ast_190281968": {\n      "node_id": "7__ast_190281968",\n      "node_type": "call_expression",\n      "text": "Runtime.getRuntime().exec(osCommand + data)",\n      "start_byte": 282,\n      "end_byte": 325,\n      "parent_id": "7__ast_191064768",\n      "children_ids": [\n        "7__ast_191118848",\n        "7__ast_188173632",\n        "7__ast_188173640"\n      ]\n    },\n    "7__ast_191064768": {\n      "node_id": "7__ast_191064768",\n      "node_type": "init_declarator",\n      "text": "process=Runtime.getRuntime().exec(osCommand + data)",\n      "start_byte": 274,\n      "end_byte": 325,\n      "parent_id": "7__ast_191618800",\n      "children_ids": [\n        "7__ast_187101088",\n        "7__ast_190281968"\n      ]\n    },\n    "7__ast_191618800": {\n      "node_id": "7__ast_191618800",\n      "node_type": "declaration",\n      "text": "Process process=Runtime.getRuntime().exec(osCommand + data);",\n      "start_byte": 266,\n      "end_byte": 326,\n      "parent_id": null,\n      "children_ids": [\n        "7__ast_187106768",\n        "7__ast_191064768"\n      ]\n    },\n    "8__ast_191613984": {\n      "node_id": "8__ast_191613984",\n      "node_type": "identifier",\n      "text": "process",\n      "start_byte": 329,\n      "end_byte": 336,\n      "parent_id": "8__ast_191387120",\n      "children_ids": []\n    },\n    "8__ast_190422640": {\n      "node_id": "8__ast_190422640",\n      "node_type": "identifier",\n      "text": "waitFor",\n      "start_byte": 337,\n      "end_byte": 344,\n      "parent_id": "8__ast_191387120",\n      "children_ids": []\n    },\n    "8__ast_190422648": {\n      "node_id": "8__ast_190422648",\n      "node_type": "argument_list",\n      "text": "()",\n      

In [2]:
primevul_df = pd.concat([primevul_train_df, primevul_val_df, primevul_test_df], ignore_index=True)
primevul_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9862 entries, 0 to 9861
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             9862 non-null   int64
 1   project         9862 non-null   object
 2   commit_id       9862 non-null   object
 3   project_url     9862 non-null   object
 4   commit_url      9862 non-null   object
 5   commit_message  9862 non-null   object
 6   target          9862 non-null   int64
 7   func            9862 non-null   object
 8   func_hash       9862 non-null   object
 9   file_name       9862 non-null   object
 10  file_hash       5882 non-null   object
 11  cwe             9862 non-null   object
 12  cve             9862 non-null   object
 13  cve_desc        9862 non-null   object
 14  nvd_url         9862 non-null   object
dtypes: int64(2), object(13)
memory usage: 1.1+ MB

In [11]:
primevul_df[primevul_df['file_name'].str.endswith('cpp')]

,idx,project,commit_id,project_url,commit_url,commit_message,target,func,func_hash,file_name,file_hash,cwe,cve,cve_desc,nvd_url
25,201923,exiv2,ae20c30805b330275b2aa0303a42e1f2bbd53661,https://github.com/Exiv2/exiv2,https://github.com/Exiv2/exiv2/commit/ae20c308...,Avoid null pointer exception due to NULL retur...,1,"int Exiv2::http(Exiv2::Dictionary& request,Exi...",145049442908546259270082234561426436152,http.cpp,5346175185590356858756044964563927268,[CWE-476],CVE-2019-13114,http.c in Exiv2 through 0.27.1 allows a malici...,https://nvd.nist.gov/vuln/detail/CVE-2019-13114
115,210876,soundtouch,7f594f8b7d10bbc16a4a31de8ec5a279af9c7378,https://gitlab.com/soundtouch/soundtouch,https://gitlab.com/soundtouch/soundtouch/commi...,New take on CVE-2018-17097 i.e. avoiding writi...,1,"void WavOutFile::write(const float *buffer, in...",164120031578096869690860593950130126980,WavFile.cpp,53671190571791452801356914943333718357,[CWE-415],CVE-2018-17097,The WavFileBase class in WavFile.cpp in Olli P...,https://nvd.nist.gov/vuln/detail/CVE-2018-17097
181,196628,UltraVNC,36a31b37b98f70c1db0428f5ad83170d604fb352,https://github.com/ultravnc/UltraVNC,https://github.com/ultravnc/UltraVNC/commit/36...,security fix,1,"vncProperties::DialogProc(HWND hwnd,\r\n\t\t\t...",291924002574413482295325424251521938521,vncproperties.cpp,147164361005981707680921279120931950785,[CWE-787],CVE-2022-24750,UltraVNC is a free and open source remote pc a...,https://nvd.nist.gov/vuln/detail/CVE-2022-24750
195,210773,soundtouch,46531e5b92dd80dd9a7947463d6224fc7cb21967,https://gitlab.com/soundtouch/soundtouch,https://gitlab.com/soundtouch/soundtouch/commi...,Improved WavFile header/fact not-too-small check,1,int WavInFile::readHeaderBlock()\r\n{\r\n c...,7897298272603014668627834597794294737,WavFile.cpp,26307841655405582680552799835367702119,[CWE-119],CVE-2018-1000223,soundtouch version up to and including 2.0.0 c...,https://nvd.nist.gov/vuln/detail/CVE-2018-1000223
260,202264,sddm,147cec383892d143b5e02daa70f1e7def50f5d98,https://github.com/sddm/sddm,https://github.com/sddm/sddm/commit/147cec3838...,Fix authentication when reusing an existing se...,1,void Display::startAuth(const QString &use...,327396237864777625079937073508587466570,Display.cpp,72356549567103509880179117525547273665,[CWE-284],CVE-2018-14345,An issue was discovered in SDDM through 0.17.0...,https://nvd.nist.gov/vuln/detail/CVE-2018-14345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9527,205958,sddm,4cfed6b0a625593fb43876f04badc4dd99799d86,https://github.com/sddm/sddm,https://github.com/sddm/sddm/commit/4cfed6b0a6...,Disable greeters from loading KDE's debug hand...,1,bool Greeter::start() {\n // check ...,136734524702089631519946301451150014852,Greeter.cpp,284865748290187101329901408755019415552.0,[CWE-284],CVE-2015-0856,daemon/Greeter.cpp in sddm before 0.13.0 does ...,https://nvd.nist.gov/vuln/detail/CVE-2015-0856
9554,211964,libsass,25c9b4952f5838b615da996035453967d0420f57,https://github.com/sass/libsass,https://github.com/sass/libsass/commit/25c9b49...,Fix minor issue with attribute selector unific...,1,Compound_Selector_Ptr Simple_Selector::unify...,39035153849612373033918284657126545526,ast.cpp,114933803620651680233704398560618872832.0,[CWE-674],CVE-2018-20822,LibSass 3.5.4 allows attackers to cause a deni...,https://nvd.nist.gov/vuln/detail/CVE-2018-20822
9568,215076,soundtouch,107f2c5d201a4dfea1b7f15c5957ff2ac9e5f260,https://gitlab.com/soundtouch/soundtouch,https://gitlab.com/soundtouch/soundtouch/commi...,Replaced illegal-number-of-channel assertions ...,1,void FIFOSampleBuffer::setChannels(int numChan...,164034081006483642009413656634630712191,FIFOSampleBuffer.cpp,181203205514363666656086276261655085056.0,[CWE-617],CVE-2018-14044,The RateTransposer::setChannels function in Ra...,https://nvd.nist.gov/vuln/detail/CVE-2018-14044
9695,199947,exiv2,8cd95e221889e41e9cc153e2cfb5a7b41c7bc7a4,https://github.com/Exiv2/exiv2,https://github.com/Exiv2/exiv2/commit/8cd95e22...,Avoid negative integer overflow when `chunkLen...,1,void PngImage::readMetadata()\n {\n#ifd...,263518100976085807650407921802733926535,pngimage.cpp,106013720895003026169779231174462275584.0,[CWE-190],CVE-2019-13108,An integer overflow in Exiv2 through 0.27.1 al...,https://nvd.nist.gov/vuln/detail/CVE-2019-13108
9774,212397,wesnoth,b2738ffb2fdd2550ececb74f76f75583c43c8b59,https://github.com/wesnoth/wesnoth,https://github.com/wesnoth/wesnoth/commit/b273...,Use looks_like_pbl() to disallow .pbl file inc...,1,static bool is_legal_file(const std::string &f...,287040035058025521865104366820345442913,filesystem_boost.cpp,24680439132295310775322423558968180736.0,[CWE-200],CVE-2015-5070,The (1) filesystem::get_wml_location function ...,https://nvd.nist.gov/vuln/detail/CVE-2015-5070

In [13]:
primevul_df[primevul_df['target'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 4862 entries, 1 to 9858
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             4862 non-null   int64
 1   project         4862 non-null   object
 2   commit_id       4862 non-null   object
 3   project_url     4862 non-null   object
 4   commit_url      4862 non-null   object
 5   commit_message  4862 non-null   object
 6   target          4862 non-null   int64
 7   func            4862 non-null   object
 8   func_hash       4862 non-null   object
 9   file_name       4862 non-null   object
 10  file_hash       3359 non-null   object
 11  cwe             4862 non-null   object
 12  cve             4862 non-null   object
 13  cve_desc        4862 non-null   object
 14  nvd_url         4862 non-null   object
dtypes: int64(2), object(13)
memory usage: 607.8+ KB

In [14]:
sven_train = pd.read_parquet("C:/hienlt/treesitter/dataset/SVEN/train.parquet")
sven_val = pd.read_parquet("C:/hienlt/treesitter/dataset/SVEN/val.parquet")
sven_full = pd.concat([sven_train, sven_val], ignore_index=True)
sven_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   func_name        803 non-null    object
 1   func_src_before  803 non-null    object
 2   func_src_after   803 non-null    object
 3   line_changes     803 non-null    object
 4   char_changes     803 non-null    object
 5   commit_link      803 non-null    object
 6   file_name        803 non-null    object
 7   vul_type         803 non-null    object
dtypes: object(8)
memory usage: 50.3+ KB

In [17]:
len(sven_full[sven_full['file_name'].str.endswith('.py')])

380

In [19]:
import json
import pandas as pd
data_train = []
with open("C:/hienlt/treesitter/dataset/RespoVul/train_c_cpp.jsonl", 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

respo_train_df = pd.DataFrame(data_train)
respo_train_df.info()

data_val = []
with open("C:/hienlt/treesitter/dataset/RespoVul/valid_c_cpp.jsonl", 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

respo_val_df = pd.DataFrame(data_val)
respo_val_df.info()


data_test = []
with open("C:/hienlt/treesitter/dataset/RespoVul/test_c_cpp.jsonl", 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_test.append(record)

respo_test_df = pd.DataFrame(data_test)
respo_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185791 entries, 0 to 185790
Data columns (total 39 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   function_id       185791 non-null  object
 1   function          185791 non-null  object
 2   target            185791 non-null  int64
 3   function_numbers  185791 non-null  object
 4   line_numbers      185791 non-null  object
 5   commit_id         185791 non-null  object
 6   cve_id            185791 non-null  object
 7   cve_language      185791 non-null  object
 8   cve_description   185791 non-null  object
 9   cvss              185791 non-null  object
 10  publish_date      185791 non-null  object
 11  cwe_id            185791 non-null  object
 12  cwe_description   185791 non-null  object
 13  cwe_consequence   185791 non-null  object
 14  cwe_method        185791 non-null  object
 15  cwe_solution      185791 non-null  object
 16  AV                185791 non-null  object
 17  AC                185791 non-null  object
 18  PR                185791 non-null  object
 19  UI                185791 non-null  object
 20  S                 185791 non-null  object
 21  C                 185791 non-null  object
 22  I                 185791 non-null  object
 23  A                 185791 non-null  object
 24  commit_message    185791 non-null  object
 25  commit_date       185791 non-null  object
 26  parents           185791 non-null  object
 27  project           185791 non-null  object
 28  outdated          185791 non-null  int64
 29  url               185791 non-null  object
 30  file_path         185791 non-null  object
 31  file_name         185791 non-null  object
 32  file_language     185791 non-null  object
 33  file_target       185791 non-null  int64
 34  static            185791 non-null  object
 35  caller            185791 non-null  object
 36  callee            185791 non-null  object
 37  caller_of_change  185791 non-null  object
 38  callee_of_change  185791 non-null  object
dtypes: int64(3), object(36)
memory usage: 55.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23224 entries, 0 to 23223
Data columns (total 39 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   function_id       23224 non-null  object
 1   function          23224 non-null  object
 2   target            23224 non-null  int64
 3   function_numbers  23224 non-null  object
 4   line_numbers      23224 non-null  object
 5   commit_id         23224 non-null  object
 6   cve_id            23224 non-null  object
 7   cve_language      23224 non-null  object
 8   cve_description   23224 non-null  object
 9   cvss              23224 non-null  object
 10  publish_date      23224 non-null  object
 11  cwe_id            23224 non-null  object
 12  cwe_description   23224 non-null  object
 13  cwe_consequence   23224 non-null  object
 14  cwe_method        23224 non-null  object
 15  cwe_solution      23224 non-null  object
 16  AV                23224 non-null  object
 17  AC                23224 non-null  object
 18  PR                23224 non-null  object
 19  UI                23224 non-null  object
 20  S                 23224 non-null  object
 21  C                 23224 non-null  object
 22  I                 23224 non-null  object
 23  A                 23224 non-null  object
 24  commit_message    23224 non-null  object
 25  commit_date       23224 non-null  object
 26  parents           23224 non-null  object
 27  project           23224 non-null  object
 28  outdated          23224 non-null  int64
 29  url               23224 non-null  object
 30  file_path         23224 non-null  object
 31  file_name         23224 non-null  object
 32  file_language     23224 non-null  object
 33  file_target       23224 non-null  int64
 34  static            23224 non-null  object
 35  caller            23224 non-null  object
 36  callee            23224 non-null  object
 37  caller_of_change  23224 non-null  object
 38  callee_of_change  23224 non-null  object
dtypes: int64(3), object(36)
memory usage: 6.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23224 entries, 0 to 23223
Data columns (total 39 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   function_id       23224 non-null  object
 1   function          23224 non-null  object
 2   target            23224 non-null  int64
 3   function_numbers  23224 non-null  object
 4   line_numbers      23224 non-null  object
 5   commit_id         23224 non-null  object
 6   cve_id            23224 non-null  object
 7   cve_language      23224 non-null  object
 8   cve_description   23224 non-null  object
 9   cvss              23224 non-null  object
 10  publish_date      23224 non-null  object
 11  cwe_id            23224 non-null  object
 12  cwe_description   23224 non-null  object
 13  cwe_consequence   23224 non-null  object
 14  cwe_method        23224 non-null  object
 15  cwe_solution      23224 non-null  object
 16  AV                23224 non-null  object
 17  AC                23224 non-null  object
 18  PR                23224 non-null  object
 19  UI                23224 non-null  object
 20  S                 23224 non-null  object
 21  C                 23224 non-null  object
 22  I                 23224 non-null  object
 23  A                 23224 non-null  object
 24  commit_message    23224 non-null  object
 25  commit_date       23224 non-null  object
 26  parents           23224 non-null  object
 27  project           23224 non-null  object
 28  outdated          23224 non-null  int64
 29  url               23224 non-null  object
 30  file_path         23224 non-null  object
 31  file_name         23224 non-null  object
 32  file_language     23224 non-null  object
 33  file_target       23224 non-null  int64
 34  static            23224 non-null  object
 35  caller            23224 non-null  object
 36  callee            23224 non-null  object
 37  caller_of_change  23224 non-null  object
 38  callee_of_change  23224 non-null  object
dtypes: int64(3), object(36)
memory usage: 6.9+ MB

In [20]:
respo_full_df = pd.concat([respo_train_df, respo_val_df, respo_test_df], ignore_index=True)
respo_full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232239 entries, 0 to 232238
Data columns (total 39 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   function_id       232239 non-null  object
 1   function          232239 non-null  object
 2   target            232239 non-null  int64
 3   function_numbers  232239 non-null  object
 4   line_numbers      232239 non-null  object
 5   commit_id         232239 non-null  object
 6   cve_id            232239 non-null  object
 7   cve_language      232239 non-null  object
 8   cve_description   232239 non-null  object
 9   cvss              232239 non-null  object
 10  publish_date      232239 non-null  object
 11  cwe_id            232239 non-null  object
 12  cwe_description   232239 non-null  object
 13  cwe_consequence   232239 non-null  object
 14  cwe_method        232239 non-null  object
 15  cwe_solution      232239 non-null  object
 16  AV                232239 non-null  object
 17  AC                232239 non-null  object
 18  PR                232239 non-null  object
 19  UI                232239 non-null  object
 20  S                 232239 non-null  object
 21  C                 232239 non-null  object
 22  I                 232239 non-null  object
 23  A                 232239 non-null  object
 24  commit_message    232239 non-null  object
 25  commit_date       232239 non-null  object
 26  parents           232239 non-null  object
 27  project           232239 non-null  object
 28  outdated          232239 non-null  int64
 29  url               232239 non-null  object
 30  file_path         232239 non-null  object
 31  file_name         232239 non-null  object
 32  file_language     232239 non-null  object
 33  file_target       232239 non-null  int64
 34  static            232239 non-null  object
 35  caller            232239 non-null  object
 36  callee            232239 non-null  object
 37  caller_of_change  232239 non-null  object
 38  callee_of_change  232239 non-null  object
dtypes: int64(3), object(36)
memory usage: 69.1+ MB

In [22]:
respo_full_df['file_target'].unique()

array([-1,  0,  1])

In [1]:
import json
import pandas as pd
data_c = []
with open("C:/hienlt/treesitter/dataset/RespoVul/ReposVul_c.jsonl", 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_c.append(record)

respo_c_df = pd.DataFrame(data_c)
respo_c_df.info()

data_cpp = []
with open("C:/hienlt/treesitter/dataset/RespoVul/ReposVul_cpp.jsonl", 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_cpp.append(record)

respo_cpp_df = pd.DataFrame(data_cpp)
respo_cpp_df.info()

data_java = []
with open("C:/hienlt/treesitter/dataset/RespoVul/ReposVul_java.jsonl", 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_java.append(record)

respo_java_df = pd.DataFrame(data_java)
respo_java_df.info()

data_python = []
with open("C:/hienlt/treesitter/dataset/RespoVul/ReposVul_python.jsonl", 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_python.append(record)

respo_python_df = pd.DataFrame(data_python)
respo_python_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4010 entries, 0 to 4009
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            4010 non-null   int64
 1   cve_id           4010 non-null   object
 2   cwe_id           4010 non-null   object
 3   cve_language     4010 non-null   object
 4   cve_description  4010 non-null   object
 5   cvss             4010 non-null   object
 6   publish_date     4010 non-null   object
 7   AV               4010 non-null   object
 8   AC               4010 non-null   object
 9   PR               4010 non-null   object
 10  UI               4010 non-null   object
 11  S                4010 non-null   object
 12  C                4010 non-null   object
 13  I                4010 non-null   object
 14  A                4010 non-null   object
 15  commit_id        4010 non-null   object
 16  commit_message   4010 non-null   object
 17  commit_date      4010 non-null   object
 18  project          4010 non-null   object
 19  url              4010 non-null   object
 20  html_url         4010 non-null   object
 21  windows_before   4010 non-null   object
 22  windows_after    4010 non-null   object
 23  parents          4010 non-null   object
 24  details          4010 non-null   object
 25  outdated         4010 non-null   int64
 26  cwe_descripiton  4010 non-null   object
 27  cwe_consequence  4010 non-null   object
 28  cwe_method       4010 non-null   object
 29  cwe_solution     4010 non-null   object
dtypes: int64(2), object(28)
memory usage: 940.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            689 non-null    int64
 1   cve_id           689 non-null    object
 2   cwe_id           689 non-null    object
 3   cve_language     689 non-null    object
 4   cve_description  689 non-null    object
 5   cvss             689 non-null    object
 6   publish_date     689 non-null    object
 7   AV               689 non-null    object
 8   AC               689 non-null    object
 9   PR               689 non-null    object
 10  UI               689 non-null    object
 11  S                689 non-null    object
 12  C                689 non-null    object
 13  I                689 non-null    object
 14  A                689 non-null    object
 15  commit_id        689 non-null    object
 16  commit_message   689 non-null    object
 17  commit_date      689 non-null    object
 18  project          689 non-null    object
 19  url              689 non-null    object
 20  html_url         689 non-null    object
 21  windows_before   689 non-null    object
 22  windows_after    689 non-null    object
 23  parents          689 non-null    object
 24  details          689 non-null    object
 25  outdated         689 non-null    int64
 26  cwe_descripiton  689 non-null    object
 27  cwe_consequence  689 non-null    object
 28  cwe_method       689 non-null    object
 29  cwe_solution     689 non-null    object
dtypes: int64(2), object(28)
memory usage: 161.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 888 entries, 0 to 887
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            888 non-null    int64
 1   cve_id           888 non-null    object
 2   cwe_id           888 non-null    object
 3   cve_language     888 non-null    object
 4   cve_description  888 non-null    object
 5   cvss             888 non-null    object
 6   publish_date     888 non-null    object
 7   AV               888 non-null    object
 8   AC               888 non-null    object
 9   PR               888 non-null    object
 10  UI               888 non-null    object
 11  S                888 non-null    object
 12  C                888 non-null    object
 13  I                888 non-null    object
 14  A                888 non-null    object
 15  commit_id        888 non-null    object
 16  commit_message   888 non-null    object
 17  commit_date      888 non-null    object
 18  project          888 non-null    object
 19  url              888 non-null    object
 20  html_url         888 non-null    object
 21  windows_before   888 non-null    object
 22  windows_after    888 non-null    object
 23  parents          888 non-null    object
 24  details          888 non-null    object
 25  outdated         888 non-null    int64
 26  cwe_descripiton  888 non-null    object
 27  cwe_consequence  888 non-null    object
 28  cwe_method       888 non-null    object
 29  cwe_solution     888 non-null    object
dtypes: int64(2), object(28)
memory usage: 208.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            1310 non-null   int64
 1   cve_id           1310 non-null   object
 2   cwe_id           1310 non-null   object
 3   cve_language     1310 non-null   object
 4   cve_description  1310 non-null   object
 5   cvss             1310 non-null   object
 6   publish_date     1310 non-null   object
 7   AV               1310 non-null   object
 8   AC               1310 non-null   object
 9   PR               1310 non-null   object
 10  UI               1310 non-null   object
 11  S                1310 non-null   object
 12  C                1310 non-null   object
 13  I                1310 non-null   object
 14  A                1310 non-null   object
 15  commit_id        1310 non-null   object
 16  commit_message   1310 non-null   object
 17  commit_date      1310 non-null   object
 18  project          1310 non-null   object
 19  url              1310 non-null   object
 20  html_url         1310 non-null   object
 21  windows_before   1310 non-null   object
 22  windows_after    1310 non-null   object
 23  parents          1310 non-null   object
 24  details          1310 non-null   object
 25  outdated         1310 non-null   int64
 26  cwe_descripiton  1310 non-null   object
 27  cwe_consequence  1310 non-null   object
 28  cwe_method       1310 non-null   object
 29  cwe_solution     1310 non-null   object
dtypes: int64(2), object(28)
memory usage: 307.2+ KB

In [4]:
respo_python_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            1310 non-null   int64
 1   cve_id           1310 non-null   object
 2   cwe_id           1310 non-null   object
 3   cve_language     1310 non-null   object
 4   cve_description  1310 non-null   object
 5   cvss             1310 non-null   object
 6   publish_date     1310 non-null   object
 7   AV               1310 non-null   object
 8   AC               1310 non-null   object
 9   PR               1310 non-null   object
 10  UI               1310 non-null   object
 11  S                1310 non-null   object
 12  C                1310 non-null   object
 13  I                1310 non-null   object
 14  A                1310 non-null   object
 15  commit_id        1310 non-null   object
 16  commit_message   1310 non-null   object
 17  commit_date      1310 non-null   object
 18  project          1310 non-null   object
 19  url              1310 non-null   object
 20  html_url         1310 non-null   object
 21  windows_before   1310 non-null   object
 22  windows_after    1310 non-null   object
 23  parents          1310 non-null   object
 24  details          1310 non-null   object
 25  outdated         1310 non-null   int64
 26  cwe_descripiton  1310 non-null   object
 27  cwe_consequence  1310 non-null   object
 28  cwe_method       1310 non-null   object
 29  cwe_solution     1310 non-null   object
dtypes: int64(2), object(28)
memory usage: 307.2+ KB

In [34]:
respo_python_df['function'] = respo_python_df['details'].apply(
	lambda x: next(
		(
			item.get('function_before')
			for item in x
			if isinstance(x, list) and isinstance(item, dict) and item.get('function_before') is not None
		),
		None
	)
)

In [35]:
respo_python_df['function']
data_list = []
for idx, row in respo_python_df.iterrows():
    functions = row['function']
    if functions and isinstance(functions, list):
        for func_dict in functions:
            if isinstance(func_dict, dict) and 'function' in func_dict:
                data_list.append({
                    'code': func_dict['function'],
                    'label': func_dict['target']
                })

respo_python_functions_df = pd.DataFrame(data_list)
respo_python_functions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3714 entries, 0 to 3713
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    3714 non-null   object
 1   label   3714 non-null   int64
dtypes: int64(1), object(1)
memory usage: 58.2+ KB

In [37]:
respo_python_functions_df[respo_python_functions_df['label'] == 0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 3610 entries, 0 to 3713
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    3610 non-null   object
 1   label   3610 non-null   int64
dtypes: int64(1), object(1)
memory usage: 84.6+ KB

In [35]:
respo_c_df['target'] = respo_c_df['details'].apply(lambda x: x[0]['target'] if isinstance(x, list) and len(x) > 0 else None)
respo_c_df.info()

KeyError: 'target'

In [20]:
for index, row in respo_python_df.iterrows():
    if isinstance(row['details'], list) and len(row['details']) > 0 and 'target' in row['details'][0]:
        # print(row['details'][0])
        respo_python_df.at[index, 'target'] = row['details'][0]['target']
    else:
        respo_python_df.at[index, 'target'] = None  # Or some default value if target is missing
    # targets.append(row['details'][0]['target'])


respo_python_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            1310 non-null   int64
 1   cve_id           1310 non-null   object
 2   cwe_id           1310 non-null   object
 3   cve_language     1310 non-null   object
 4   cve_description  1310 non-null   object
 5   cvss             1310 non-null   object
 6   publish_date     1310 non-null   object
 7   AV               1310 non-null   object
 8   AC               1310 non-null   object
 9   PR               1310 non-null   object
 10  UI               1310 non-null   object
 11  S                1310 non-null   object
 12  C                1310 non-null   object
 13  I                1310 non-null   object
 14  A                1310 non-null   object
 15  commit_id        1310 non-null   object
 16  commit_message   1310 non-null   object
 17  commit_date      1310 non-null   object
 18  project          1310 non-null   object
 19  url              1310 non-null   object
 20  html_url         1310 non-null   object
 21  windows_before   1310 non-null   object
 22  windows_after    1310 non-null   object
 23  parents          1310 non-null   object
 24  details          1310 non-null   object
 25  outdated         1310 non-null   int64
 26  cwe_descripiton  1310 non-null   object
 27  cwe_consequence  1310 non-null   object
 28  cwe_method       1310 non-null   object
 29  cwe_solution     1310 non-null   object
 30  target           612 non-null    object
dtypes: int64(2), object(29)
memory usage: 317.4+ KB

In [23]:
respo_python_df[respo_python_df['target'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 4 to 1297
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            51 non-null     int64
 1   cve_id           51 non-null     object
 2   cwe_id           51 non-null     object
 3   cve_language     51 non-null     object
 4   cve_description  51 non-null     object
 5   cvss             51 non-null     object
 6   publish_date     51 non-null     object
 7   AV               51 non-null     object
 8   AC               51 non-null     object
 9   PR               51 non-null     object
 10  UI               51 non-null     object
 11  S                51 non-null     object
 12  C                51 non-null     object
 13  I                51 non-null     object
 14  A                51 non-null     object
 15  commit_id        51 non-null     object
 16  commit_message   51 non-null     object
 17  commit_date      51 non-null     object
 18  project          51 non-null     object
 19  url              51 non-null     object
 20  html_url         51 non-null     object
 21  windows_before   51 non-null     object
 22  windows_after    51 non-null     object
 23  parents          51 non-null     object
 24  details          51 non-null     object
 25  outdated         51 non-null     int64
 26  cwe_descripiton  51 non-null     object
 27  cwe_consequence  51 non-null     object
 28  cwe_method       51 non-null     object
 29  cwe_solution     51 non-null     object
 30  target           51 non-null     object
dtypes: int64(2), object(29)
memory usage: 12.8+ KB

In [1]:
import os
from pathlib import Path
import pandas as pd
import json

def load_dataset(base_path):
    """
    Load Java vulnerability dataset from the folder structure.
    
    Args:
        base_path: Path to the dataset folder
        
    Returns:
        pandas.DataFrame with columns: code, label, cwe_id
    """
    data = []
    base_path = Path(base_path)
    
    # Iterate through each CWE folder
    for cwe_folder in base_path.iterdir():
        if not cwe_folder.is_dir():
            continue
            
        cwe_id = cwe_folder.name  # e.g., 'CWE-074'
        
        # Iterate through 'bad' and 'good' subfolders
        for label_folder in ['bad', 'good']:
            label_path = cwe_folder / label_folder
            
            if not label_path.exists():
                continue
            
            # Determine label: 1 for bad (vulnerable), 0 for good (safe)
            label = 1 if label_folder == 'bad' else 0
            
            # Iterate through all .txt files in the folder
            for file_path in label_path.glob('*.txt'):
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    # Extract code (everything before the separator line)
                    # The separator is a line with ^^^^^ or similar pattern
                    lines = content.split('\n')
                    code_lines = []
                    
                    for line in lines:
                        if line.strip().startswith('^'):
                            break
                        code_lines.append(line)
                    
                    code = '\n'.join(code_lines).strip()
                    code = code[:-1]
                    if code:  # Only add if there's actual code
                        data.append({
                            'code': code,
                            'label': label,
                            'cwe_id': cwe_id
                        })
                        
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")
    
    # Create DataFrame
    df = pd.DataFrame(data)
    return df

In [7]:
# Usage
base_path = r'c:/hienlt/treesitter/dataset/SARD/PHP'
df = load_dataset(base_path)

# Display info about the dataset
print(f"Total samples: {len(df)}")
print(f"\nLabel distribution:")
print(df['label'].value_counts())
print(f"\nCWE-ID distribution:")
print(df['cwe_id'].value_counts())
print(f"\nDataFrame shape: {df.shape}")
print(f"\nFirst few rows:")
print(df.head())

Total samples: 37808

Label distribution:
label
0    20754
1    17054
Name: count, dtype: int64

CWE-ID distribution:
cwe_id
CWE-079    10615
CWE-074     7442
CWE-601     5214
CWE-091     4997
CWE-090     4189
CWE-078     2847
CWE-089     2504
Name: count, dtype: int64

DataFrame shape: (37808, 3)

First few rows:
                                                code  label   cwe_id
0  $string = $_POST [ 'UserData' ] ; $tainted = u...      1  CWE-074
1  $descriptorspec = array ( 0 => array ( " pipe ...      1  CWE-074
2  $descriptorspec = array ( 0 => array ( " pipe ...      1  CWE-074
3  $tainted = system ( 'ls' , $retval ) ; $query ...      1  CWE-074
4  $tainted = $_SESSION [ 'UserData' ] ; if ( fil...      1  CWE-074

In [8]:
df.to_csv("./dataset/babel_sard_php.csv", index=False)

In [24]:
import json
import pandas as pd
data_train = []
with open(r'C:/hienlt/treesitter/dataset/Primevul/primevul_train.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

primevul_train_df = pd.DataFrame(data_train)
primevul_train_df.info()

data_val = []
with open(r'C:/hienlt/treesitter/dataset/Primevul/primevul_valid.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

primevul_val_df = pd.DataFrame(data_val)
primevul_val_df.info()


data_test = []
with open(r'C:/hienlt/treesitter/dataset/Primevul/primevul_test.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_test.append(record)

primevul_test_df = pd.DataFrame(data_test)
primevul_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175797 entries, 0 to 175796
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idx             175797 non-null  int64
 1   project         175797 non-null  object
 2   commit_id       175797 non-null  object
 3   project_url     175797 non-null  object
 4   commit_url      175797 non-null  object
 5   commit_message  175797 non-null  object
 6   target          175797 non-null  int64
 7   func            175797 non-null  object
 8   func_hash       175797 non-null  object
 9   file_name       175797 non-null  object
 10  file_hash       120537 non-null  float64
 11  cwe             175797 non-null  object
 12  cve             175797 non-null  object
 13  cve_desc        175797 non-null  object
 14  nvd_url         175797 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 20.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23948 entries, 0 to 23947
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             23948 non-null  int64
 1   project         23948 non-null  object
 2   commit_id       23948 non-null  object
 3   project_url     23948 non-null  object
 4   commit_url      23948 non-null  object
 5   commit_message  23948 non-null  object
 6   target          23948 non-null  int64
 7   func            23948 non-null  object
 8   func_hash       23948 non-null  object
 9   file_name       23948 non-null  object
 10  file_hash       19649 non-null  float64
 11  cwe             23948 non-null  object
 12  cve             23948 non-null  object
 13  cve_desc        23948 non-null  object
 14  nvd_url         23948 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 2.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24788 entries, 0 to 24787
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             24788 non-null  int64
 1   project         24788 non-null  object
 2   commit_id       24788 non-null  object
 3   project_url     24788 non-null  object
 4   commit_url      24788 non-null  object
 5   commit_message  24788 non-null  object
 6   target          24788 non-null  int64
 7   func            24788 non-null  object
 8   func_hash       24788 non-null  object
 9   file_name       24788 non-null  object
 10  file_hash       18878 non-null  float64
 11  cwe             24788 non-null  object
 12  cve             24788 non-null  object
 13  cve_desc        24788 non-null  object
 14  nvd_url         24788 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 2.8+ MB

In [25]:
pv_full_df = pd.concat([primevul_train_df, primevul_val_df, primevul_test_df], ignore_index=True)
pv_full_df[pv_full_df['target'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 6004 entries, 0 to 200803
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             6004 non-null   int64
 1   project         6004 non-null   object
 2   commit_id       6004 non-null   object
 3   project_url     6004 non-null   object
 4   commit_url      6004 non-null   object
 5   commit_message  6004 non-null   object
 6   target          6004 non-null   int64
 7   func            6004 non-null   object
 8   func_hash       6004 non-null   object
 9   file_name       6004 non-null   object
 10  file_hash       4313 non-null   float64
 11  cwe             6004 non-null   object
 12  cve             6004 non-null   object
 13  cve_desc        6004 non-null   object
 14  nvd_url         6004 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 750.5+ KB

In [26]:
pv_full_df[pv_full_df['target'] == 0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 218529 entries, 2607 to 224532
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idx             218529 non-null  int64
 1   project         218529 non-null  object
 2   commit_id       218529 non-null  object
 3   project_url     218529 non-null  object
 4   commit_url      218529 non-null  object
 5   commit_message  218529 non-null  object
 6   target          218529 non-null  int64
 7   func            218529 non-null  object
 8   func_hash       218529 non-null  object
 9   file_name       218529 non-null  object
 10  file_hash       154751 non-null  float64
 11  cwe             218529 non-null  object
 12  cve             218529 non-null  object
 13  cve_desc        218529 non-null  object
 14  nvd_url         218529 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 26.7+ MB

In [10]:
prime_full = pd.concat([primevul_train_df, primevul_val_df, primevul_test_df], ignore_index=True)
prime_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224533 entries, 0 to 224532
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idx             224533 non-null  int64
 1   project         224533 non-null  object
 2   commit_id       224533 non-null  object
 3   project_url     224533 non-null  object
 4   commit_url      224533 non-null  object
 5   commit_message  224533 non-null  object
 6   target          224533 non-null  int64
 7   func            224533 non-null  object
 8   func_hash       224533 non-null  object
 9   file_name       224533 non-null  object
 10  file_hash       159064 non-null  float64
 11  cwe             224533 non-null  object
 12  cve             224533 non-null  object
 13  cve_desc        224533 non-null  object
 14  nvd_url         224533 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 25.7+ MB

In [13]:
prime_full[prime_full['target'] == 0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 218529 entries, 2607 to 224532
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idx             218529 non-null  int64
 1   project         218529 non-null  object
 2   commit_id       218529 non-null  object
 3   project_url     218529 non-null  object
 4   commit_url      218529 non-null  object
 5   commit_message  218529 non-null  object
 6   target          218529 non-null  int64
 7   func            218529 non-null  object
 8   func_hash       218529 non-null  object
 9   file_name       218529 non-null  object
 10  file_hash       154751 non-null  float64
 11  cwe             218529 non-null  object
 12  cve             218529 non-null  object
 13  cve_desc        218529 non-null  object
 14  nvd_url         218529 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 26.7+ MB

In [1]:
import json
import pandas as pd
data_cwe_078 = []
with open(r'C:/hienlt/treesitter/dataset/data_078.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_cwe_078.append(record)

java_078_babel_df = pd.DataFrame(data_cwe_078)
java_078_babel_df.info()

data_cwe_079 = []
with open(r'C:/hienlt/treesitter/dataset/data_079.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_cwe_079.append(record)

java_079_babel_df = pd.DataFrame(data_cwe_079)
java_079_babel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   func    2120 non-null   object
 1   target  2120 non-null   int64
dtypes: int64(1), object(1)
memory usage: 33.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6343 entries, 0 to 6342
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   func    6343 non-null   object
 1   target  6343 non-null   int64
dtypes: int64(1), object(1)
memory usage: 99.2+ KB

In [2]:
java_078_treeclimber_df = pd.read_csv("C:/hienlt/treesitter/dataset/java_babel_CWE-078.csv")
java_078_treeclimber_df.info()
java_079_treeclimber_df = pd.read_csv("C:/hienlt/treesitter/dataset/java_babel_CWE-079.csv")
java_079_treeclimber_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    2120 non-null   object
 1   label   2120 non-null   int64
 2   cwe_id  2120 non-null   object
dtypes: int64(1), object(2)
memory usage: 49.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6343 entries, 0 to 6342
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    6343 non-null   object
 1   label   6343 non-null   int64
 2   cwe_id  6343 non-null   object
dtypes: int64(1), object(2)
memory usage: 148.8+ KB

In [7]:
java_079_babel_df[java_079_babel_df['target'] == 1].head()

                                                   func  target
2198  private void goodG2B2(HttpServletRequest reque...       1
2199  private void goodG2BSink(String data,HttpServl...       1
2200  private void goodG2B1(HttpServletRequest reque...       1
2201  private void goodG2B1(HttpServletRequest reque...       1
2202  private void goodG2B(HttpServletRequest reques...       1

In [8]:
java_079_treeclimber_df[java_079_treeclimber_df['label'] == 1].head()

                                                code  label   cwe_id
0  public void bad(HttpServletRequest request,Htt...      1  CWE-079
1  public void bad(HttpServletRequest request,Htt...      1  CWE-079
2  public void bad(HttpServletRequest request,Htt...      1  CWE-079
3  public void bad(HttpServletRequest request,Htt...      1  CWE-079
4  public void bad(HttpServletRequest request,Htt...      1  CWE-079

In [9]:
java_079_babel_df['target'] = java_079_babel_df['target'].apply(lambda x: 1 if x == 0 else 0)
java_079_babel_df.head()
java_078_babel_df['target'] = java_078_babel_df['target'].apply(lambda x: 1 if x == 0 else 0)
java_078_babel_df.head()

                                                func  target
0  public void bad() throws Throwable {\n  String...       1
1  public void bad() throws Throwable {\n  String...       1
2  public void bad(HttpServletRequest request,Htt...       1
3  public void badSink(LinkedList<String> dataLin...       1
4  public void badSink(String data,HttpServletReq...       1

In [10]:
java_078_babel_df.to_json('./dataset/java_078_babel.jsonl', orient='records', lines=True, force_ascii=False)
java_079_babel_df.to_json('./dataset/java_079_babel.jsonl', orient='records', lines=True, force_ascii=False)

In [13]:
import re
import random
import string

def _rand_str(n=8):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=n))

pattern = re.compile(r'good|bad')

java_079_babel_df['func'] = java_079_babel_df['func'].apply(
    lambda x: pattern.sub(lambda _: _rand_str(), x) if isinstance(x, str) else x
)

java_079_babel_df.head()

                                                func  target
0  public void HwU3OtYa(HttpServletRequest reques...       1
1  public void MwRfenwp(HttpServletRequest reques...       1
2  public void ks8POtVPSink(String data,HttpServl...       1
3  public void ckLkoStRSink(HttpServletRequest re...       1
4  public void 9GKsg8laSink(String data,HttpServl...       1

In [14]:
java_079_babel_df.to_json('./dataset/java_079_babel_replaced.jsonl', orient='records', lines=True, force_ascii=False)

In [1]:
import pandas as pd
train_sven = pd.read_parquet("C:/hienlt/treesitter/dataset/python_dataset/train-sven.parquet")
val_sven = pd.read_parquet("C:/hienlt/treesitter/dataset/python_dataset/val-sven.parquet")

sven_full = pd.concat([train_sven, val_sven], ignore_index=True)
sven_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   func_name        803 non-null    object
 1   func_src_before  803 non-null    object
 2   func_src_after   803 non-null    object
 3   line_changes     803 non-null    object
 4   char_changes     803 non-null    object
 5   commit_link      803 non-null    object
 6   file_name        803 non-null    object
 7   vul_type         803 non-null    object
dtypes: object(8)
memory usage: 50.3+ KB

In [3]:
sven_py = sven_full[sven_full['file_name'].str.endswith('.py', na=False)]
sven_py.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 1 to 761
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   func_name        380 non-null    object
 1   func_src_before  380 non-null    object
 2   func_src_after   380 non-null    object
 3   line_changes     380 non-null    object
 4   char_changes     380 non-null    object
 5   commit_link      380 non-null    object
 6   file_name        380 non-null    object
 7   vul_type         380 non-null    object
dtypes: object(8)
memory usage: 26.7+ KB

In [5]:
sven_py.head()

,func_name,func_src_before,func_src_after,line_changes,char_changes,commit_link,file_name,vul_type
1,zmi_page_request,"def zmi_page_request(self, *args, **kwargs...","def zmi_page_request(self, *args, **kwargs...","{'deleted': [{'line_no': 26, 'char_start': 131...","{'deleted': [], 'added': [{'char_start': 1322,...",github.com/zms-publishing/zms4/commit/3f28620d...,ZMSItem.py,cwe-022
5,_inject_file_into_fs,"def _inject_file_into_fs(fs, path, contents):\...","def _inject_file_into_fs(fs, path, contents, a...","{'deleted': [{'line_no': 5, 'char_start': 212,...","{'deleted': [{'char_start': 67, 'char_end': 69...",github.com/openstack/nova/commit/2427d4a99bed3...,nova/virt/disk/api.py,cwe-022
7,cut,"def cut(self, key):\n try:\n ...","def cut(self, key):\n try:\n ...","{'deleted': [{'line_no': 3, 'char_start': 37, ...","{'deleted': [{'char_start': 66, 'char_end': 79...",github.com/latchset/custodia/commit/785fc87f38...,custodia/store/etcdstore.py,cwe-022
9,candidate_paths_for_url,"def candidate_paths_for_url(self, url):\n ...","def candidate_paths_for_url(self, url):\n ...","{'deleted': [{'line_no': 4, 'char_start': 129,...","{'deleted': [{'char_start': 145, 'char_end': 1...",github.com/evansd/whitenoise/commit/4d8a3ab1e9...,whitenoise/base.py,cwe-022
10,updateKey,"def updateKey(client):\n\t""""""Updates the conte...","def updateKey(client):\n\t""""""Updates the conte...","{'deleted': [{'line_no': 9, 'char_start': 233,...","{'deleted': [{'char_start': 233, 'char_end': 2...",github.com/Mimickal/FoxLock/commit/7c665e55698...,impl.py,cwe-022

In [8]:
processed_sven = pd.DataFrame()
for index, row in sven_py.iterrows():
    safe_code = row['func_src_after']
    safe_label = 0
    vulnerable_code = row['func_src_before']
    vulnerable_label = 1
    vul_type = row['vul_type']
    
    # Process the code as needed (e.g., remove comments, normalize, etc.)
    # For demonstration, we'll just keep the code as is.
    
    processed_sven = pd.concat([processed_sven, pd.DataFrame([{
        'code': safe_code,  
        'label': safe_label,
        'cwe': vul_type
    }])], ignore_index=True)
    processed_sven = pd.concat([processed_sven, pd.DataFrame([{
        'code': vulnerable_code,  
        'label': vulnerable_label,
        'cwe': vul_type
    }])], ignore_index=True)

processed_sven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    760 non-null    object
 1   label   760 non-null    int64
 2   cwe     760 non-null    object
dtypes: int64(1), object(2)
memory usage: 17.9+ KB

In [9]:
processed_sven.to_csv("./dataset/sven_python.csv", index=False)

In [10]:
processed_sven['cwe'].unique()

array(['cwe-022', 'cwe-078', 'cwe-079', 'cwe-089'], dtype=object)

In [18]:
import json
idx_022 = processed_sven[processed_sven['cwe'] == 'cwe-089'].index
print(f"Number of cwe-089 samples: {len(idx_022)}")
with open('./dataset/_cwe_089.json', 'w', encoding='utf-8') as f:
    f.write(json.dumps(idx_022.tolist(), ensure_ascii=False))

Number of cwe-089 samples: 408

In [21]:
processed_sven[processed_sven['cwe'] == 'cwe-022'].head()
processed_sven['func'] = processed_sven['code']
processed_sven['target'] = processed_sven['label']
processed_sven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    760 non-null    object
 1   label   760 non-null    int64
 2   cwe     760 non-null    object
 3   func    760 non-null    object
 4   target  760 non-null    int64
dtypes: int64(2), object(3)
memory usage: 29.8+ KB

In [22]:
processed_sven[processed_sven['cwe'] == 'cwe-022'].to_json('./dataset/sven_022_python.jsonl', orient='records', lines=True, force_ascii=False)
processed_sven[processed_sven['cwe'] == 'cwe-078'].to_json('./dataset/sven_078_python.jsonl', orient='records', lines=True, force_ascii=False)
processed_sven[processed_sven['cwe'] == 'cwe-079'].to_json('./dataset/sven_079_python.jsonl', orient='records', lines=True, force_ascii=False)
processed_sven[processed_sven['cwe'] == 'cwe-089'].to_json('./dataset/sven_089_python.jsonl', orient='records', lines=True, force_ascii=False)

In [1]:
import json
import pandas as pd
data_train = []
with open(r'C:/hienlt/treesitter/dataset/primevul_train_raw.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

primevul_train_df = pd.DataFrame(data_train)
primevul_train_df.info()

data_val = []
with open(r'C:/hienlt/treesitter/dataset/primevul_val_raw.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

primevul_val_df = pd.DataFrame(data_val)
primevul_val_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   idx        7889 non-null   int64
 1   project    7889 non-null   object
 2   commit_id  7889 non-null   object
 3   func       7889 non-null   object
 4   func_hash  7889 non-null   object
 5   cwe        7889 non-null   object
 6   cve        7888 non-null   object
 7   code       7889 non-null   object
 8   label      7889 non-null   int64
 9   target     7889 non-null   int64
dtypes: int64(3), object(7)
memory usage: 616.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   idx        986 non-null    int64
 1   project    986 non-null    object
 2   commit_id  986 non-null    object
 3   func       986 non-null    object
 4   func_hash  986 non-null    object
 5   cwe        986 non-null    object
 6   cve        986 non-null    object
 7   code       986 non-null    object
 8   label      986 non-null    int64
 9   target     986 non-null    int64
dtypes: int64(3), object(7)
memory usage: 77.2+ KB

In [2]:
primevul_train_df['target'] = primevul_train_df['label']
primevul_val_df['target'] = primevul_val_df['label']

In [4]:
primevul_train_df.to_json('./dataset/primevul_train_raw.jsonl', orient='records', lines=True, force_ascii=False)
primevul_val_df.to_json('./dataset/primevul_val_raw.jsonl', orient='records', lines=True, force_ascii=False)

In [3]:
ptrain = pd.read_csv("C:/hienlt/treesitter/dataset/primevul_train.csv")
primevul_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   idx        7889 non-null   int64
 1   project    7889 non-null   object
 2   commit_id  7889 non-null   object
 3   func       7889 non-null   object
 4   func_hash  7889 non-null   object
 5   cwe        7889 non-null   object
 6   cve        7888 non-null   object
 7   code       7889 non-null   object
 8   label      7889 non-null   int64
 9   target     7889 non-null   int64
dtypes: int64(3), object(7)
memory usage: 616.5+ KB

In [2]:
import pandas as pd
sven_py = pd.read_csv("C:/hienlt/treesitter/dataset/sven_python.csv")
sven_py.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    760 non-null    object
 1   label   760 non-null    int64
 2   cwe     760 non-null    object
dtypes: int64(1), object(2)
memory usage: 17.9+ KB

In [6]:
sven_py[sven_py['cwe'] == 'cwe-022'].to_csv('./dataset/sven_022_python.csv', index=False)
sven_py[sven_py['cwe'] == 'cwe-078'].to_csv('./dataset/sven_078_python.csv', index=False)
sven_py[sven_py['cwe'] == 'cwe-079'].to_csv('./dataset/sven_079_python.csv', index=False)
sven_py[sven_py['cwe'] == 'cwe-089'].to_csv('./dataset/sven_089_python.csv', index=False)

In [4]:
sven_py['func'] = sven_py['code']
sven_py['target'] = sven_py['label']
sven_py.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    760 non-null    object
 1   label   760 non-null    int64
 2   cwe     760 non-null    object
 3   func    760 non-null    object
 4   target  760 non-null    int64
dtypes: int64(2), object(3)
memory usage: 29.8+ KB

In [5]:
sven_py.to_json('./dataset/sven_full_python.jsonl', orient='records', lines=True, force_ascii=False)

In [9]:
prime_val = pd.read_csv("C:/hienlt/treesitter/dataset/primevul_train.csv")
prime_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7759 non-null   object
 4   commit_url      7887 non-null   object
 5   commit_message  5460 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       4699 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7888 non-null   object
 13  cve_desc        7888 non-null   object
 14  nvd_url         7889 non-null   object
 15  code            7889 non-null   object
 16  label           7889 non-null   int64
dtypes: int64(3), object(14)
memory usage: 1.0+ MB

In [10]:
float(len(prime_val[prime_val['target'] == 1]) / len(prime_val[prime_val['target'] == 0]))

0.9673316708229427

In [ ]:
import json
import pandas as pd
data_train = []
with open(r'C:/hienlt/treesitter/dataset/0802.train.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

primevul_train_df = pd.DataFrame(data_train)
primevul_train_df.info()

data_val = []
with open(r'C:/hienlt/treesitter/dataset/0802.val.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

primevul_val_df = pd.DataFrame(data_val)
primevul_val_df.info()


data_test = []
with open(r'C:/hienlt/treesitter/dataset/0802.test.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_test.append(record)

primevul_test_df = pd.DataFrame(data_test)
primevul_test_df.info()

In [11]:
sven_py.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    760 non-null    object
 1   label   760 non-null    int64
 2   cwe     760 non-null    object
 3   func    760 non-null    object
 4   target  760 non-null    int64
dtypes: int64(2), object(3)
memory usage: 29.8+ KB

In [14]:
from sklearn.model_selection import train_test_split

# Save original index
sven_py['original_idx'] = sven_py.index

# Separate by label
sven_py_label_0 = sven_py[sven_py['label'] == 0]
sven_py_label_1 = sven_py[sven_py['label'] == 1]

# Split label 0: 70% train, 15% val, 15% test
train_0, temp_0 = train_test_split(sven_py_label_0, test_size=0.3, random_state=42)
val_0, test_0 = train_test_split(temp_0, test_size=0.5, random_state=42)

# Split label 1: 70% train, 15% val, 15% test
train_1, temp_1 = train_test_split(sven_py_label_1, test_size=0.3, random_state=42)
val_1, test_1 = train_test_split(temp_1, test_size=0.5, random_state=42)

# Combine and shuffle
sven_train = pd.concat([train_0, train_1], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
sven_val = pd.concat([val_0, val_1], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
sven_test = pd.concat([test_0, test_1], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Train: {len(sven_train)} (label 0: {len(train_0)}, label 1: {len(train_1)})")
print(f"Val: {len(sven_val)} (label 0: {len(val_0)}, label 1: {len(val_1)})")
print(f"Test: {len(sven_test)} (label 0: {len(test_0)}, label 1: {len(test_1)})")

Train: 532 (label 0: 266, label 1: 266)
Val: 114 (label 0: 57, label 1: 57)
Test: 114 (label 0: 57, label 1: 57)

,code,label,cwe,func,target,original_idx
0,@check_document_access_permission()\ndef edit_...,0,cwe-079,@check_document_access_permission()\ndef edit_...,0,248
1,"def retrieve_videos_from_playlist(playlist_id,...",1,cwe-089,"def retrieve_videos_from_playlist(playlist_id,...",1,747
2,"@mod.route('/edit/<int:msg_id>', methods=['GET...",0,cwe-089,"@mod.route('/edit/<int:msg_id>', methods=['GET...",0,580
3,"@endpoints.route(""/ranks"")\ndef ranks():\n ...",1,cwe-089,"@endpoints.route(""/ranks"")\ndef ranks():\n ...",1,333
4,"def _get_vdisk_attributes(self, vdisk_name...",1,cwe-078,"def _get_vdisk_attributes(self, vdisk_name...",1,695

In [21]:
import json
idx_sven = sven_test['original_idx'].tolist()
print(f"Number of samples in sven_test: {len(idx_sven)}")
with open('./dataset/_testsven_test_sven_.json', 'w', encoding='utf-8') as f:
    f.write(json.dumps(idx_sven, ensure_ascii=False))

Number of samples in sven_test: 114

In [1]:
import json
import pandas as pd
data_train = []
with open(r'C:/hienlt/treesitter/dataset/SVEN/0802.train.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

sven_train_df = pd.DataFrame(data_train)
sven_train_df.info()

data_val = []
with open(r'C:/hienlt/treesitter/dataset/SVEN/0802.valid.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

sven_val_df = pd.DataFrame(data_val)
sven_val_df.info()


data_test = []
with open(r'C:/hienlt/treesitter/dataset/SVEN/0802.test.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_test.append(record)

sven_test_df = pd.DataFrame(data_test)
sven_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      486 non-null    object
 1   target    486 non-null    int64
 2   vul_type  486 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      122 non-null    object
 1   target    122 non-null    int64
 2   vul_type  122 non-null    object
dtypes: int64(1), object(2)
memory usage: 3.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      152 non-null    object
 1   target    152 non-null    int64
 2   vul_type  152 non-null    object
dtypes: int64(1), object(2)
memory usage: 3.7+ KB

In [3]:
sven_train_df['code'] = sven_train_df['func']
sven_train_df['label'] = sven_train_df['target']
sven_val_df['code'] = sven_val_df['func']
sven_val_df['label'] = sven_val_df['target']
sven_test_df['code'] = sven_test_df['func']
sven_test_df['label'] = sven_test_df['target']
sven_train_df.to_csv("./dataset/SVEN/sven_train.csv", index=False)
sven_val_df.to_csv("./dataset/SVEN/sven_val.csv", index=False)
sven_test_df.to_csv("./dataset/SVEN/sven_test.csv", index=False)

In [1]:
import pandas as pd
sven_test_df = pd.read_csv("./dataset/SVEN/sven_test.csv")
sven_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      152 non-null    object
 1   target    152 non-null    int64
 2   vul_type  152 non-null    object
 3   code      152 non-null    object
 4   label     152 non-null    int64
dtypes: int64(2), object(3)
memory usage: 6.1+ KB

In [2]:
sven_test_df['language'] = "python"
sven_test_df.to_csv("./dataset/SVEN/sven_test.csv", index=False)
sven_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      152 non-null    object
 1   target    152 non-null    int64
 2   vul_type  152 non-null    object
 3   code      152 non-null    object
 4   label     152 non-null    int64
 5   language  152 non-null    object
dtypes: int64(2), object(4)
memory usage: 7.2+ KB

In [5]:
prime_vul_test = pd.read_csv("C:/hienlt/treesitter/dataset/primevul_test.csv")
prime_vul_test['language'] = "c/cpp"

In [7]:
prime_vul_test.to_csv("./dataset/primevul_test.csv", index=False)

In [1]:
import pandas as pd
mvd_df = pd.read_csv("C:/hienlt/treesitter/dataset/MVD/CVEALL.csv")
mvd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225994 entries, 0 to 225993
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   processed_func   225992 non-null  object
 1   target           225994 non-null  int64
 2   flaw_line        11764 non-null   object
 3   flaw_line_index  225994 non-null  int64
 4   commit_url       225994 non-null  object
 5   language         225994 non-null  object
dtypes: int64(2), object(4)
memory usage: 10.3+ MB

In [8]:
mvd_df['language'].unique()

array(['Python', 'TypeScript', 'Java', 'CS', 'CCPP', 'JavaScript'],
      dtype=object)

In [4]:
mvd_df[mvd_df['language'] == 'Python'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 14476 entries, 0 to 204838
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   processed_func   14476 non-null  object
 1   target           14476 non-null  int64
 2   flaw_line        830 non-null    object
 3   flaw_line_index  14476 non-null  int64
 4   commit_url       14476 non-null  object
 5   language         14476 non-null  object
dtypes: int64(2), object(4)
memory usage: 791.7+ KB

In [6]:
mvd_df['code'] = mvd_df['processed_func']
mvd_df['label'] = mvd_df['target']
mvd_df['func'] = mvd_df['processed_func']
mvd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225994 entries, 0 to 225993
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   processed_func   225992 non-null  object
 1   target           225994 non-null  int64
 2   flaw_line        11764 non-null   object
 3   flaw_line_index  225994 non-null  int64
 4   commit_url       225994 non-null  object
 5   language         225994 non-null  object
 6   code             225992 non-null  object
 7   label            225994 non-null  int64
 8   func             225992 non-null  object
dtypes: int64(3), object(6)
memory usage: 15.5+ MB

In [7]:
mvd_df.to_csv("./dataset/MVD/mvd_dataset_all.csv", index=False)

In [16]:
mvd_df[mvd_df['language'] == 'JavaScript'].to_csv("./dataset/MVD/mvd_javascript.csv", index=False)

In [11]:
mvd_df['language'].unique()

array(['Python', 'TypeScript', 'Java', 'CS', 'CCPP', 'JavaScript'],
      dtype=object)

In [2]:
import pandas as pd
sven_test_df = pd.read_csv("./dataset/SVEN/sven_test.csv")
sven_val_df = pd.read_csv("./dataset/SVEN/sven_val.csv")
sven_train_df = pd.read_csv("./dataset/SVEN/sven_train.csv")
sven_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      152 non-null    object
 1   target    152 non-null    int64
 2   vul_type  152 non-null    object
 3   code      152 non-null    object
 4   label     152 non-null    int64
 5   language  152 non-null    object
dtypes: int64(2), object(4)
memory usage: 7.2+ KB

In [2]:
sven_test_df['language'] = "Python"
sven_val_df['language'] = "Python"
sven_train_df['language'] = "Python"
sven_test_df.to_csv("./dataset/SVEN/sven_test.csv", index=False)
sven_val_df.to_csv("./dataset/SVEN/sven_val.csv", index=False)
sven_train_df.to_csv("./dataset/SVEN/sven_train.csv", index=False)

In [3]:
primevul_train_df = pd.read_csv("./dataset/primevul_train.csv")
primevul_val_df = pd.read_csv("./dataset/primevul_val.csv")
primevul_test_df = pd.read_csv("./dataset/primevul_test.csv")
primevul_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7759 non-null   object
 4   commit_url      7887 non-null   object
 5   commit_message  5460 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       4699 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7888 non-null   object
 13  cve_desc        7888 non-null   object
 14  nvd_url         7889 non-null   object
 15  code            7889 non-null   object
 16  label           7889 non-null   int64
 17  language        7889 non-null   object
dtypes: int64(3), object(15)
memory usage: 1.1+ MB

In [4]:
primevul_train_df['language'] = "CCPP"
primevul_val_df['language'] = "CCPP"
primevul_test_df['language'] = "CCPP"

primevul_train_df.to_csv("./dataset/primevul_train.csv", index=False)
primevul_val_df.to_csv("./dataset/primevul_val.csv", index=False)
primevul_test_df.to_csv("./dataset/primevul_test.csv", index=False)

In [5]:
len(primevul_test_df['code'].unique())

987

In [1]:
import pandas as pd
primevule_test = pd.read_csv("./dataset/primevul_test.csv")
primevule_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             987 non-null    int64
 1   project         987 non-null    object
 2   commit_id       987 non-null    object
 3   project_url     965 non-null    object
 4   commit_url      986 non-null    object
 5   commit_message  660 non-null    object
 6   target          987 non-null    int64
 7   func            987 non-null    object
 8   func_hash       987 non-null    object
 9   file_name       583 non-null    object
 10  file_hash       583 non-null    float64
 11  cwe             987 non-null    object
 12  cve             986 non-null    object
 13  cve_desc        986 non-null    object
 14  nvd_url         987 non-null    object
 15  code            987 non-null    object
 16  label           987 non-null    int64
 17  language        987 non-null    object
dtypes: float64(1), int64(3), object(14)
memory usage: 138.9+ KB

In [1]:
import pandas as pd
import json

In [2]:
primevule_test.to_json('./dataset/primevul_test_raw.jsonl', orient='records', lines=True, force_ascii=False)

In [3]:
sven_train = pd.read_csv("./dataset/SVEN/sven_train.csv")
sven_val = pd.read_csv("./dataset/SVEN/sven_val.csv")  
sven_test = pd.read_csv("./dataset/SVEN/sven_test.csv")
sven_train.to_json('./dataset/SVEN/sven_train.jsonl', orient='records', lines=True, force_ascii=False)
sven_val.to_json('./dataset/SVEN/sven_val.jsonl', orient='records', lines=True, force_ascii=False)
sven_test.to_json('./dataset/SVEN/sven_test.jsonl', orient='records', lines=True, force_ascii=False)

In [4]:
sven_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      486 non-null    object
 1   target    486 non-null    int64
 2   vul_type  486 non-null    object
 3   code      486 non-null    object
 4   label     486 non-null    int64
 5   language  486 non-null    object
dtypes: int64(2), object(4)
memory usage: 22.9+ KB

In [6]:
sven_train = pd.read_csv("./dataset/SVEN/sven_train.csv")
sven_val = pd.read_csv("./dataset/SVEN/sven_val.csv")
sven_test = pd.read_csv("./dataset/SVEN/sven_test.csv")
sven_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      486 non-null    object
 1   target    486 non-null    int64
 2   vul_type  486 non-null    object
 3   code      486 non-null    object
 4   label     486 non-null    int64
 5   language  486 non-null    object
dtypes: int64(2), object(4)
memory usage: 22.9+ KB

In [8]:
moe_train_sven = pd.DataFrame({
    'code': sven_train['code'],
    'vuln': sven_train['label'],
    'cwe': 2
})
moe_val_sven = pd.DataFrame({
    'code': sven_val['code'],
    'vuln': sven_val['label'],
    'cwe': 2
})
moe_test_sven = pd.DataFrame({
    'code': sven_test['code'],
    'vuln': sven_test['label'],
    'cwe': 2
})
moe_train_sven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    486 non-null    object
 1   vuln    486 non-null    int64
 2   cwe     486 non-null    int64
dtypes: int64(2), object(1)
memory usage: 11.5+ KB

In [9]:
moe_train_sven.to_json('./dataset/SVEN/sven_train_moe.jsonl', orient='records', lines=True, force_ascii=False)
moe_val_sven.to_json('./dataset/SVEN/sven_val_moe.jsonl', orient='records', lines=True, force_ascii=False)
moe_test_sven.to_json('./dataset/SVEN/sven_test_moe.jsonl', orient='records', lines=True, force_ascii=False)

In [10]:
data_train = []
with open(r'C:/hienlt/treesitter/dataset/Primevul/primevul_train_moe.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_train.append(record)

primevul_train_moe = pd.DataFrame(data_train)
primevul_train_moe.info()

data_val = []
with open(r'C:/hienlt/treesitter/dataset/Primevul/primevul_val_moe.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_val.append(record)

primevul_val_moe = pd.DataFrame(data_val)
primevul_val_moe.info()


data_test = []
with open(r'C:/hienlt/treesitter/dataset/Primevul/primevul_test_moe.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_test.append(record)

primevul_test_moe = pd.DataFrame(data_test)
primevul_test_moe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    7889 non-null   object
 1   vuln    7889 non-null   int64
 2   cwe     7889 non-null   int64
dtypes: int64(2), object(1)
memory usage: 185.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    986 non-null    object
 1   vuln    986 non-null    int64
 2   cwe     986 non-null    int64
dtypes: int64(2), object(1)
memory usage: 23.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    987 non-null    object
 1   vuln    987 non-null    int64
 2   cwe     987 non-null    int64
dtypes: int64(2), object(1)
memory usage: 23.3+ KB

In [11]:
moe_train = pd.concat([primevul_train_moe, moe_train_sven], ignore_index=True)
moe_val = pd.concat([primevul_val_moe, moe_val_sven], ignore_index=True)
moe_test = pd.concat([primevul_test_moe, moe_test_sven], ignore_index=True)
moe_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8375 entries, 0 to 8374
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    8375 non-null   object
 1   vuln    8375 non-null   int64
 2   cwe     8375 non-null   int64
dtypes: int64(2), object(1)
memory usage: 196.4+ KB

In [12]:
moe_train.to_json('./dataset/MoE/primevul_sven_train_moe.jsonl', orient='records', lines=True, force_ascii=False)
moe_val.to_json('./dataset/MoE/primevul_sven_val_moe.jsonl', orient='records', lines=True, force_ascii=False)
moe_test.to_json('./dataset/MoE/primevul_sven_test_moe.jsonl', orient='records', lines=True, force_ascii=False)

In [2]:
data_predictions = []
with open(r'C:/hienlt/treesitter/dataset/MoE_predictions/test_predictions_20260310_114329.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        data_predictions.append(record)

predictions_moe = pd.DataFrame(data_predictions)
predictions_moe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        1139 non-null   int64
 1   predicted_label  1139 non-null   int64
 2   real_label       1139 non-null   int64
 3   probability      1139 non-null   float64
 4   cwe_id           1139 non-null   int64
 5   is_correct       1139 non-null   bool
dtypes: bool(1), float64(1), int64(4)
memory usage: 45.7 KB

In [5]:
predictions_moe.head(25)

    sample_id  predicted_label  real_label  probability  cwe_id  is_correct
0           0                0           0     0.018305       1        True
1           1                1           1     0.980783       1        True
2           2                1           1     0.933354       1        True
3           3                1           1     0.980610       1        True
4           4                1           1     0.982879       1        True
5           5                1           1     0.967589       1        True
6           6                1           1     0.582470       1        True
7           7                1           1     0.975098       1        True
8           8                0           0     0.057411       1        True
9           9                0           0     0.029066       1        True
10         10                0           0     0.052916       1        True
11         11                0           0     0.053210       1        True
12         12                1           0     0.800249       1       False
13         13                1           1     0.979927       1        True
14         14                0           0     0.025918       1        True
15         15                1           1     0.981926       1        True
16         16                1           1     0.508733       1        True
17         17                0           0     0.193927       1        True
18         18                1           1     0.991711       1        True
19         19                0           0     0.125041       1        True
20         20                0           0     0.030418       1        True
21         21                1           1     0.991961       1        True
22         22                0           0     0.026786       1        True
23         23                1           1     0.984956       1        True
24         24                1           1     0.980627       1        True

In [6]:
predictions_moe_false = predictions_moe[predictions_moe['is_correct'] == False]
predictions_moe_false.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69 entries, 12 to 1132
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        69 non-null     int64
 1   predicted_label  69 non-null     int64
 2   real_label       69 non-null     int64
 3   probability      69 non-null     float64
 4   cwe_id           69 non-null     int64
 5   is_correct       69 non-null     bool
dtypes: bool(1), float64(1), int64(4)
memory usage: 3.3 KB

In [7]:
predictions_moe_false_cpp = predictions_moe_false[predictions_moe_false['cwe_id'] == 1]
predictions_moe_false_python = predictions_moe_false[predictions_moe_false['cwe_id'] == 2]
predictions_moe_false_cpp.info()
predictions_moe_false_python.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 12 to 967
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        32 non-null     int64
 1   predicted_label  32 non-null     int64
 2   real_label       32 non-null     int64
 3   probability      32 non-null     float64
 4   cwe_id           32 non-null     int64
 5   is_correct       32 non-null     bool
dtypes: bool(1), float64(1), int64(4)
memory usage: 1.5 KB
<class 'pandas.core.frame.DataFrame'>
Index: 37 entries, 990 to 1132
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        37 non-null     int64
 1   predicted_label  37 non-null     int64
 2   real_label       37 non-null     int64
 3   probability      37 non-null     float64
 4   cwe_id           37 non-null     int64
 5   is_correct       37 non-null     bool
dtypes: bool(1), float64(1), int64(4)
memory usage: 1.8 KB

In [8]:
predictions_moe_false_cpp['sample_id'].tolist().to_json('./dataset/MoE_predictions/moe_false_cpp.json', orient='records', lines=True, force_ascii=False)
predictions_moe_false_python['sample_id'].tolist().to_json('./dataset/MoE_predictions/moe_false_python.json', orient='records', lines=True, force_ascii=False)

AttributeError: 'list' object has no attribute 'to_json'

In [1]:
import json
import pandas as pd
moe_test = []
with open(r'C:/hienlt/treesitter/dataset/MoE/primevul_sven_test_moe.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        moe_test.append(record)

moe_test_df = pd.DataFrame(moe_test)
moe_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    1139 non-null   object
 1   vuln    1139 non-null   int64
 2   cwe     1139 non-null   int64
dtypes: int64(2), object(1)
memory usage: 26.8+ KB

In [3]:
# Ensure both DataFrames have an 'idx' column based on their row index
if 'idx' not in predictions_moe.columns:
    predictions_moe['idx'] = predictions_moe.index

if 'idx' not in moe_test_df.columns:
    moe_test_df['idx'] = moe_test_df.index

# Join on idx
joined_df = predictions_moe.merge(moe_test_df, on='idx', how='inner')

joined_df.info()
# joined_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        1139 non-null   int64
 1   predicted_label  1139 non-null   int64
 2   real_label       1139 non-null   int64
 3   probability      1139 non-null   float64
 4   cwe_id           1139 non-null   int64
 5   is_correct       1139 non-null   bool
 6   idx              1139 non-null   int64
 7   code             1139 non-null   object
 8   vuln             1139 non-null   int64
 9   cwe              1139 non-null   int64
dtypes: bool(1), float64(1), int64(7), object(1)
memory usage: 81.3+ KB

In [8]:
joined_df.head()
moe_cpp_predictions = joined_df[joined_df['cwe_id'] == 1]
moe_python_predictions = joined_df[joined_df['cwe_id'] == 2]
moe_cpp_predictions.info()
moe_python_predictions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 987 entries, 0 to 986
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        987 non-null    int64
 1   predicted_label  987 non-null    int64
 2   real_label       987 non-null    int64
 3   probability      987 non-null    float64
 4   cwe_id           987 non-null    int64
 5   is_correct       987 non-null    bool
 6   idx              987 non-null    int64
 7   code             987 non-null    object
 8   vuln             987 non-null    int64
 9   cwe              987 non-null    int64
dtypes: bool(1), float64(1), int64(7), object(1)
memory usage: 78.1+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 987 to 1138
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        152 non-null    int64
 1   predicted_label  152 non-null    int64
 2   real_label       152 non-null    int64
 3   probability      152 non-null    float64
 4   cwe_id           152 non-null    int64
 5   is_correct       152 non-null    bool
 6   idx              152 non-null    int64
 7   code             152 non-null    object
 8   vuln             152 non-null    int64
 9   cwe              152 non-null    int64
dtypes: bool(1), float64(1), int64(7), object(1)
memory usage: 12.0+ KB

In [7]:
mvd_test_cpp = pd.read_csv("C:/hienlt/treesitter/dataset/MoE_predictions/c_based_test_predictions.csv")  
mvd_test_python = pd.read_csv("C:/hienlt/treesitter/dataset/MoE_predictions/python_based_test_predictions.csv")
mvd_test_cpp.info()
mvd_test_python.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        987 non-null    object
 1   true_label  987 non-null    int64
 2   pred_label  987 non-null    int64
 3   language    987 non-null    object
dtypes: int64(2), object(2)
memory usage: 31.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        152 non-null    object
 1   true_label  152 non-null    int64
 2   pred_label  152 non-null    int64
 3   language    152 non-null    object
dtypes: int64(2), object(2)
memory usage: 4.9+ KB

In [9]:
gathered_cpp = moe_cpp_predictions.merge(mvd_test_cpp, on='code', how='outer', indicator=True)
gathered_python = moe_python_predictions.merge(mvd_test_python, on='code', how='outer', indicator=True)
gathered_cpp.info()
gathered_python.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        987 non-null    int64
 1   predicted_label  987 non-null    int64
 2   real_label       987 non-null    int64
 3   probability      987 non-null    float64
 4   cwe_id           987 non-null    int64
 5   is_correct       987 non-null    bool
 6   idx              987 non-null    int64
 7   code             987 non-null    object
 8   vuln             987 non-null    int64
 9   cwe              987 non-null    int64
 10  true_label       987 non-null    int64
 11  pred_label       987 non-null    int64
 12  language         987 non-null    object
 13  _merge           987 non-null    category
dtypes: bool(1), category(1), float64(1), int64(9), object(2)
memory usage: 94.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        152 non-null    int64
 1   predicted_label  152 non-null    int64
 2   real_label       152 non-null    int64
 3   probability      152 non-null    float64
 4   cwe_id           152 non-null    int64
 5   is_correct       152 non-null    bool
 6   idx              152 non-null    int64
 7   code             152 non-null    object
 8   vuln             152 non-null    int64
 9   cwe              152 non-null    int64
 10  true_label       152 non-null    int64
 11  pred_label       152 non-null    int64
 12  language         152 non-null    object
 13  _merge           152 non-null    category
dtypes: bool(1), category(1), float64(1), int64(9), object(2)
memory usage: 14.8+ KB

In [14]:
gathered_python.head()

,sample_id,predicted_label,real_label,probability,cwe_id,is_correct,idx,code,vuln,cwe,true_label,pred_label,language,_merge
0,1014,0,0,0.142713,2,True,1014,"\tdef add_input(self, data):\n\t\tconnection =...",0,2,0,0,SVEN,both
1,1053,1,1,0.958722,2,True,1053,"\tdef add_input(self, data):\n\t\tconnection =...",1,2,1,1,SVEN,both
2,1097,0,0,0.076436,2,True,1097,def view_grocery_list():\n ...,0,2,0,0,SVEN,both
3,990,1,0,0.630931,2,False,990,@property\n async def html_content(self...,0,2,0,1,SVEN,both
4,1028,1,0,0.311372,2,False,1028,@staticmethod\n def _add_to_db(user):\n...,0,2,0,1,SVEN,both

In [15]:
gathered_cpp.head()

,sample_id,predicted_label,real_label,probability,cwe_id,is_correct,idx,code,vuln,cwe,true_label,pred_label,language,_merge
0,310,1,1,0.990742,1,True,310,"\tSilenceMessage(const std::string& mask, cons...",1,1,1,1,Primevul,both
1,657,1,1,0.971770,1,True,657,"\tint lazy_bdecode(char const* start, char con...",1,1,1,1,Primevul,both
2,833,1,1,0.940845,1,True,833,"\nstatic int ssl_verify_server_cert(Vio *vio, ...",1,1,1,1,Primevul,both
3,793,1,0,0.924980,1,False,793,MacroExpander(const Solid::Device &device)...,0,1,0,0,Primevul,both
4,652,1,1,0.705381,1,True,652,bool Greeter::start() {\n // check ...,1,1,1,0,Primevul,both

In [16]:
gathered_cpp.drop(columns=['idx', 'real_label', 'vuln', 'cwe_id'], inplace=True)
gathered_python.drop(columns=['idx', 'real_label', 'vuln', 'cwe_id'], inplace=True)
gathered_cpp.info()
gathered_python.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        987 non-null    int64
 1   predicted_label  987 non-null    int64
 2   probability      987 non-null    float64
 3   is_correct       987 non-null    bool
 4   code             987 non-null    object
 5   cwe              987 non-null    int64
 6   true_label       987 non-null    int64
 7   pred_label       987 non-null    int64
 8   language         987 non-null    object
 9   _merge           987 non-null    category
dtypes: bool(1), category(1), float64(1), int64(5), object(2)
memory usage: 63.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        152 non-null    int64
 1   predicted_label  152 non-null    int64
 2   probability      152 non-null    float64
 3   is_correct       152 non-null    bool
 4   code             152 non-null    object
 5   cwe              152 non-null    int64
 6   true_label       152 non-null    int64
 7   pred_label       152 non-null    int64
 8   language         152 non-null    object
 9   _merge           152 non-null    category
dtypes: bool(1), category(1), float64(1), int64(5), object(2)
memory usage: 10.1+ KB

In [19]:
gathered_cpp['is_correct(mvd)'] = gathered_cpp['pred_label'] == gathered_cpp['true_label']
gathered_python['is_correct(mvd)'] = gathered_python['pred_label'] == gathered_python['true_label']
gathered_cpp.head()

,sample_id,predicted_label,probability,is_correct,code,cwe,true_label,pred_label,language,_merge,is_correct(mvd)
0,310,1,0.990742,True,"\tSilenceMessage(const std::string& mask, cons...",1,1,1,Primevul,both,True
1,657,1,0.971770,True,"\tint lazy_bdecode(char const* start, char con...",1,1,1,Primevul,both,True
2,833,1,0.940845,True,"\nstatic int ssl_verify_server_cert(Vio *vio, ...",1,1,1,Primevul,both,True
3,793,1,0.924980,False,MacroExpander(const Solid::Device &device)...,1,0,0,Primevul,both,True
4,652,1,0.705381,True,bool Greeter::start() {\n // check ...,1,1,0,Primevul,both,False

In [23]:
gathered_cpp_both_true = gathered_cpp[(gathered_cpp['is_correct(mvd)'] == True) & (gathered_cpp['is_correct'] == True)]
gathered_cpp_both_true.info()
gathered_cpp_wrong_predicted = gathered_cpp.loc[
    ~gathered_cpp.index.isin(gathered_cpp_both_true.index)
]
# optional:
# gathered_cpp_wrong_predicted = gathered_cpp_wrong_predicted.reset_index(drop=True)
gathered_cpp_wrong_predicted.head()

<class 'pandas.core.frame.DataFrame'>
Index: 933 entries, 0 to 986
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        933 non-null    int64
 1   predicted_label  933 non-null    int64
 2   probability      933 non-null    float64
 3   is_correct       933 non-null    bool
 4   code             933 non-null    object
 5   cwe              933 non-null    int64
 6   true_label       933 non-null    int64
 7   pred_label       933 non-null    int64
 8   language         933 non-null    object
 9   _merge           933 non-null    category
 10  is_correct(mvd)  933 non-null    bool
dtypes: bool(2), category(1), float64(1), int64(5), object(2)
memory usage: 68.5+ KB

,sample_id,predicted_label,probability,is_correct,code,cwe,true_label,pred_label,language,_merge,is_correct(mvd)
3,793,1,0.924980,False,MacroExpander(const Solid::Device &device)...,1,0,0,Primevul,both,True
4,652,1,0.705381,True,bool Greeter::start() {\n // check ...,1,1,0,Primevul,both,False
69,744,1,0.775460,False,ps_parser_skip_PS_token( PS_Parser parser )...,1,0,1,Primevul,both,False
107,474,1,0.537007,True,void UrlParser::parse(char ch)\n {\n swi...,1,1,0,Primevul,both,False
149,306,0,0.177516,True,BufFilePushCompressed (BufFilePtr f)\n{\n i...,1,0,1,Primevul,both,False

In [24]:
gathered_python_both_true = gathered_python[(gathered_python['is_correct(mvd)'] == True) & (gathered_python['is_correct'] == True)]
gathered_python_both_true.info()
gathered_python_wrong_predicted = gathered_python.loc[
    ~gathered_python.index.isin(gathered_python_both_true.index)
]
# optional:
# gathered_python_wrong_predicted = gathered_python_wrong_predicted.reset_index(drop=True)
gathered_python_wrong_predicted.head()

<class 'pandas.core.frame.DataFrame'>
Index: 102 entries, 0 to 151
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        102 non-null    int64
 1   predicted_label  102 non-null    int64
 2   probability      102 non-null    float64
 3   is_correct       102 non-null    bool
 4   code             102 non-null    object
 5   cwe              102 non-null    int64
 6   true_label       102 non-null    int64
 7   pred_label       102 non-null    int64
 8   language         102 non-null    object
 9   _merge           102 non-null    category
 10  is_correct(mvd)  102 non-null    bool
dtypes: bool(2), category(1), float64(1), int64(5), object(2)
memory usage: 7.6+ KB

,sample_id,predicted_label,probability,is_correct,code,cwe,true_label,pred_label,language,_merge,is_correct(mvd)
3,990,1,0.630931,False,@property\n async def html_content(self...,2,0,1,SVEN,both,False
4,1028,1,0.311372,False,@staticmethod\n def _add_to_db(user):\n...,2,0,1,SVEN,both,False
5,1026,0,0.180597,False,@staticmethod\n def compare_and_update(...,2,1,0,SVEN,both,False
6,1001,1,0.593876,False,@staticmethod\n def estimate_size(task_...,2,0,1,SVEN,both,False
7,1121,1,0.404185,True,"def __init__(self, *args, **kwargs):\n ...",2,1,0,SVEN,both,False

In [27]:
gather_wrong_predicted = pd.concat([gathered_cpp_wrong_predicted, gathered_python_wrong_predicted], ignore_index=True)
gather_wrong_predicted.to_csv("./dataset/MoE_predictions/gather_wrong_predicted.csv", index=False)

In [9]:
cpp_false_ids = predictions_moe_false_cpp['sample_id'].tolist()
python_false_ids = predictions_moe_false_python['sample_id'].tolist()
# moe_test_df['predicted_wrong'] = moe_test_df['idx'].apply(lambda x: 1 if x in cpp_false_ids or x in python_false_ids else 0)
# sample_id maps to row index in moe_test_df
moe_test_df['idx'] = moe_test_df.index

false_ids = set(cpp_false_ids) | set(python_false_ids)
moe_test_df['predicted_wrong'] = moe_test_df['idx'].isin(false_ids).astype(int)

moe_test_wrong = moe_test_df[moe_test_df['predicted_wrong'] == 1]
moe_test_wrong.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69 entries, 12 to 1132
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   code             69 non-null     object
 1   vuln             69 non-null     int64
 2   cwe              69 non-null     int64
 3   idx              69 non-null     int64
 4   predicted_wrong  69 non-null     int64
dtypes: int64(4), object(1)
memory usage: 3.2+ KB

In [10]:
moe_test_wrong_cpp = moe_test_wrong[moe_test_wrong['cwe'] == 1]
moe_test_wrong_python = moe_test_wrong[moe_test_wrong['cwe'] == 2]
moe_test_wrong_cpp.info()
moe_test_wrong_python.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 12 to 967
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   code             32 non-null     object
 1   vuln             32 non-null     int64
 2   cwe              32 non-null     int64
 3   idx              32 non-null     int64
 4   predicted_wrong  32 non-null     int64
dtypes: int64(4), object(1)
memory usage: 1.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 37 entries, 990 to 1132
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   code             37 non-null     object
 1   vuln             37 non-null     int64
 2   cwe              37 non-null     int64
 3   idx              37 non-null     int64
 4   predicted_wrong  37 non-null     int64
dtypes: int64(4), object(1)
memory usage: 1.7+ KB

In [11]:
moe_test_wrong_cpp.head(32)

,code,vuln,cwe,idx,predicted_wrong
12,XvImageFormatValues * XvMCListSubpictureTypes ...,0,1,12,1
27,"XLookupColor (\n\tregister Display *dpy,\n ...",1,1,27,1
46,ProcXSendExtensionEvent(ClientPtr client)\n{\n...,0,1,46,1
64,method_invocation_get_uid (GDBusMethodInvocati...,1,1,64,1
81,"add_range(fz_context *ctx, pdf_cmap *cmap, uns...",1,1,81,1
188,"get_futex_key(u32 __user *uaddr, int fshared, ...",1,1,188,1
338,WebGLObject::WebGLObject(WebGLRenderingContext...,1,1,338,1
339,"xps_true_callback_glyph_name(gs_font *pfont, g...",0,1,339,1
342,poppler_page_get_annot_mapping (PopplerPage *p...,0,1,342,1
355,static int vqa_decode_frame(AVCodecContext *av...,0,1,355,1
378,"int tls1_cbc_remove_padding(const SSL* s,\n\t\...",1,1,378,1
394,"void FlateStream::readSome() {\n int code1, c...",0,1,394,1
424,static void set_k_acc(struct SYMBOL *s)\n{\n\t...,1,1,424,1
426,"gs_setdevice_no_erase(gs_gstate * pgs, gx_devi...",0,1,426,1
477,int ssl3_send_newsession_ticket(SSL *s)\n{\n ...,0,1,477,1
496,user_register (User *user)\n{\n g_autop...,0,1,496,1
508,"do_ed_script (char const *inname, char const *...",1,1,508,1
542,static int samldb_prim_group_change(struct sam...,0,1,542,1
609,"user_update_from_pwent (User *user,\n...",0,1,609,1
611,static void ssl3_take_mac(SSL *s)\n {\n...,1,1,611,1
626,"int main(int argc, char *argv[])\n{\n\tint opt...",0,1,626,1
627,static void dtls1_clear_queues(SSL *s)\n{\n ...,0,1,627,1
744,ps_parser_skip_PS_token( PS_Parser parser )...,0,1,744,1
777,void DTLS_RECORD_LAYER_clear(RECORD_LAYER *rl)...,0,1,777,1
793,MacroExpander(const Solid::Device &device)...,0,1,793,1
848,"static int nfs_iterate(struct file *file, stru...",0,1,848,1
895,void RemoveActionCallback(const ActionCallback...,1,1,895,1
923,"int X509_aux_print(BIO *out, X509 *x, int inde...",1,1,923,1
942,"static int decode_format80(GetByteContext *gb,...",0,1,942,1
944,static void reds_start_auth_sasl(RedLinkInfo *...,0,1,944,1
953,"static int h2c_decode_headers(struct h2c *h2c,...",1,1,953,1
967,"static void md5_transform(u32 *hash, u32 const...",1,1,967,1

In [14]:
with open('./dataset/MoE_predictions/moe_wrong_python_samples.jsonl', 'w', encoding='utf-8') as f:
    for code, vuln in zip(moe_test_wrong_python['code'], moe_test_wrong_python['vuln']):
        f.write(json.dumps({'code': code, 'vuln': vuln}, ensure_ascii=False) + '\n')

In [2]:
moe_wrong_cpp = []
with open(r'C:/hienlt/treesitter/dataset/MoE_predictions/moe_wrong_cpp_samples.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        moe_wrong_cpp.append(record)

moe_wrong_cpp_df = pd.DataFrame(moe_wrong_cpp)
moe_wrong_cpp_df.info()

moe_wrong_python = []
with open(r'C:/hienlt/treesitter/dataset/MoE_predictions/moe_wrong_python_samples.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        moe_wrong_python.append(record)

moe_wrong_python_df = pd.DataFrame(moe_wrong_python)
moe_wrong_python_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    32 non-null     object
 1   vuln    32 non-null     int64
dtypes: int64(1), object(1)
memory usage: 640.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    37 non-null     object
 1   vuln    37 non-null     int64
dtypes: int64(1), object(1)
memory usage: 720.0+ bytes

In [9]:
mvd_cpp_test = pd.read_csv("C:/hienlt/treesitter/dataset/MoE_predictions/c_based_test_predictions.csv")
# mvd_cpp_test.info()
mvd_cpp_test_wrong = mvd_cpp_test[mvd_cpp_test['true_label'] != mvd_cpp_test['pred_label']]
mvd_cpp_test_wrong.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37 entries, 2 to 983
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        37 non-null     object
 1   true_label  37 non-null     int64
 2   pred_label  37 non-null     int64
 3   language    37 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.4+ KB

In [10]:
mvd_python_test = pd.read_csv("C:/hienlt/treesitter/dataset/MoE_predictions/python_based_test_predictions.csv")
mvd_python_test_wrong = mvd_python_test[mvd_python_test['true_label'] != mvd_python_test['pred_label']]
mvd_python_test_wrong.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 3 to 145
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        40 non-null     object
 1   true_label  40 non-null     int64
 2   pred_label  40 non-null     int64
 3   language    40 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.6+ KB

In [11]:
merged_python_wrong = pd.merge(moe_wrong_python_df, mvd_python_test_wrong, on='code', how='inner')
merged_python_wrong.info()
merged_python_wrong.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        27 non-null     object
 1   vuln        27 non-null     int64
 2   true_label  27 non-null     int64
 3   pred_label  27 non-null     int64
 4   language    27 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.2+ KB

,code,vuln,true_label,pred_label,language
0,@property\n async def html_content(self...,0,0,1,SVEN
1,"def get_context_data(self, *args, **kwargs...",0,0,1,SVEN
2,"def get_queryset(self, **kwargs):\n ...",1,1,0,SVEN
3,@staticmethod\n def estimate_size(task_...,0,0,1,SVEN
4,async def save(request):\n # TODO csrf\n ...,0,0,1,SVEN

In [12]:
merged_cpp_wrong = pd.merge(moe_wrong_cpp_df, mvd_cpp_test_wrong, on='code', how='inner')
merged_cpp_wrong.info()
merged_cpp_wrong.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        15 non-null     object
 1   vuln        15 non-null     int64
 2   true_label  15 non-null     int64
 3   pred_label  15 non-null     int64
 4   language    15 non-null     object
dtypes: int64(3), object(2)
memory usage: 728.0+ bytes

,code,vuln,true_label,pred_label,language
0,ProcXSendExtensionEvent(ClientPtr client)\n{\n...,0,0,1,Primevul
1,method_invocation_get_uid (GDBusMethodInvocati...,1,1,0,Primevul
2,WebGLObject::WebGLObject(WebGLRenderingContext...,1,1,0,Primevul
3,"int tls1_cbc_remove_padding(const SSL* s,\n\t\...",1,1,0,Primevul
4,static void set_k_acc(struct SYMBOL *s)\n{\n\t...,1,1,0,Primevul

In [13]:
gathered_wrong = pd.concat([merged_python_wrong, merged_cpp_wrong], ignore_index=True)
gathered_wrong.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        42 non-null     object
 1   vuln        42 non-null     int64
 2   true_label  42 non-null     int64
 3   pred_label  42 non-null     int64
 4   language    42 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.8+ KB

In [14]:
gathered_wrong.to_csv("./dataset/MoE_predictions/gathered_wrong_samples.csv", index=False)

In [2]:
sven_train = pd.read_csv("./dataset/SVEN/sven_train.csv")
sven_val = pd.read_csv("./dataset/SVEN/sven_val.csv")   
sven_test = pd.read_csv("./dataset/SVEN/sven_test.csv")
sven_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      486 non-null    object
 1   target    486 non-null    int64
 2   vul_type  486 non-null    object
 3   code      486 non-null    object
 4   label     486 non-null    int64
 5   language  486 non-null    object
dtypes: int64(2), object(4)
memory usage: 22.9+ KB

In [22]:
primevul_train = pd.read_csv("./dataset/primevul_train.csv")
primevul_val = pd.read_csv("./dataset/primevul_val.csv")
primevul_test = pd.read_csv("./dataset/primevul_test.csv")
primevul_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7759 non-null   object
 4   commit_url      7887 non-null   object
 5   commit_message  5460 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       4699 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7888 non-null   object
 13  cve_desc        7888 non-null   object
 14  nvd_url         7889 non-null   object
 15  code            7889 non-null   object
 16  label           7889 non-null   int64
 17  language        7889 non-null   object
dtypes: int64(3), object(15)
memory usage: 1.1+ MB

In [ ]:
sven_train['vul_type'].unique()

array(['cwe-079', 'cwe-089', 'cwe-078', 'cwe-022'], dtype=object)

In [10]:
for index, row in sven_test.iterrows():
    if row['vul_type'] == 'cwe-022':
        sven_test.at[index, 'cwe'] = 22
    elif row['vul_type'] == 'cwe-078':
        sven_test.at[index, 'cwe'] = 78
    elif row['vul_type'] == 'cwe-079':
        sven_test.at[index, 'cwe'] = 79
    elif row['vul_type'] == 'cwe-089':
        sven_test.at[index, 'cwe'] = 89
    else:
        sven_test.at[index, 'cwe'] = None

In [11]:
primevul_train['cwe'].unique()

array(["['CWE-20']", "['CWE-415']", "['CWE-787']", "['CWE-125']",
       "['CWE-119']", "['CWE-189']", "['CWE-264']", "['CWE-200']",
       "['CWE-476']", "['CWE-416']", "['CWE-772']", "['CWE-295']",
       "['CWE-310']", "['CWE-401']", "['CWE-399']", "['CWE-704']",
       "['CWE-77']", "['NVD-CWE-Other']", '[]', "['CWE-269']",
       "['CWE-284']", "['CWE-78']", "['CWE-311']", "['CWE-134']",
       "['CWE-276']", "['CWE-362']", "['CWE-345']", "['CWE-22']",
       "['CWE-241']", "['CWE-755']", "['CWE-254']", "['CWE-703']",
       "['CWE-190']", "['CWE-863']", "['CWE-665']", "['CWE-918']",
       "['CWE-120']", "['CWE-639']", "['CWE-369']", "['CWE-834']",
       "['CWE-763']", "['CWE-835']", "['CWE-252']", "['CWE-824']",
       "['CWE-674']", "['CWE-754']", "['CWE-400']", "['CWE-19']",
       "['CWE-17']", "['CWE-94']", "['CWE-79']", "['CWE-331']",
       "['CWE-617']", "['CWE-354']", "['CWE-59']", "['CWE-843']",
       "['CWE-287']", "['CWE-61']", "['CWE-281']", "['CWE-667']",
       "['CWE-862']", "['CWE-347']", "['CWE-255']", "['CWE-320']",
       "['CWE-823']", "['CWE-664']", "['CWE-121']", "['CWE-697']",
       "['CWE-88']", "['CWE-388']", "['CWE-681']", "['CWE-349']",
       "['CWE-693']", "['CWE-294']", "['CWE-131']", "['CWE-285']",
       "['CWE-327']", "['CWE-732']", "['CWE-352']", "['CWE-209']",
       "['CWE-502']", "['CWE-273']", "['CWE-191']", "['CWE-908']",
       "['CWE-74']", "['CWE-444']", "['CWE-404']", "['CWE-770']",
       "['CWE-909']", "['CWE-1021']", "['CWE-668']", "['CWE-122']",
       "['CWE-532']", "['CWE-798']", "['CWE-682']", "['CWE-672']",
       "['CWE-212']", "['CWE-113']", "['CWE-290']", "['CWE-129']",
       "['CWE-89']", "['CWE-307']", "['CWE-203']", "['CWE-93']",
       "['CWE-426']", "['CWE-326']", "['CWE-522']", "['CWE-193']",
       "['CWE-417']", "['CWE-16']", "['CWE-601']", "['CWE-346']",
       "['CWE-611']", "['CWE-361']", "['CWE-613']", "['CWE-172']"],
      dtype=object)

In [23]:
for index, row in primevul_train.iterrows():
    try:
        cwe_id = float(row['cwe'].split('-')[-1][:-2])
        primevul_train.at[index, 'cwe'] = cwe_id
    except ValueError:
        primevul_train.at[index, 'cwe'] = 999

for index, row in primevul_val.iterrows():
    try:
        cwe_id = float(row['cwe'].split('-')[-1][:-2])
    except ValueError:
        cwe_id = 999
    primevul_val.at[index, 'cwe'] = cwe_id

for index, row in primevul_test.iterrows():
    try:
        cwe_id = float(row['cwe'].split('-')[-1][:-2])
    except ValueError:
        cwe_id = 999
    primevul_test.at[index, 'cwe'] = cwe_id

In [17]:
sven_train.iloc[0]['cwe']

np.float64(79.0)

In [27]:
primevul_train.head()

,idx,project,commit_id,project_url,commit_url,commit_message,target,func,func_hash,file_name,file_hash,cwe,cve,cve_desc,nvd_url,code,label,language
0,12806,samba,a819d2b440aafa3138d95ff6e8b824da885a70e9,https://github.com/samba-team/samba,https://git.samba.org/?p=samba.git;a=commitdif...,CVE-2015-5296: libcli/smb: make sure we requir...,0,const char *smbXcli_conn_remote_name(struct sm...,1237698367289631204308328920919550716,smbXcli_base.c,331622354437169301578486293682424361127,20.0,CVE-2015-5296,"Samba 3.x and 4.x before 4.1.22, 4.2.x before ...",https://nvd.nist.gov/vuln/detail/CVE-2015-5296,const char *smbXcli_conn_remote_name(struct sm...,0,CCPP
1,10820,nmap,350bbe0597d37ad67abe5fef8fba984707b4e9ad,https://github.com/nmap/nmap,https://github.com/nmap/nmap/commit/350bbe0597...,Avoid a crash (double-free) when SSH connectio...,1,"static int do_session_handshake (lua_State *L,...",158553276448407058877806570620623389090,nse_libssh2.cc,198789152988758879779329023859317580758,415.0,CVE-2017-18594,nse_libssh2.cc in Nmap 7.70 is subject to a de...,https://nvd.nist.gov/vuln/detail/CVE-2017-18594,"static int do_session_handshake (lua_State *L,...",1,CCPP
2,196266,ImageMagick,63302366a63602acbaad5c8223a105811b2adddd,https://github.com/ImageMagick/ImageMagick,https://github.com/ImageMagick/ImageMagick/com...,Improve buffer overflow sanity check,1,static Image *ReadTIFFImage(const ImageInfo *i...,217182507208746682644661587427845758125,tiff.c,282976777664008314084580813339151903411,787.0,CVE-2016-10064,Buffer overflow in coders/tiff.c in ImageMagic...,https://nvd.nist.gov/vuln/detail/CVE-2016-10064,static Image *ReadTIFFImage(const ImageInfo *i...,1,CCPP
3,2576,tcpdump,db8c799f6dfc68765c9451fcbfca06e662f5bd5f,https://github.com/the-tcpdump-group/tcpdump,https://github.com/the-tcpdump-group/tcpdump/c...,CVE-2017-13009/IPv6 mobility: Add a bounds che...,1,"mobility_print(netdissect_options *ndo,\n ...",234313348879631125998556739362622837502,print-mobility.c,226475948374881409132642604864562430267,125.0,CVE-2017-13009,The IPv6 mobility parser in tcpdump before 4.9...,https://nvd.nist.gov/vuln/detail/CVE-2017-13009,"mobility_print(netdissect_options *ndo,\n ...",1,CCPP
4,12267,spice,8af619009660b24e0b41ad26b30289eea288fcc2,https://gitlab.freedesktop.org/spice/spice,https://cgit.freedesktop.org/spice/spice/commi...,Fix buffer overflow when decrypting client SPI...,0,static unsigned long pthreads_thread_id(void)\...,127351323319873153702695078495849589203,reds.c,253596976331707060179602102741411418827,119.0,CVE-2013-4282,Stack-based buffer overflow in the reds_handle...,https://nvd.nist.gov/vuln/detail/CVE-2013-4282,static unsigned long pthreads_thread_id(void)\...,0,CCPP

In [33]:
sven_train_moe_new = pd.DataFrame({
    'code': sven_train['code'],
    'vuln': sven_train['label'],
    'cwe': sven_train['cwe'],
    'language': 'Python'
})
sven_val_moe_new = pd.DataFrame({
    'code': sven_val['code'],
    'vuln': sven_val['label'],
    'cwe': sven_val['cwe'],
    'language': 'Python'
})
sven_test_moe_new = pd.DataFrame({
    'code': sven_test['code'],
    'vuln': sven_test['label'],
    'cwe': sven_test['cwe'],
    'language': 'Python'
})
sven_train_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      486 non-null    object
 1   vuln      486 non-null    int64
 2   cwe       486 non-null    float64
 3   language  486 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 15.3+ KB

In [34]:
primevul_train_moe_new = pd.DataFrame({
    'code': primevul_train['code'],
    'vuln': primevul_train['label'],
    'cwe': primevul_train['cwe'],
    'language': 'CCPP'
})
primevul_val_moe_new = pd.DataFrame({
    'code': primevul_val['code'],
    'vuln': primevul_val['label'],
    'cwe': primevul_val['cwe'],
    'language': 'CCPP'
})
primevul_test_moe_new = pd.DataFrame({
    'code': primevul_test['code'],
    'vuln': primevul_test['label'],
    'cwe': primevul_test['cwe'],
    'language': 'CCPP'
})
primevul_train_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      7889 non-null   object
 1   vuln      7889 non-null   int64
 2   cwe       7889 non-null   object
 3   language  7889 non-null   object
dtypes: int64(1), object(3)
memory usage: 246.7+ KB

In [35]:
primevul_sven_train_moe_new = pd.concat([primevul_train_moe_new, sven_train_moe_new], ignore_index=True)
primevul_sven_val_moe_new = pd.concat([primevul_val_moe_new, sven_val_moe_new], ignore_index=True)
primevul_sven_test_moe_new = pd.concat([primevul_test_moe_new, sven_test_moe_new], ignore_index=True)
primevul_sven_train_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8375 entries, 0 to 8374
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      8375 non-null   object
 1   vuln      8375 non-null   int64
 2   cwe       8375 non-null   object
 3   language  8375 non-null   object
dtypes: int64(1), object(3)
memory usage: 261.8+ KB

In [36]:
primevul_sven_train_moe_new.to_csv("./dataset/MoE/primevul_sven_train_moe_new.csv", index=False)
primevul_sven_val_moe_new.to_csv("./dataset/MoE/primevul_sven_val_moe_new.csv", index=False)
primevul_sven_test_moe_new.to_csv("./dataset/MoE/primevul_sven_test_moe_new.csv", index=False)

In [ ]:
primevul_sven_train_moe_new.to_json("./dataset/MoE/primevul_sven_train_moe_new.jsonl", orient="records", lines=True)
primevul_sven_val_moe_new.to_json("./dataset/MoE/primevul_sven_val_moe_new.jsonl", orient="records", lines=True)
primevul_sven_test_moe_new.to_json("./dataset/MoE/primevul_sven_test_moe_new.jsonl", orient="records", lines=True)

In [1]:
import pandas as pd
import json

In [2]:
primevul_sven_val_moe_new = pd.read_csv("./dataset/MoE/primevul_sven_val_moe_new.csv")
primevul_sven_val_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1108 entries, 0 to 1107
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1108 non-null   object
 1   vuln      1108 non-null   int64
 2   cwe       1108 non-null   float64
 3   language  1108 non-null   object
dtypes: float64(1), int64(1), object(2)
memory usage: 34.8+ KB

In [3]:
primevul_sven_test_moe_new = pd.read_csv("./dataset/MoE/primevul_sven_test_moe_new.csv")
primevul_sven_test_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1139 non-null   object
 1   vuln      1139 non-null   int64
 2   cwe       1139 non-null   float64
 3   language  1139 non-null   object
dtypes: float64(1), int64(1), object(2)
memory usage: 35.7+ KB

In [6]:
primevul_val_new = primevul_sven_val_moe_new[primevul_sven_val_moe_new['language'] == 'CCPP']
primevul_test_new = primevul_sven_test_moe_new[primevul_sven_test_moe_new['language'] == 'CCPP']
primevul_sven_val_moe_new = primevul_sven_val_moe_new.drop(primevul_val_new.index)
primevul_sven_test_moe_new = primevul_sven_test_moe_new.drop(primevul_test_new.index)
primevul_sven_val_moe_new.info()
primevul_sven_test_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 986 to 1107
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      122 non-null    object
 1   vuln      122 non-null    int64
 2   cwe       122 non-null    float64
 3   language  122 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 3.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 987 to 1138
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      152 non-null    object
 1   vuln      152 non-null    int64
 2   cwe       152 non-null    float64
 3   language  152 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 4.9+ KB

In [9]:
primevul_val_moe_new = primevul_val_new.sample(frac=1, random_state=42).reset_index(drop=True)
primevul_test_moe_new = primevul_test_new.sample(frac=1, random_state=42).reset_index(drop=True)
primevul_val_moe_new.info()
primevul_test_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      986 non-null    object
 1   vuln      986 non-null    int64
 2   cwe       986 non-null    float64
 3   language  986 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 30.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      987 non-null    object
 1   vuln      987 non-null    int64
 2   cwe       987 non-null    float64
 3   language  987 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 31.0+ KB

In [10]:
primevul_val_moe_new_label_1 = primevul_val_moe_new[primevul_val_moe_new['vuln'] == 1]
primevul_val_moe_new_label_0 = primevul_val_moe_new[primevul_val_moe_new['vuln'] == 0]
primevul_test_moe_new_label_1 = primevul_test_moe_new[primevul_test_moe_new['vuln'] == 1]
primevul_test_moe_new_label_0 = primevul_test_moe_new[primevul_test_moe_new['vuln'] == 0]
print(f"Val label 1: {len(primevul_val_moe_new_label_1)}, Val label 0: {len(primevul_val_moe_new_label_0)}")
print(f"Test label 1: {len(primevul_test_moe_new_label_1)}, Test label 0: {len(primevul_test_moe_new_label_0)}")

Val label 1: 489, Val label 0: 497
Test label 1: 494, Test label 0: 493

In [11]:
primevul_val_moe_new = pd.concat([primevul_val_moe_new_label_1[:300], primevul_val_moe_new_label_0, primevul_test_moe_new_label_0[304:]], ignore_index=True)
primevul_test_moe_new = pd.concat([primevul_test_moe_new_label_1, primevul_val_moe_new_label_1[300:], primevul_test_moe_new_label_0[:304]], ignore_index=True)

In [12]:
primevul_val_moe_new_label_1 = primevul_val_moe_new[primevul_val_moe_new['vuln'] == 1]
primevul_val_moe_new_label_0 = primevul_val_moe_new[primevul_val_moe_new['vuln'] == 0]
primevul_test_moe_new_label_1 = primevul_test_moe_new[primevul_test_moe_new['vuln'] == 1]
primevul_test_moe_new_label_0 = primevul_test_moe_new[primevul_test_moe_new['vuln'] == 0]
print(f"Val label 1: {len(primevul_val_moe_new_label_1)}, Val label 0: {len(primevul_val_moe_new_label_0)}")
print(f"Test label 1: {len(primevul_test_moe_new_label_1)}, Test label 0: {len(primevul_test_moe_new_label_0)}")

Val label 1: 300, Val label 0: 686
Test label 1: 683, Test label 0: 304

In [13]:
primevul_sven_val_moe_new = pd.concat([primevul_sven_val_moe_new, primevul_val_moe_new], ignore_index=True)
primevul_sven_test_moe_new = pd.concat([primevul_sven_test_moe_new, primevul_test_moe_new], ignore_index=True)
primevul_sven_val_moe_new.info()
primevul_sven_test_moe_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1108 entries, 0 to 1107
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1108 non-null   object
 1   vuln      1108 non-null   int64
 2   cwe       1108 non-null   float64
 3   language  1108 non-null   object
dtypes: float64(1), int64(1), object(2)
memory usage: 34.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1139 non-null   object
 1   vuln      1139 non-null   int64
 2   cwe       1139 non-null   float64
 3   language  1139 non-null   object
dtypes: float64(1), int64(1), object(2)
memory usage: 35.7+ KB

In [14]:
primevul_sven_val_moe_new.to_json("./dataset/MoE/primevul_sven_val_moe_nounder.jsonl", orient="records", lines=True)
primevul_sven_test_moe_new.to_json("./dataset/MoE/primevul_sven_test_moe_nounder.jsonl", orient="records", lines=True)

In [22]:
import pandas as pd
import json
import re

In [31]:
pr_train_data = []
with open('C:/hienlt/treesitter/dataset/Primevul/primevul_train.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_train_data.append(record)
primevul_train_df = pd.DataFrame(pr_train_data)
primevul_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175797 entries, 0 to 175796
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idx             175797 non-null  int64
 1   project         175797 non-null  object
 2   commit_id       175797 non-null  object
 3   project_url     175797 non-null  object
 4   commit_url      175797 non-null  object
 5   commit_message  175797 non-null  object
 6   target          175797 non-null  int64
 7   func            175797 non-null  object
 8   func_hash       175797 non-null  object
 9   file_name       175797 non-null  object
 10  file_hash       120537 non-null  float64
 11  cwe             175797 non-null  object
 12  cve             175797 non-null  object
 13  cve_desc        175797 non-null  object
 14  nvd_url         175797 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 20.1+ MB

In [24]:
pr_valid_data = []
with open('C:/hienlt/treesitter/dataset/Primevul/primevul_valid.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_valid_data.append(record)
primevul_valid_df = pd.DataFrame(pr_valid_data)
primevul_valid_df.info()

pr_test_data = []
with open('C:/hienlt/treesitter/dataset/Primevul/primevul_test.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_test_data.append(record)
primevul_test_df = pd.DataFrame(pr_test_data)
primevul_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23948 entries, 0 to 23947
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             23948 non-null  int64
 1   project         23948 non-null  object
 2   commit_id       23948 non-null  object
 3   project_url     23948 non-null  object
 4   commit_url      23948 non-null  object
 5   commit_message  23948 non-null  object
 6   target          23948 non-null  int64
 7   func            23948 non-null  object
 8   func_hash       23948 non-null  object
 9   file_name       23948 non-null  object
 10  file_hash       19649 non-null  float64
 11  cwe             23948 non-null  object
 12  cve             23948 non-null  object
 13  cve_desc        23948 non-null  object
 14  nvd_url         23948 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 2.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24788 entries, 0 to 24787
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             24788 non-null  int64
 1   project         24788 non-null  object
 2   commit_id       24788 non-null  object
 3   project_url     24788 non-null  object
 4   commit_url      24788 non-null  object
 5   commit_message  24788 non-null  object
 6   target          24788 non-null  int64
 7   func            24788 non-null  object
 8   func_hash       24788 non-null  object
 9   file_name       24788 non-null  object
 10  file_hash       18878 non-null  float64
 11  cwe             24788 non-null  object
 12  cve             24788 non-null  object
 13  cve_desc        24788 non-null  object
 14  nvd_url         24788 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 2.8+ MB

In [4]:
primevul_train_df[primevul_train_df['target'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 4862 entries, 0 to 84266
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             4862 non-null   int64
 1   project         4862 non-null   object
 2   commit_id       4862 non-null   object
 3   project_url     4862 non-null   object
 4   commit_url      4862 non-null   object
 5   commit_message  4862 non-null   object
 6   target          4862 non-null   int64
 7   func            4862 non-null   object
 8   func_hash       4862 non-null   object
 9   file_name       4862 non-null   object
 10  file_hash       3359 non-null   float64
 11  cwe             4862 non-null   object
 12  cve             4862 non-null   object
 13  cve_desc        4862 non-null   object
 14  nvd_url         4862 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 607.8+ KB

In [25]:
pr_label_1 = primevul_train_df[primevul_train_df['target'] == 1]
pr_label_1 = pr_label_1.sample(frac=1, random_state=42).reset_index(drop=True)
pr_label_0 = primevul_train_df[primevul_train_df['target'] == 0]
pr_label_0 = pr_label_0.sample(frac=1, random_state=42).reset_index(drop=True)
pr_label_0 = pr_label_0[:len(pr_label_1)]

In [26]:
pr_train_df = pd.concat([pr_label_1, pr_label_0], ignore_index=True)
pr_train_df = pr_train_df.sample(frac=1, random_state=42).reset_index(drop=True)
pr_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9724 entries, 0 to 9723
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             9724 non-null   int64
 1   project         9724 non-null   object
 2   commit_id       9724 non-null   object
 3   project_url     9724 non-null   object
 4   commit_url      9724 non-null   object
 5   commit_message  9724 non-null   object
 6   target          9724 non-null   int64
 7   func            9724 non-null   object
 8   func_hash       9724 non-null   object
 9   file_name       9724 non-null   object
 10  file_hash       6694 non-null   float64
 11  cwe             9724 non-null   object
 12  cve             9724 non-null   object
 13  cve_desc        9724 non-null   object
 14  nvd_url         9724 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 1.1+ MB

In [28]:
cnt = 0
for index, row in pr_train_df.iterrows():
    if(index < 5): print(row['cwe'])
    if len(row['cwe']) == 0:
        cnt += 1
print(f"Number of samples with multiple CWEs: {cnt}")

['CWE-264']
['CWE-703']
['CWE-401']
['CWE-787']
['CWE-20']
Number of samples with multiple CWEs: 540

In [33]:
# for index, row in pr_train_df.iterrows():
#     try:
#         if(len(row['cwe']) == 0):
#             pr_train_df.at[index, 'cwe'] = -1
#             continue
#         cwe_id = int(row['cwe'][0].split('-')[-1])
#         pr_train_df.at[index, 'cwe'] = cwe_id
#     except ValueError:
#         primevul_train_df.at[index, 'cwe'] = -2
        
# for index, row in primevul_train_df.iterrows():
#     try:
#         # print(row['cwe'])
#         if(len(row['cwe']) == 0):
#             primevul_train_df.at[index, 'cwe'] = -1
#             continue
#         cwe_id = int(row['cwe'][0].split('-')[-1])
#         primevul_train_df.at[index, 'cwe'] = cwe_id
#     except ValueError:
#         primevul_train_df.at[index, 'cwe'] = -2
#         continue

for index, row in primevul_valid_df.iterrows():
    try:
        if(len(row['cwe']) == 0):
            primevul_valid_df.at[index, 'cwe'] = -1
            continue
        cwe_id = int(row['cwe'][0].split('-')[-1])
        primevul_valid_df.at[index, 'cwe'] = cwe_id
    except ValueError:
        primevul_valid_df.at[index, 'cwe'] = -2
        continue


for index, row in primevul_test_df.iterrows():
    try:
        if(len(row['cwe']) == 0):
            primevul_test_df.at[index, 'cwe'] = -1
            continue
        cwe_id = int(row['cwe'][0].split('-')[-1])
        primevul_test_df.at[index, 'cwe'] = cwe_id
    except ValueError:
        primevul_test_df.at[index, 'cwe'] = -2
        continue

In [34]:
pr_val_df = primevul_valid_df[primevul_valid_df['target'] == 1]
pr_val_df = primevul_valid_df[primevul_valid_df['target'] == 0].sample(n=len(pr_val_df), random_state=42).reset_index(drop=True)
pr_val_df = pd.concat([pr_val_df, primevul_valid_df[primevul_valid_df['target'] == 1]], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_val_df.info()    

pr_test_df = primevul_test_df[primevul_test_df['target'] == 1]
pr_test_df = primevul_test_df[primevul_test_df['target'] == 0].sample(n=len(pr_test_df), random_state=42).reset_index(drop=True)
pr_test_df = pd.concat([pr_test_df, primevul_valid_df[primevul_valid_df['target'] == 1]], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             1186 non-null   int64
 1   project         1186 non-null   object
 2   commit_id       1186 non-null   object
 3   project_url     1186 non-null   object
 4   commit_url      1186 non-null   object
 5   commit_message  1186 non-null   object
 6   target          1186 non-null   int64
 7   func            1186 non-null   object
 8   func_hash       1186 non-null   object
 9   file_name       1186 non-null   object
 10  file_hash       991 non-null    float64
 11  cwe             1186 non-null   object
 12  cve             1186 non-null   object
 13  cve_desc        1186 non-null   object
 14  nvd_url         1186 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 139.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1142 entries, 0 to 1141
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             1142 non-null   int64
 1   project         1142 non-null   object
 2   commit_id       1142 non-null   object
 3   project_url     1142 non-null   object
 4   commit_url      1142 non-null   object
 5   commit_message  1142 non-null   object
 6   target          1142 non-null   int64
 7   func            1142 non-null   object
 8   func_hash       1142 non-null   object
 9   file_name       1142 non-null   object
 10  file_hash       915 non-null    float64
 11  cwe             1142 non-null   object
 12  cve             1142 non-null   object
 13  cve_desc        1142 non-null   object
 14  nvd_url         1142 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 134.0+ KB

In [ ]:
# primevul_test_df.drop(primevul_test_df[primevul_test_df['cwe'] == 0].index, inplace=True)
# primevul_valid_df.drop(primevul_valid_df[primevul_valid_df['cwe'] == 0].index, inplace=True)

In [35]:
# primevul_test_df.info()
primevul_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24788 entries, 0 to 24787
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             24788 non-null  int64
 1   project         24788 non-null  object
 2   commit_id       24788 non-null  object
 3   project_url     24788 non-null  object
 4   commit_url      24788 non-null  object
 5   commit_message  24788 non-null  object
 6   target          24788 non-null  int64
 7   func            24788 non-null  object
 8   func_hash       24788 non-null  object
 9   file_name       24788 non-null  object
 10  file_hash       18878 non-null  float64
 11  cwe             24788 non-null  object
 12  cve             24788 non-null  object
 13  cve_desc        24788 non-null  object
 14  nvd_url         24788 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 2.8+ MB

In [36]:
pr_moe_train_df = pd.DataFrame({
    'code': primevul_train_df['func'],    
    'vuln': primevul_train_df['target'],
    'cwe': primevul_train_df['cwe'],
    'language': 'CCPP'
})
pr_moe_valid_df = pd.DataFrame({
    'code': primevul_valid_df['func'],    
    'vuln': primevul_valid_df['target'],
    'cwe': primevul_valid_df['cwe'],
    'language': 'CCPP'
})
pr_moe_test_df = pd.DataFrame({
    'code': primevul_test_df['func'],    
    'vuln': primevul_test_df['target'],
    'cwe': primevul_test_df['cwe'],
    'language': 'CCPP'
})

pr_moe_train_under_df = pd.DataFrame({
    'code': pr_train_df['func'],    
    'vuln': pr_train_df['target'],
    'cwe': pr_train_df['cwe'],
    'language': 'CCPP'
})
pr_moe_valid_under_df = pd.DataFrame({
    'code': pr_val_df['func'],    
    'vuln': pr_val_df['target'],
    'cwe': pr_val_df['cwe'],
    'language': 'CCPP'
})
pr_moe_test_under_df = pd.DataFrame({
    'code': pr_test_df['func'],    
    'vuln': pr_test_df['target'],
    'cwe': pr_test_df['cwe'],
    'language': 'CCPP'
})

                                                code  vuln  cwe language
0  static int raw_cmd_copyout(int cmd, void __use...     1  264     CCPP
1  static int decode_attr_aclsupport(struct xdr_s...     0  703     CCPP
2  static Image *ReadPCLImage(const ImageInfo *im...     1  401     CCPP
3  static int axff_init(struct hid_device *hid)\n...     1  787     CCPP
4  static void x25_kill_by_device(struct net_devi...     0   20     CCPP

In [41]:
pr_sv_train_moe = pd.read_csv("./dataset/MoE/primevul_sven_train_moe_new.csv")
pr_sv_val_moe = pd.read_csv("./dataset/MoE/primevul_sven_val_moe_new.csv")
pr_sv_test_moe = pd.read_csv("./dataset/MoE/primevul_sven_test_moe_new.csv")
sv_train_moe = pr_sv_train_moe[pr_sv_train_moe['language'] == 'Python']
sv_val_moe = pr_sv_val_moe[pr_sv_val_moe['language'] == 'Python']
sv_test_moe = pr_sv_test_moe[pr_sv_test_moe['language'] == 'Python']
for index, row in sv_train_moe.iterrows():
    sv_train_moe.at[index, 'cwe'] = int(row['cwe'])
for index, row in sv_val_moe.iterrows():
    sv_val_moe.at[index, 'cwe'] = int(row['cwe'])
for index, row in sv_test_moe.iterrows():
    sv_test_moe.at[index, 'cwe'] = int(row['cwe'])
sv_train_moe.info()
sv_val_moe.info()
sv_test_moe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 486 entries, 7889 to 8374
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      486 non-null    object
 1   vuln      486 non-null    int64
 2   cwe       486 non-null    float64
 3   language  486 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 35.1+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 986 to 1107
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      122 non-null    object
 1   vuln      122 non-null    int64
 2   cwe       122 non-null    float64
 3   language  122 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 8.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 987 to 1138
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      152 non-null    object
 1   vuln      152 non-null    int64
 2   cwe       152 non-null    float64
 3   language  152 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 10.0+ KB

In [42]:
pr_sv_train_moe_under = pd.concat([pr_moe_train_under_df, sv_train_moe], ignore_index=True)
pr_sv_val_moe_under = pd.concat([pr_moe_valid_under_df, sv_val_moe], ignore_index=True)
pr_sv_test_moe_under = pd.concat([pr_moe_test_under_df, sv_test_moe], ignore_index=True)

pr_sv_train_moe_nounder = pd.concat([pr_moe_train_df, sv_train_moe], ignore_index=True)
pr_sv_val_moe_nounder = pd.concat([pr_moe_valid_df, sv_val_moe], ignore_index=True)
pr_sv_test_moe_nounder = pd.concat([pr_moe_test_df, sv_test_moe], ignore_index=True)

In [45]:
pr_sv_train_moe_under.to_json("./dataset/MoE/pr_sv_full_cmt/under/pr_sv_train_moe_under.jsonl", orient="records", lines=True)
pr_sv_val_moe_under.to_json("./dataset/MoE/pr_sv_full_cmt/under/pr_sv_val_moe_under.jsonl", orient="records", lines=True)
pr_sv_test_moe_under.to_json("./dataset/MoE/pr_sv_full_cmt/under/pr_sv_test_moe_under.jsonl", orient="records", lines=True)

pr_sv_train_moe_nounder.to_json("./dataset/MoE/pr_sv_full_cmt/nounder/pr_sv_train_moe_nounder.jsonl", orient="records", lines=True)
pr_sv_val_moe_nounder.to_json("./dataset/MoE/pr_sv_full_cmt/nounder/pr_sv_val_moe_nounder.jsonl", orient="records", lines=True)
pr_sv_test_moe_nounder.to_json("./dataset/MoE/pr_sv_full_cmt/nounder/pr_sv_test_moe_nounder.jsonl", orient="records", lines=True)

In [69]:
pr_sv_train_moe_noundervaltest = pd.concat([pr_moe_train_df, sv_train_moe], ignore_index=True)
pr_sv_val_moe_noundervaltest = pd.concat([pr_moe_valid_df, sv_val_moe], ignore_index=True)
pr_sv_test_moe_noundervaltest = pd.concat([pr_moe_test_df, sv_test_moe], ignore_index=True)

In [70]:
pr_sv_train_moe_noundervaltest = pr_sv_train_moe_noundervaltest.sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_val_moe_noundervaltest = pr_sv_val_moe_noundervaltest.sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_test_moe_noundervaltest = pr_sv_test_moe_noundervaltest.sample(frac=1, random_state=42).reset_index(drop=True)

In [71]:
pr_sv_train_moe_noundervaltest.to_json("./dataset/MoE/primevul_sven_train_moe_noundervaltest.jsonl", orient="records", lines=True)
pr_sv_val_moe_noundervaltest.to_json("./dataset/MoE/primevul_sven_val_moe_noundervaltest.jsonl", orient="records", lines=True)
pr_sv_test_moe_noundervaltest.to_json("./dataset/MoE/primevul_sven_test_moe_noundervaltest.jsonl", orient="records", lines=True)

In [9]:
for index, row in pr_moe_train_raw_df.iterrows():
    pr_moe_train_raw_df.at[index, 'cwe'] = int(row['cwe'])

# for index, row in pr_sv_val_moe_noundervaltest.iterrows():
#     pr_sv_val_moe_noundervaltest.at[index, 'cwe'] = int(row['cwe'])

# for index, row in pr_sv_test_moe_noundervaltest.iterrows():
#     pr_sv_test_moe_noundervaltest.at[index, 'cwe'] = int(row['cwe'])

pr_moe_train_raw_df.head()

                                                code  vuln  cwe language
0   long ssl_get_algorithm2(SSL *s)\n        {\n ...     1  310     CCPP
1  gnutls_session_get_data (gnutls_session_t sess...     1  119     CCPP
2  gnutls_session_get_data (gnutls_session_t sess...     1  119     CCPP
3  getftp (struct url *u, wgint passed_expected_b...     1  200     CCPP
4  void fz_init_cached_color_converter(fz_context...     1   20     CCPP

In [77]:
pr_train_moe_noundervaltest = pr_sv_train_moe_noundervaltest[pr_sv_train_moe_noundervaltest['language'] == 'CCPP']
sv_train_moe_noundervaltest = pr_sv_train_moe_noundervaltest[pr_sv_train_moe_noundervaltest['language'] == 'Python']
pr_val_moe_noundervaltest = pr_sv_val_moe_noundervaltest[pr_sv_val_moe_noundervaltest['language'] == 'CCPP']
sv_val_moe_noundervaltest = pr_sv_val_moe_noundervaltest[pr_sv_val_moe_noundervaltest['language'] == 'Python']
pr_test_moe_noundervaltest = pr_sv_test_moe_noundervaltest[pr_sv_test_moe_noundervaltest['language'] == 'CCPP']
sv_test_moe_noundervaltest = pr_sv_test_moe_noundervaltest[pr_sv_test_moe_noundervaltest['language'] == 'Python']
pr_train_moe_noundervaltest.info()
sv_train_moe_noundervaltest.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9724 entries, 0 to 10209
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9724 non-null   object
 1   vuln      9724 non-null   int64
 2   cwe       9724 non-null   object
 3   language  9724 non-null   object
dtypes: int64(1), object(3)
memory usage: 379.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 486 entries, 10 to 10181
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      486 non-null    object
 1   vuln      486 non-null    int64
 2   cwe       486 non-null    object
 3   language  486 non-null    object
dtypes: int64(1), object(3)
memory usage: 19.0+ KB

In [ ]:
def remove_comments(code):
    code = re.sub(r'//.*?\n|/\*.*?\*/|#.*?\n', '', code, flags=re.S)
    code = re.sub(r'/\*.*?\*/', '', code, flags=re.S)
    return code

In [22]:

def remove_comments_java(code):
    # Pattern explanation:
    # Group 1: Matches String literals ("...") OR Char literals ('...')
    # Match 2: Single-line comments (//...)
    # Match 3: Multi-line comments (/*...*/)
    pattern = r'("[^"\\]*(?:\\.[^"\\]*)*"|\'[^\'\\]*(?:\\.[^\'\\]*)*\')|//[^\n]*|/\*.*?\*/'
    
    # If the regex matched a string/char (Group 1), put it back. 
    # Otherwise, it matched a comment, so replace it with an empty string.
    code = re.sub(pattern, lambda m: m.group(1) if m.group(1) else '', code, flags=re.S)
    return code

In [23]:
def remove_comments_python(code):
    """Remove Python comments from code."""
    code = re.sub(r'#.*?\n', '\n', code)
    # Remove docstrings (simple approach)
    code = re.sub(r'""".*?"""', '""', code, flags=re.S)
    code = re.sub(r"'''.*?'''", "''", code, flags=re.S)
    return code

In [ ]:
def remove_comments_generic(code, extension):
    clean_code_mapping = {
        'c': remove_comments(code=code),
        'cpp': remove_comments(code=code),
        'java': remove_comments_java(code=code),
        'py': remove_comments_python(code=code)
    }
    return clean_code_mapping.get(extension, code)

In [82]:
for index, row in sv_train_moe_noundervaltest.iterrows():
    sv_train_moe_noundervaltest.at[index, 'code'] = remove_comments_python(row['code'])

for index, row in sv_val_moe_noundervaltest.iterrows():
    sv_val_moe_noundervaltest.at[index, 'code'] = remove_comments_python(row['code'])

for index, row in sv_test_moe_noundervaltest.iterrows():
    sv_test_moe_noundervaltest.at[index, 'code'] = remove_comments_python(row['code'])

In [83]:
pr_sv_train_moe_noundervaltest = pd.concat([pr_train_moe_noundervaltest, sv_train_moe_noundervaltest], ignore_index=True)
pr_sv_val_moe_noundervaltest = pd.concat([pr_val_moe_noundervaltest, sv_val_moe_noundervaltest], ignore_index=True)
pr_sv_test_moe_noundervaltest = pd.concat([pr_test_moe_noundervaltest, sv_test_moe_noundervaltest], ignore_index=True)
pr_sv_train_moe_noundervaltest.sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_val_moe_noundervaltest.sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_test_moe_noundervaltest.sample(frac=1, random_state=42).reset_index(drop=True)

                                                    code  vuln  cwe language
0      SPICE_GNUC_VISIBLE int spice_server_set_agent_...     0   -2     CCPP
1      void LinkResolver::resolve_invokeinterface(Cal...     0   -2     CCPP
2      xfs_perag_clear_reclaim_tag(\n\tstruct xfs_per...     0   -1     CCPP
3      static void copy_rr(pj_pool_t *pool, pj_dns_pa...     0  787     CCPP
4      static int set_find_vma_callback_state(struct ...     0  787     CCPP
...                                                  ...   ...  ...      ...
24935  static void copy_query(pj_pool_t *pool, pj_dns...     0  787     CCPP
24936  xfrm_secpath_reject(int idx, struct sk_buff *s...     0  125     CCPP
24937  static void ddc_register_devices(void)\n{\n   ...     0  125     CCPP
24938  static int io_iopoll_check(struct io_ring_ctx ...     0   94     CCPP
24939    void Compute(OpKernelContext* context) overr...     0  125     CCPP

[24940 rows x 4 columns]

In [86]:
pr_sv_train_moe_noundervaltest.to_json("./dataset/MoE/primevul_sven_train_moe_noundervaltest.jsonl", orient="records", lines=True)
pr_sv_val_moe_noundervaltest.to_json("./dataset/MoE/primevul_sven_val_moe_noundervaltest.jsonl", orient="records", lines=True)
pr_sv_test_moe_noundervaltest.to_json("./dataset/MoE/primevul_sven_test_moe_noundervaltest.jsonl", orient="records", lines=True)

In [1]:
import json
import pandas as pd
pr_sv_train_moe_noundervaltest_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_train_moe_noundervaltest.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train_moe_noundervaltest_data.append(record)

pr_sv_train_moe_noundervaltest_df = pd.DataFrame(pr_sv_train_moe_noundervaltest_data)
pr_sv_train_moe_noundervaltest_df.info()

pr_sv_val_moe_noundervaltest_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_val_moe_noundervaltest.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_val_moe_noundervaltest_data.append(record)
pr_sv_val_moe_noundervaltest_df = pd.DataFrame(pr_sv_val_moe_noundervaltest_data)
pr_sv_val_moe_noundervaltest_df.info()

pr_sv_test_moe_noundervaltest_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_test_moe_noundervaltest.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test_moe_noundervaltest_data.append(record)   
pr_sv_test_moe_noundervaltest_df = pd.DataFrame(pr_sv_test_moe_noundervaltest_data)
pr_sv_test_moe_noundervaltest_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10210 entries, 0 to 10209
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      10210 non-null  object
 1   vuln      10210 non-null  int64
 2   cwe       10210 non-null  int64
 3   language  10210 non-null  object
dtypes: int64(2), object(2)
memory usage: 319.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24070 entries, 0 to 24069
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24070 non-null  object
 1   vuln      24070 non-null  int64
 2   cwe       24070 non-null  int64
 3   language  24070 non-null  object
dtypes: int64(2), object(2)
memory usage: 752.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24940 entries, 0 to 24939
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24940 non-null  object
 1   vuln      24940 non-null  int64
 2   cwe       24940 non-null  int64
 3   language  24940 non-null  object
dtypes: int64(2), object(2)
memory usage: 779.5+ KB

In [17]:
pr_train = pr_sv_train_moe_noundervaltest_df[pr_sv_train_moe_noundervaltest_df['language'] == 'CCPP']
pr_val = pr_sv_val_moe_noundervaltest_df[pr_sv_val_moe_noundervaltest_df['language'] == 'CCPP']
pr_test = pr_sv_test_moe_noundervaltest_df[pr_sv_test_moe_noundervaltest_df['language'] == 'CCPP']
sv_train = pr_sv_train_moe_noundervaltest_df[pr_sv_train_moe_noundervaltest_df['language'] == 'Python']
sv_val = pr_sv_val_moe_noundervaltest_df[pr_sv_val_moe_noundervaltest_df['language'] == 'Python']
sv_test = pr_sv_test_moe_noundervaltest_df[pr_sv_test_moe_noundervaltest_df['language'] == 'Python']
pr_train.info() 
pr_val.info()
pr_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9724 entries, 0 to 9723
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9724 non-null   object
 1   vuln      9724 non-null   int64
 2   cwe       9724 non-null   int64
 3   language  9724 non-null   object
dtypes: int64(2), object(2)
memory usage: 379.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 23948 entries, 0 to 23947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      23948 non-null  object
 1   vuln      23948 non-null  int64
 2   cwe       23948 non-null  int64
 3   language  23948 non-null  object
dtypes: int64(2), object(2)
memory usage: 935.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 24788 entries, 0 to 24787
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24788 non-null  object
 1   vuln      24788 non-null  int64
 2   cwe       24788 non-null  int64
 3   language  24788 non-null  object
dtypes: int64(2), object(2)
memory usage: 968.3+ KB

In [3]:
pr_train.to_csv("./dataset/MVD/primevul_train_noundervaltest.csv", index=False)
pr_val.to_csv("./dataset/MVD/primevul_val_noundervaltest.csv", index=False)
pr_test.to_csv("./dataset/MVD/primevul_test_noundervaltest.csv", index=False)
sv_train.to_csv("./dataset/MVD/sven_train_nocmt.csv", index=False)
sv_val.to_csv("./dataset/MVD/sven_val_nocmt.csv", index=False)
sv_test.to_csv("./dataset/MVD/sven_test_nocmt.csv", index=False)

In [18]:
pr_train.to_json("./dataset/MVD/primevul_train_noundervaltest.jsonl", orient="records", lines=True)
pr_val.to_json("./dataset/MVD/primevul_val_noundervaltest.jsonl", orient="records", lines=True)
pr_test.to_json("./dataset/MVD/primevul_test_noundervaltest.jsonl", orient="records", lines=True)

In [19]:
sv_train_0802_data = []
with open('C:/hienlt/treesitter/dataset/SVEN/0802.train.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        sv_train_0802_data.append(record)
sv_train_0802_df = pd.DataFrame(sv_train_0802_data)
sv_train_0802_df.info()

sv_valid_0802_data = []
with open('C:/hienlt/treesitter/dataset/SVEN/0802.valid.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        sv_valid_0802_data.append(record)
sv_valid_0802_df = pd.DataFrame(sv_valid_0802_data)
sv_valid_0802_df.info()


sv_test_0802_data = []
with open('C:/hienlt/treesitter/dataset/SVEN/0802.test.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        sv_test_0802_data.append(record)
sv_test_0802_df = pd.DataFrame(sv_test_0802_data)
sv_test_0802_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      486 non-null    object
 1   target    486 non-null    int64
 2   vul_type  486 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      122 non-null    object
 1   target    122 non-null    int64
 2   vul_type  122 non-null    object
dtypes: int64(1), object(2)
memory usage: 3.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   func      152 non-null    object
 1   target    152 non-null    int64
 2   vul_type  152 non-null    object
dtypes: int64(1), object(2)
memory usage: 3.7+ KB

In [24]:
for index, row in sv_train_0802_df.iterrows():
    sv_train_0802_df.at[index, 'func'] = remove_comments_python(row['func'])
    sv_train_0802_df.at[index, 'vul_type'] = int(row['vul_type'].split('-')[-1][1:])

for index, row in sv_valid_0802_df.iterrows():
    sv_valid_0802_df.at[index, 'func'] = remove_comments_python(row['func'])
    sv_valid_0802_df.at[index, 'vul_type'] = int(row['vul_type'].split('-')[-1][1:])
    
for index, row in sv_test_0802_df.iterrows():
    sv_test_0802_df.at[index, 'func'] = remove_comments_python(row['func'])
    sv_test_0802_df.at[index, 'vul_type'] = int(row['vul_type'].split('-')[-1][1:])

In [25]:
sv_train_moe_0802 = pd.DataFrame({
    'code': sv_train_0802_df['func'],
    'vuln': sv_train_0802_df['target'],
    'cwe': sv_train_0802_df['vul_type'],
    'language': 'Python'
})

sv_valid_moe_0802 = pd.DataFrame({
    'code': sv_valid_0802_df['func'],
    'vuln': sv_valid_0802_df['target'],
    'cwe': sv_valid_0802_df['vul_type'],
    'language': 'Python'
})

sv_test_moe_0802 = pd.DataFrame({
    'code': sv_test_0802_df['func'],
    'vuln': sv_test_0802_df['target'],
    'cwe': sv_test_0802_df['vul_type'],
    'language': 'Python'
})
sv_train_moe_0802.info()
sv_valid_moe_0802.info()
sv_test_moe_0802.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      486 non-null    object
 1   vuln      486 non-null    int64
 2   cwe       486 non-null    object
 3   language  486 non-null    object
dtypes: int64(1), object(3)
memory usage: 15.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      122 non-null    object
 1   vuln      122 non-null    int64
 2   cwe       122 non-null    object
 3   language  122 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      152 non-null    object
 1   vuln      152 non-null    int64
 2   cwe       152 non-null    object
 3   language  152 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.9+ KB

In [26]:
sv_train_moe_0802.head()

                                                code  vuln cwe language
0      @property\n    async def html_content(self...     1  79   Python
1  def manipulate_reservation_action(request: Htt...     1  79   Python
2  @hook.command(adminonly=True)\ndef openPoll(qu...     1  89   Python
3      def _get_vdisk_attributes(self, vdisk_name...     1  78   Python
4      def get_requested_day(self, date):\n\n    ...     0  89   Python

In [27]:
sv_train_moe_0802.to_json("./dataset/MoE/sven_train_moe_0802.jsonl", orient="records", lines=True)
sv_valid_moe_0802.to_json("./dataset/MoE/sven_valid_moe_0802.jsonl", orient="records", lines=True)
sv_test_moe_0802.to_json("./dataset/MoE/sven_test_moe_0802.jsonl", orient="records", lines=True)

In [30]:
pr_train_moe_data = []
with open('C:/hienlt/treesitter/dataset/MVD/primevul_train_raw_nocmt.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_train_moe_data.append(record)     
pr_train_moe_df = pd.DataFrame(pr_train_moe_data)
pr_train_moe_df.info()

pr_val_moe_data = []
with open('C:/hienlt/treesitter/dataset/MVD/primevul_val_noundervaltest.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_val_moe_data.append(record)     
pr_val_moe_df = pd.DataFrame(pr_val_moe_data)
pr_val_moe_df.info()


pr_test_moe_data = []
with open('C:/hienlt/treesitter/dataset/MVD/primevul_test_noundervaltest.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_test_moe_data.append(record)     
pr_test_moe_df = pd.DataFrame(pr_test_moe_data)
pr_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175797 entries, 0 to 175796
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      175797 non-null  object
 1   vuln      175797 non-null  int64
 2   cwe       175797 non-null  int64
 3   language  175797 non-null  object
dtypes: int64(2), object(2)
memory usage: 5.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23948 entries, 0 to 23947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      23948 non-null  object
 1   vuln      23948 non-null  int64
 2   cwe       23948 non-null  int64
 3   language  23948 non-null  object
dtypes: int64(2), object(2)
memory usage: 748.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24788 entries, 0 to 24787
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24788 non-null  object
 1   vuln      24788 non-null  int64
 2   cwe       24788 non-null  int64
 3   language  24788 non-null  object
dtypes: int64(2), object(2)
memory usage: 774.8+ KB

In [34]:
pr_train_label_1 = pr_train_moe_df[pr_train_moe_df['vuln'] == 1]
pr_train_label_0 = pr_train_moe_df[pr_train_moe_df['vuln'] == 0].sample(n=len(pr_train_label_1), random_state=42).reset_index(drop=True)
pr_val_label_1 = pr_val_moe_df[pr_val_moe_df['vuln'] == 1]
pr_val_label_0 = pr_val_moe_df[pr_val_moe_df['vuln'] == 0].sample(n=len(pr_val_label_1), random_state=42).reset_index(drop=True)
pr_test_label_1 = pr_test_moe_df[pr_test_moe_df['vuln'] == 1]
pr_test_label_0 = pr_test_moe_df[pr_test_moe_df['vuln'] == 0].sample(n=len(pr_test_label_1), random_state=42).reset_index(drop=True)

In [35]:
pr_train_under = pd.concat([pr_train_label_1, pr_train_label_0], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_val_under = pd.concat([pr_val_label_1, pr_val_label_0], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_test_under = pd.concat([pr_test_label_1, pr_test_label_0], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_train_under.info()
pr_val_under.info()
pr_test_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9724 entries, 0 to 9723
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9724 non-null   object
 1   vuln      9724 non-null   int64
 2   cwe       9724 non-null   int64
 3   language  9724 non-null   object
dtypes: int64(2), object(2)
memory usage: 304.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1186 non-null   object
 1   vuln      1186 non-null   int64
 2   cwe       1186 non-null   int64
 3   language  1186 non-null   object
dtypes: int64(2), object(2)
memory usage: 37.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1098 entries, 0 to 1097
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1098 non-null   object
 1   vuln      1098 non-null   int64
 2   cwe       1098 non-null   int64
 3   language  1098 non-null   object
dtypes: int64(2), object(2)
memory usage: 34.4+ KB

In [36]:
pr_sv_train_full_nounder = pd.concat([pr_train_moe_df, sv_train_moe_0802], ignore_index=True)
pr_sv_val_full_nounder = pd.concat([pr_val_moe_df, sv_valid_moe_0802], ignore_index=True)
pr_sv_test_full_nounder = pd.concat([pr_test_moe_df, sv_test_moe_0802], ignore_index=True)
pr_sv_train_full_nounder.info()
pr_sv_val_full_nounder.info()
pr_sv_test_full_nounder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176283 entries, 0 to 176282
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      176283 non-null  object
 1   vuln      176283 non-null  int64
 2   cwe       176283 non-null  object
 3   language  176283 non-null  object
dtypes: int64(1), object(3)
memory usage: 5.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24070 entries, 0 to 24069
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24070 non-null  object
 1   vuln      24070 non-null  int64
 2   cwe       24070 non-null  object
 3   language  24070 non-null  object
dtypes: int64(1), object(3)
memory usage: 752.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24940 entries, 0 to 24939
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24940 non-null  object
 1   vuln      24940 non-null  int64
 2   cwe       24940 non-null  object
 3   language  24940 non-null  object
dtypes: int64(1), object(3)
memory usage: 779.5+ KB

In [37]:
pr_sv_train_full_under = pd.concat([pr_train_under, sv_train_moe_0802], ignore_index=True)
pr_sv_val_full_under = pd.concat([pr_val_under, sv_valid_moe_0802], ignore_index=True)
pr_sv_test_full_under = pd.concat([pr_test_under, sv_test_moe_0802], ignore_index=True)
pr_sv_train_full_under.info()
pr_sv_val_full_under.info()
pr_sv_test_full_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10210 entries, 0 to 10209
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      10210 non-null  object
 1   vuln      10210 non-null  int64
 2   cwe       10210 non-null  object
 3   language  10210 non-null  object
dtypes: int64(1), object(3)
memory usage: 319.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1308 entries, 0 to 1307
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1308 non-null   object
 1   vuln      1308 non-null   int64
 2   cwe       1308 non-null   object
 3   language  1308 non-null   object
dtypes: int64(1), object(3)
memory usage: 41.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1250 non-null   object
 1   vuln      1250 non-null   int64
 2   cwe       1250 non-null   object
 3   language  1250 non-null   object
dtypes: int64(1), object(3)
memory usage: 39.2+ KB

In [38]:
pr_sv_train_full_nounder.to_json("./dataset/MoE/primevul_sven_train_full_nounder.jsonl", orient="records", lines=True)
pr_sv_val_full_nounder.to_json("./dataset/MoE/primevul_sven_val_full_nounder.jsonl", orient="records", lines=True)
pr_sv_test_full_nounder.to_json("./dataset/MoE/primevul_sven_test_full_nounder.jsonl", orient="records", lines=True)
pr_sv_train_full_under.to_json("./dataset/MoE/primevul_sven_train_full_under.jsonl", orient="records", lines=True)
pr_sv_val_full_under.to_json("./dataset/MoE/primevul_sven_val_full_under.jsonl", orient="records", lines=True)
pr_sv_test_full_under.to_json("./dataset/MoE/primevul_sven_test_full_under.jsonl", orient="records", lines=True)

In [3]:
pr_sv_train_full_nounder_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_train_full_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train_full_nounder_data.append(record)
pr_sv_train_full_nounder_df = pd.DataFrame(pr_sv_train_full_nounder_data)
pr_sv_val_full_nounder_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_val_full_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_val_full_nounder_data.append(record)
pr_sv_val_full_nounder_df = pd.DataFrame(pr_sv_val_full_nounder_data)
pr_sv_test_full_nounder_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_test_full_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test_full_nounder_data.append(record)
pr_sv_test_full_nounder_df = pd.DataFrame(pr_sv_test_full_nounder_data)
pr_sv_train_full_under_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_train_full_under.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train_full_under_data.append(record)
pr_sv_train_full_under_df = pd.DataFrame(pr_sv_train_full_under_data)
pr_sv_val_full_under_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_val_full_under.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_val_full_under_data.append(record)
pr_sv_val_full_under_df = pd.DataFrame(pr_sv_val_full_under_data)
pr_sv_test_full_under_data = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_test_full_under.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test_full_under_data.append(record)  
pr_sv_test_full_under_df = pd.DataFrame(pr_sv_test_full_under_data)
pr_sv_train_full_nounder_df.info()
# pr_sv_val_full_nounder_df.info()
pr_sv_test_full_nounder_df.info()
# pr_sv_train_full_under_df.info()
# pr_sv_val_full_under_df.info()
# pr_sv_test_full_under_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176283 entries, 0 to 176282
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      176283 non-null  object
 1   vuln      176283 non-null  int64
 2   cwe       176283 non-null  int64
 3   language  176283 non-null  object
dtypes: int64(2), object(2)
memory usage: 5.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24940 entries, 0 to 24939
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24940 non-null  object
 1   vuln      24940 non-null  int64
 2   cwe       24940 non-null  int64
 3   language  24940 non-null  object
dtypes: int64(2), object(2)
memory usage: 779.5+ KB

In [4]:
pr_train_full_nounder = pr_sv_train_full_nounder_df[pr_sv_train_full_nounder_df['language'] == 'CCPP']
pr_val_full_nounder = pr_sv_val_full_nounder_df[pr_sv_val_full_nounder_df['language'] == 'CCPP']
pr_test_full_nounder = pr_sv_test_full_nounder_df[pr_sv_test_full_nounder_df['language'] == 'CCPP']
pr_train_full_under = pr_sv_train_full_under_df[pr_sv_train_full_under_df['language'] == 'CCPP']
pr_val_full_under = pr_sv_val_full_under_df[pr_sv_val_full_under_df['language'] == 'CCPP']
pr_test_full_under = pr_sv_test_full_under_df[pr_sv_test_full_under_df['language'] == 'CCPP']
pr_train_full_nounder.info()
pr_val_full_nounder.info()
pr_test_full_nounder.info()
pr_train_full_under.info()
pr_val_full_under.info()
pr_test_full_under.info()
pr_train_full_nounder.to_csv("./dataset/MVD/primevul_train_full_nounder.csv", index=False)
pr_val_full_nounder.to_csv("./dataset/MVD/primevul_val_full_nounder.csv", index=False)
pr_test_full_nounder.to_csv("./dataset/MVD/primevul_test_full_nounder.csv", index=False)
pr_train_full_under.to_csv("./dataset/MVD/primevul_train_full_under.csv", index=False)
pr_val_full_under.to_csv("./dataset/MVD/primevul_val_full_under.csv", index=False)
pr_test_full_under.to_csv("./dataset/MVD/primevul_test_full_under.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 175797 entries, 0 to 175796
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      175797 non-null  object
 1   vuln      175797 non-null  int64
 2   cwe       175797 non-null  int64
 3   language  175797 non-null  object
dtypes: int64(2), object(2)
memory usage: 6.7+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 23948 entries, 0 to 23947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      23948 non-null  object
 1   vuln      23948 non-null  int64
 2   cwe       23948 non-null  int64
 3   language  23948 non-null  object
dtypes: int64(2), object(2)
memory usage: 935.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 24788 entries, 0 to 24787
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24788 non-null  object
 1   vuln      24788 non-null  int64
 2   cwe       24788 non-null  int64
 3   language  24788 non-null  object
dtypes: int64(2), object(2)
memory usage: 968.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 9724 entries, 0 to 9723
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9724 non-null   object
 1   vuln      9724 non-null   int64
 2   cwe       9724 non-null   int64
 3   language  9724 non-null   object
dtypes: int64(2), object(2)
memory usage: 379.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1186 entries, 0 to 1185
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1186 non-null   object
 1   vuln      1186 non-null   int64
 2   cwe       1186 non-null   int64
 3   language  1186 non-null   object
dtypes: int64(2), object(2)
memory usage: 46.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1098 entries, 0 to 1097
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1098 non-null   object
 1   vuln      1098 non-null   int64
 2   cwe       1098 non-null   int64
 3   language  1098 non-null   object
dtypes: int64(2), object(2)
memory usage: 42.9+ KB

In [2]:
pr_train_full_nounder = pd.read_csv("./dataset/MVD/primevul_train_full_nounder.csv")
pr_val_full_nounder = pd.read_csv("./dataset/MVD/primevul_val_full_nounder.csv")
pr_test_full_nounder = pd.read_csv("./dataset/MVD/primevul_test_full_nounder.csv")

pr_train_full_nounder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175797 entries, 0 to 175796
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      175797 non-null  object
 1   vuln      175797 non-null  int64
 2   cwe       175797 non-null  int64
 3   language  175797 non-null  object
dtypes: int64(2), object(2)
memory usage: 5.4+ MB

In [3]:
pr_train_full_nounder['cwe'].unique()

array([ 310,  119,  200,   20,  416,  835,  189,  347,  354,  190,  125,
        399,  264,  209,   59,   78,  388,  704,  476,   22,  254,   17,
        787,  772,  362,  345,  311,  284,  400,  369,  327,  320,  415,
        331,   16,  703,   94,  255,   89,  287,   19,   79,  401,  862,
        269,  834,  617,  770,  755,  129,  241,  404,  191,  732,  532,
         74,  426,  754,  674,  824,   77,  295,  693,  352,  290,  285,
        665,  120,  601,  611,  522,  361, 1021,  668,  664,  172,  682,
        252,  502,  918,  909,  134,   -1,   -2,  697,  639,  843,  122,
        707,   61,  552,  276,  667,  863,  681,  294,  763,  417,  281,
        203,  212,  131,  346,  193,  273,  116,  307,  349,   93,  908,
        823,  113,  672,   88,  457,  798,  670,  121,  326,  444,  613,
        288])

In [22]:
cwe_freq_train = {}
for cwe, vuln in zip(pr_train_full_nounder['cwe'], pr_train_full_nounder['vuln']):
    if cwe in cwe_freq_train and vuln == 1:
        cwe_freq_train[cwe] += 1
    elif vuln == 1 and cwe not in cwe_freq_train:
        cwe_freq_train[cwe] = 1
cwe_freq_train_df = pd.DataFrame(list(cwe_freq_train.items()), columns=['cwe', 'frequency'])
cwe_freq_train_df = cwe_freq_train_df.sort_values(by='frequency', ascending=False).reset_index(drop=True)
cwe_freq_train_df.info()

cwe_freq_val = {}
for cwe, vuln in zip(pr_val_full_nounder['cwe'], pr_val_full_nounder['vuln']):
    if cwe in cwe_freq_val and vuln == 1:
        cwe_freq_val[cwe] += 1
    elif vuln == 1 and cwe not in cwe_freq_val:
        cwe_freq_val[cwe] = 1
cwe_freq_val_df = pd.DataFrame(list(cwe_freq_val.items()), columns=['cwe', 'frequency'])
cwe_freq_val_df = cwe_freq_val_df.sort_values(by='frequency', ascending=False).reset_index(drop=True)
cwe_freq_val_df.info()

cwe_freq_test = {}
for cwe, vuln in zip(pr_test_full_nounder['cwe'], pr_test_full_nounder['vuln']):
    if cwe in cwe_freq_test and vuln == 1:
        cwe_freq_test[cwe] += 1
    elif vuln == 1 and cwe not in cwe_freq_test:
        cwe_freq_test[cwe] = 1
cwe_freq_test_df = pd.DataFrame(list(cwe_freq_test.items()), columns=['cwe', 'frequency'])
cwe_freq_test_df = cwe_freq_test_df.sort_values(by='frequency', ascending=False).reset_index(drop=True)
cwe_freq_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cwe        119 non-null    int64
 1   frequency  119 non-null    int64
dtypes: int64(2)
memory usage: 2.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cwe        70 non-null     int64
 1   frequency  70 non-null     int64
dtypes: int64(2)
memory usage: 1.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cwe        69 non-null     int64
 1   frequency  69 non-null     int64
dtypes: int64(2)
memory usage: 1.2 KB

In [26]:
cwe_freq_df = pd.DataFrame(columns=['cwe', 'train_freq', 'val_freq', 'test_freq', 'total_freq'])
cwe_freq = {}
cwes = set(cwe_freq_train_df['cwe']).union(set(cwe_freq_val_df['cwe'])).union(set(cwe_freq_test_df['cwe']))
for cwe in cwes:
    train_freq = cwe_freq_train.get(cwe, 0)
    val_freq = cwe_freq_val.get(cwe, 0)
    test_freq = cwe_freq_test.get(cwe, 0)
    total_freq = train_freq + val_freq + test_freq
    cwe_freq[cwe] = total_freq

cwe_freq

{522: 5,
 16: 1,
 17: 15,
 19: 14,
 20: 471,
 532: 5,
 22: 46,
 552: 2,
 565: 1,
 59: 25,
 61: 8,
 74: 11,
 77: 9,
 78: 27,
 79: 30,
 88: 4,
 89: 6,
 601: 5,
 91: 2,
 93: 2,
 94: 19,
 611: 3,
 613: 1,
 617: 60,
 113: 1,
 116: 1,
 119: 719,
 120: 59,
 121: 2,
 122: 13,
 125: 677,
 639: 1,
 129: 6,
 131: 2,
 134: 7,
 662: 1,
 664: 1,
 665: 21,
 667: 3,
 668: 5,
 670: 1,
 672: 3,
 674: 13,
 681: 6,
 682: 3,
 172: 2,
 693: 2,
 697: 3,
 189: 179,
 190: 228,
 703: 257,
 704: 13,
 191: 11,
 193: 7,
 707: 1,
 706: 1,
 200: 321,
 203: 7,
 209: 1,
 212: 2,
 732: 5,
 241: 4,
 754: 16,
 755: 13,
 763: 8,
 252: 10,
 254: 20,
 255: 2,
 770: 23,
 772: 89,
 264: 175,
 269: 27,
 273: 1,
 787: 504,
 276: 8,
 275: 1,
 281: 1,
 284: 68,
 285: 4,
 798: 1,
 287: 17,
 288: 1,
 290: 1,
 294: 5,
 295: 13,
 307: 2,
 310: 70,
 311: 1,
 824: 11,
 823: 2,
 320: 8,
 834: 15,
 835: 62,
 326: 5,
 327: 9,
 843: 9,
 331: 3,
 345: 9,
 346: 1,
 347: 6,
 349: 1,
 862: 9,
 863: 5,
 352: 2,
 354: 8,
 361: 1,
 362: 100,
 369: 138,
 388: 7,
 908: 7,
 909: 7,
 399: 196,
 400: 39,
 401: 117,
 404: 4,
 918: 2,
 924: 2,
 415: 95,
 416: 295,
 417: 1,
 426: 1,
 434: 3,
 444: 3,
 457: 1,
 459: 1,
 476: 373,
 502: 3,
 1021: 1}

In [27]:
cwe_freq_df['cwe'] = cwe_freq.keys()
cwe_freq_df['total_freq'] = cwe_freq.values()
cwe_freq_df = cwe_freq_df.sort_values(by='total_freq', ascending=False).reset_index(drop=True)
cwe_freq_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cwe         128 non-null    int64
 1   train_freq  0 non-null      object
 2   val_freq    0 non-null      object
 3   test_freq   0 non-null      object
 4   total_freq  128 non-null    int64
dtypes: int64(2), object(3)
memory usage: 5.1+ KB

In [28]:
for index, row in cwe_freq_df.iterrows():
    cwe = row['cwe']
    cwe_freq_df.at[index, 'train_freq'] = cwe_freq_train.get(cwe, 0)
    cwe_freq_df.at[index, 'val_freq'] = cwe_freq_val.get(cwe, 0)
    cwe_freq_df.at[index, 'test_freq'] = cwe_freq_test.get(cwe, 0)
cwe_freq_df.info()
cwe_freq_df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cwe         128 non-null    int64
 1   train_freq  128 non-null    object
 2   val_freq    128 non-null    object
 3   test_freq   128 non-null    object
 4   total_freq  128 non-null    int64
dtypes: int64(2), object(3)
memory usage: 5.1+ KB

    cwe train_freq val_freq test_freq  total_freq
0   119        679       19        21         719
1   125        538       80        59         677
2   787        318       96        90         504
3    20        442       11        18         471
4   476        272       54        47         373
5   200        285       20        16         321
6   416        228       28        39         295
7   703        155       47        55         257
8   190        184       27        17         228
9   399        189        4         3         196
10  189        166        7         6         179
11  264        171        2         2         175
12  369         79       38        21         138
13  401         94       14         9         117
14  362         83        7        10         100
15  415         75        8        12          95
16  772         82        3         4          89
17  310         63        5         2          70
18  284         58        5         5          68
19  835         50        7         5          62

In [29]:
cwe_freq_df.to_csv("./dataset/MVD/cwe_frequency_full_nounder.csv", index=False)

In [33]:
cwe_freq_df_threshold_39 = cwe_freq_df[cwe_freq_df['total_freq'] >= 39]
cwe_freq_df_threshold_39.head(25)
cwes_threshold_39 = cwe_freq_df_threshold_39['cwe'].tolist()

In [20]:
cwe_freq_df.to_csv("./dataset/MVD/cwe_frequency_full_nounder.csv", index=False)

In [21]:
threshold_2 = 20
threshold_1 = 10
threshold_3 = 30

In [34]:
primevul_train_df_39 = pr_train_full_nounder.copy()
primevul_train_df_39 = primevul_train_df_39[primevul_train_df_39['cwe'].isin(cwes_threshold_39)].reset_index(drop=True)
primevul_val_df_39 = pr_val_full_nounder.copy()
primevul_val_df_39 = primevul_val_df_39[primevul_val_df_39['cwe'].isin(cwes_threshold_39)].reset_index(drop=True)
primevul_test_df_39 = pr_test_full_nounder.copy()
primevul_test_df_39 = primevul_test_df_39[primevul_test_df_39['cwe'].isin(cwes_threshold_39)].reset_index(drop=True)
primevul_train_df_39.info()
primevul_val_df_39.info()
primevul_test_df_39.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136051 entries, 0 to 136050
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      136051 non-null  object
 1   vuln      136051 non-null  int64
 2   cwe       136051 non-null  int64
 3   language  136051 non-null  object
dtypes: int64(2), object(2)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17224 entries, 0 to 17223
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      17224 non-null  object
 1   vuln      17224 non-null  int64
 2   cwe       17224 non-null  int64
 3   language  17224 non-null  object
dtypes: int64(2), object(2)
memory usage: 538.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18141 entries, 0 to 18140
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      18141 non-null  object
 1   vuln      18141 non-null  int64
 2   cwe       18141 non-null  int64
 3   language  18141 non-null  object
dtypes: int64(2), object(2)
memory usage: 567.0+ KB

In [41]:
primevul_train_df_39.to_csv("./dataset/MVD/primevul_train_threshold_39.csv", index=False)
primevul_val_df_39.to_csv("./dataset/MVD/primevul_val_threshold_39.csv", index=False)
primevul_test_df_39.to_csv("./dataset/MVD/primevul_test_threshold_39.csv", index=False)

In [35]:
pr_train_under_39 = primevul_train_df_39[primevul_train_df_39['vuln'] == 1]
pr_train_under_39 = pd.concat([pr_train_under_39, primevul_train_df_39[primevul_train_df_39['vuln'] == 0].sample(n=len(pr_train_under_39), random_state=42).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_val_under_39 = primevul_val_df_39[primevul_val_df_39['vuln'] == 1]
pr_val_under_39 = pd.concat([pr_val_under_39, primevul_val_df_39[primevul_val_df_39['vuln'] == 0].sample(n=len(pr_val_under_39), random_state=42).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_test_under_39 = primevul_test_df_39[primevul_test_df_39['vuln'] == 1]
pr_test_under_39 = pd.concat([pr_test_under_39, primevul_test_df_39[primevul_test_df_39['vuln'] == 0].sample(n=len(pr_test_under_39), random_state=42).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_train_under_39.info()
pr_val_under_39.info()
pr_test_under_39.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8710 entries, 0 to 8709
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      8710 non-null   object
 1   vuln      8710 non-null   int64
 2   cwe       8710 non-null   int64
 3   language  8710 non-null   object
dtypes: int64(2), object(2)
memory usage: 272.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1022 entries, 0 to 1021
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1022 non-null   object
 1   vuln      1022 non-null   int64
 2   cwe       1022 non-null   int64
 3   language  1022 non-null   object
dtypes: int64(2), object(2)
memory usage: 32.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 944 entries, 0 to 943
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      944 non-null    object
 1   vuln      944 non-null    int64
 2   cwe       944 non-null    int64
 3   language  944 non-null    object
dtypes: int64(2), object(2)
memory usage: 29.6+ KB

In [36]:
sven_train_moe = []
with open('C:/hienlt/treesitter/dataset/MoE/sven_train_moe_0802.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        sven_train_moe.append(record)
sven_train_moe_df = pd.DataFrame(sven_train_moe)
sven_train_moe_df.info()

sven_valid_moe = []
with open('C:/hienlt/treesitter/dataset/MoE/sven_valid_moe_0802.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        sven_valid_moe.append(record)
sven_valid_moe_df = pd.DataFrame(sven_valid_moe)
sven_valid_moe_df.info()


sven_test_moe = []
with open('C:/hienlt/treesitter/dataset/MoE/sven_test_moe_0802.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        sven_test_moe.append(record)
sven_test_moe_df = pd.DataFrame(sven_test_moe)
sven_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      486 non-null    object
 1   vuln      486 non-null    int64
 2   cwe       486 non-null    int64
 3   language  486 non-null    object
dtypes: int64(2), object(2)
memory usage: 15.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      122 non-null    object
 1   vuln      122 non-null    int64
 2   cwe       122 non-null    int64
 3   language  122 non-null    object
dtypes: int64(2), object(2)
memory usage: 3.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      152 non-null    object
 1   vuln      152 non-null    int64
 2   cwe       152 non-null    int64
 3   language  152 non-null    object
dtypes: int64(2), object(2)
memory usage: 4.9+ KB

In [37]:
pr_sv_train_full_nounder_39 = pd.concat([primevul_train_df_39, sven_train_moe_df], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_val_full_nounder_39 = pd.concat([primevul_val_df_39, sven_valid_moe_df], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_test_full_nounder_39 = pd.concat([primevul_test_df_39, sven_test_moe_df], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_train_full_nounder_39.info()
pr_sv_val_full_nounder_39.info()
pr_sv_test_full_nounder_39.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136537 entries, 0 to 136536
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      136537 non-null  object
 1   vuln      136537 non-null  int64
 2   cwe       136537 non-null  int64
 3   language  136537 non-null  object
dtypes: int64(2), object(2)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17346 entries, 0 to 17345
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      17346 non-null  object
 1   vuln      17346 non-null  int64
 2   cwe       17346 non-null  int64
 3   language  17346 non-null  object
dtypes: int64(2), object(2)
memory usage: 542.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18293 entries, 0 to 18292
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      18293 non-null  object
 1   vuln      18293 non-null  int64
 2   cwe       18293 non-null  int64
 3   language  18293 non-null  object
dtypes: int64(2), object(2)
memory usage: 571.8+ KB

In [38]:
pr_sv_train_full_under_39 = pd.concat([pr_train_under_39, sven_train_moe_df], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_val_full_under_39 = pd.concat([pr_val_under_39, sven_valid_moe_df], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_test_full_under_39 = pd.concat([pr_test_under_39, sven_test_moe_df], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
pr_sv_train_full_under_39.info()
pr_sv_val_full_under_39.info()
pr_sv_test_full_under_39.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9196 entries, 0 to 9195
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9196 non-null   object
 1   vuln      9196 non-null   int64
 2   cwe       9196 non-null   int64
 3   language  9196 non-null   object
dtypes: int64(2), object(2)
memory usage: 287.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1144 non-null   object
 1   vuln      1144 non-null   int64
 2   cwe       1144 non-null   int64
 3   language  1144 non-null   object
dtypes: int64(2), object(2)
memory usage: 35.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1096 non-null   object
 1   vuln      1096 non-null   int64
 2   cwe       1096 non-null   int64
 3   language  1096 non-null   object
dtypes: int64(2), object(2)
memory usage: 34.4+ KB

In [39]:
pr_sv_train_full_nounder_39.to_json("./dataset/MoE/primevul_sven_train_full_nounder_39.jsonl", orient="records", lines=True)
pr_sv_val_full_nounder_39.to_json("./dataset/MoE/primevul_sven_val_full_nounder_39.jsonl", orient="records", lines=True)
pr_sv_test_full_nounder_39.to_json("./dataset/MoE/primevul_sven_test_full_nounder_39.jsonl", orient="records", lines=True)
pr_sv_train_full_under_39.to_json("./dataset/MoE/primevul_sven_train_full_under_39.jsonl", orient="records", lines=True)
pr_sv_val_full_under_39.to_json("./dataset/MoE/primevul_sven_val_full_under_39.jsonl", orient="records", lines=True)
pr_sv_test_full_under_39.to_json("./dataset/MoE/primevul_sven_test_full_under_39.jsonl", orient="records", lines=True)

In [40]:
pr_train_under_39.to_csv("./dataset/MVD/primevul_train_under_39.csv", index=False)

In [2]:
import json
import pandas as pd
pr_sv_train_moe = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_train_full_under_39.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train_moe.append(record)
pr_sv_train_moe_df = pd.DataFrame(pr_sv_train_moe)
pr_sv_train_moe_df.info()

pr_sv_valid_moe = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_val_full_under_39.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_valid_moe.append(record)
pr_sv_valid_moe_df = pd.DataFrame(pr_sv_valid_moe)
pr_sv_valid_moe_df.info()


pr_sv_test_moe = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_test_full_under_39.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test_moe.append(record)
pr_sv_test_moe_df = pd.DataFrame(pr_sv_test_moe)
pr_sv_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9196 entries, 0 to 9195
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9196 non-null   object
 1   vuln      9196 non-null   int64
 2   cwe       9196 non-null   int64
 3   language  9196 non-null   object
dtypes: int64(2), object(2)
memory usage: 287.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1144 non-null   object
 1   vuln      1144 non-null   int64
 2   cwe       1144 non-null   int64
 3   language  1144 non-null   object
dtypes: int64(2), object(2)
memory usage: 35.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1096 non-null   object
 1   vuln      1096 non-null   int64
 2   cwe       1096 non-null   int64
 3   language  1096 non-null   object
dtypes: int64(2), object(2)
memory usage: 34.4+ KB

In [4]:
pr_under_train_39 = pr_sv_train_moe_df[pr_sv_train_moe_df['language'] == 'CCPP']
pr_under_val_39 = pr_sv_valid_moe_df[pr_sv_valid_moe_df['language'] == 'CCPP']
pr_under_test_39 = pr_sv_test_moe_df[pr_sv_test_moe_df['language'] == 'CCPP']
pr_under_train_39.info()
pr_under_val_39.info()
pr_under_test_39.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8710 entries, 0 to 9195
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      8710 non-null   object
 1   vuln      8710 non-null   int64
 2   cwe       8710 non-null   int64
 3   language  8710 non-null   object
dtypes: int64(2), object(2)
memory usage: 340.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1022 entries, 0 to 1142
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1022 non-null   object
 1   vuln      1022 non-null   int64
 2   cwe       1022 non-null   int64
 3   language  1022 non-null   object
dtypes: int64(2), object(2)
memory usage: 39.9+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 944 entries, 0 to 1095
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      944 non-null    object
 1   vuln      944 non-null    int64
 2   cwe       944 non-null    int64
 3   language  944 non-null    object
dtypes: int64(2), object(2)
memory usage: 36.9+ KB

In [6]:
pr_under_train_39.to_csv("./dataset/MVD/primevul_train_under_39.csv", index=False)
pr_under_val_39.to_csv("./dataset/MVD/primevul_val_under_39.csv", index=False)
pr_under_test_39.to_csv("./dataset/MVD/primevul_test_under_39.csv", index=False)

In [3]:
import json
import pandas as pd

pr_sv_train = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_train_full_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train.append(record)

df_pr_sv_train = pd.DataFrame(pr_sv_train)

pr_sv_val = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_val_full_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_val.append(record)

df_pr_sv_val = pd.DataFrame(pr_sv_val)

pr_sv_test = []
with open('C:/hienlt/treesitter/dataset/MoE/primevul_sven_test_full_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test.append(record)   
df_pr_sv_test = pd.DataFrame(pr_sv_test)

In [9]:
df_pr_sv_train.info()
df_pr_sv_val.info()
df_pr_sv_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176283 entries, 0 to 176282
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      176283 non-null  object
 1   vuln      176283 non-null  int64
 2   cwe       176283 non-null  int64
 3   language  176283 non-null  object
dtypes: int64(2), object(2)
memory usage: 5.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24070 entries, 0 to 24069
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24070 non-null  object
 1   vuln      24070 non-null  int64
 2   cwe       24070 non-null  int64
 3   language  24070 non-null  object
dtypes: int64(2), object(2)
memory usage: 752.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24940 entries, 0 to 24939
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24940 non-null  object
 1   vuln      24940 non-null  int64
 2   cwe       24940 non-null  int64
 3   language  24940 non-null  object
dtypes: int64(2), object(2)
memory usage: 779.5+ KB

In [10]:
df_pr_train = df_pr_sv_train[df_pr_sv_train['language'] == 'CCPP']
df_pr_val = df_pr_sv_val[df_pr_sv_val['language'] == 'CCPP']
df_pr_test = df_pr_sv_test[df_pr_sv_test['language'] == 'CCPP']
df_pr_train.info()
df_pr_val.info()
df_pr_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175797 entries, 0 to 175796
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      175797 non-null  object
 1   vuln      175797 non-null  int64
 2   cwe       175797 non-null  int64
 3   language  175797 non-null  object
dtypes: int64(2), object(2)
memory usage: 6.7+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 23948 entries, 0 to 23947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      23948 non-null  object
 1   vuln      23948 non-null  int64
 2   cwe       23948 non-null  int64
 3   language  23948 non-null  object
dtypes: int64(2), object(2)
memory usage: 935.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 24788 entries, 0 to 24787
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      24788 non-null  object
 1   vuln      24788 non-null  int64
 2   cwe       24788 non-null  int64
 3   language  24788 non-null  object
dtypes: int64(2), object(2)
memory usage: 968.3+ KB

In [4]:
df_sv_train = df_pr_sv_train[df_pr_sv_train['language'] == 'Python']
df_sv_val = df_pr_sv_val[df_pr_sv_val['language'] == 'Python']
df_sv_test = df_pr_sv_test[df_pr_sv_test['language'] == 'Python']
df_sv_train.info()
df_sv_val.info()
df_sv_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 486 entries, 175797 to 176282
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      486 non-null    object
 1   vuln      486 non-null    int64
 2   cwe       486 non-null    int64
 3   language  486 non-null    object
dtypes: int64(2), object(2)
memory usage: 19.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 23948 to 24069
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      122 non-null    object
 1   vuln      122 non-null    int64
 2   cwe       122 non-null    int64
 3   language  122 non-null    object
dtypes: int64(2), object(2)
memory usage: 4.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 24788 to 24939
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      152 non-null    object
 1   vuln      152 non-null    int64
 2   cwe       152 non-null    int64
 3   language  152 non-null    object
dtypes: int64(2), object(2)
memory usage: 5.9+ KB

In [11]:
df_pr_full = pd.concat([df_pr_train, df_pr_val, df_pr_test], ignore_index=True)
df_pr_full.sample(frac=1, random_state=45).reset_index(drop=True)
df_pr_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224533 entries, 0 to 224532
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      224533 non-null  object
 1   vuln      224533 non-null  int64
 2   cwe       224533 non-null  int64
 3   language  224533 non-null  object
dtypes: int64(2), object(2)
memory usage: 6.9+ MB

In [12]:
from sklearn.model_selection import train_test_split
df_pr_train, df_pr_temp = train_test_split(df_pr_full, test_size=0.2, random_state=45)
df_pr_val, df_pr_test = train_test_split(df_pr_temp, test_size=0.5, random_state=45, stratify=df_pr_temp['vuln'])
df_pr_train.info()
df_pr_val.info()
df_pr_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 179626 entries, 84768 to 137630
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      179626 non-null  object
 1   vuln      179626 non-null  int64
 2   cwe       179626 non-null  int64
 3   language  179626 non-null  object
dtypes: int64(2), object(2)
memory usage: 6.9+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 22453 entries, 169736 to 109087
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22453 non-null  object
 1   vuln      22453 non-null  int64
 2   cwe       22453 non-null  int64
 3   language  22453 non-null  object
dtypes: int64(2), object(2)
memory usage: 877.1+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 22454 entries, 48442 to 200493
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22454 non-null  object
 1   vuln      22454 non-null  int64
 2   cwe       22454 non-null  int64
 3   language  22454 non-null  object
dtypes: int64(2), object(2)
memory usage: 877.1+ KB

In [25]:
float(len(df_pr_train[df_pr_train['vuln'] == 1]) / len(df_pr_train))

0.026961575718437197

In [13]:
df_pr_train_under = df_pr_train[df_pr_train['vuln'] == 1]
df_pr_train_under = pd.concat([df_pr_train_under, df_pr_train[df_pr_train['vuln'] == 0].sample(n=len(df_pr_train_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
df_pr_val_under = df_pr_val[df_pr_val['vuln'] == 1]
df_pr_val_under = pd.concat([df_pr_val_under, df_pr_val[df_pr_val['vuln'] == 0].sample(n=len(df_pr_val_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
df_pr_test_under = df_pr_test[df_pr_test['vuln'] == 1]
df_pr_test_under = pd.concat([df_pr_test_under, df_pr_test[df_pr_test['vuln'] == 0].sample(n=len(df_pr_test_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
df_pr_train_under.info()
df_pr_val_under.info()
df_pr_test_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9680 entries, 0 to 9679
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9680 non-null   object
 1   vuln      9680 non-null   int64
 2   cwe       9680 non-null   int64
 3   language  9680 non-null   object
dtypes: int64(2), object(2)
memory usage: 302.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1164 entries, 0 to 1163
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1164 non-null   object
 1   vuln      1164 non-null   int64
 2   cwe       1164 non-null   int64
 3   language  1164 non-null   object
dtypes: int64(2), object(2)
memory usage: 36.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1164 entries, 0 to 1163
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1164 non-null   object
 1   vuln      1164 non-null   int64
 2   cwe       1164 non-null   int64
 3   language  1164 non-null   object
dtypes: int64(2), object(2)
memory usage: 36.5+ KB

In [27]:
pr_sv_train_nocmt_under = pd.concat([df_pr_train_under, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_val_nocmt_under = pd.concat([df_pr_val_under, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_test_nocmt_under = pd.concat([df_pr_test_under, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_train_nocmt_under.info()
pr_sv_val_nocmt_under.info()
pr_sv_test_nocmt_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10172 entries, 0 to 10171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      10172 non-null  object
 1   vuln      10172 non-null  int64
 2   cwe       10172 non-null  int64
 3   language  10172 non-null  object
dtypes: int64(2), object(2)
memory usage: 318.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1282 entries, 0 to 1281
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1282 non-null   object
 1   vuln      1282 non-null   int64
 2   cwe       1282 non-null   int64
 3   language  1282 non-null   object
dtypes: int64(2), object(2)
memory usage: 40.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314 entries, 0 to 1313
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1314 non-null   object
 1   vuln      1314 non-null   int64
 2   cwe       1314 non-null   int64
 3   language  1314 non-null   object
dtypes: int64(2), object(2)
memory usage: 41.2+ KB

In [29]:
pr_sv_train_nocmt = pd.concat([df_pr_train, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_val_nocmt = pd.concat([df_pr_val, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_test_nocmt = pd.concat([df_pr_test, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_train_nocmt.info()
pr_sv_val_nocmt.info()
pr_sv_test_nocmt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180112 entries, 0 to 180111
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      180112 non-null  object
 1   vuln      180112 non-null  int64
 2   cwe       180112 non-null  int64
 3   language  180112 non-null  object
dtypes: int64(2), object(2)
memory usage: 5.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22575 entries, 0 to 22574
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22575 non-null  object
 1   vuln      22575 non-null  int64
 2   cwe       22575 non-null  int64
 3   language  22575 non-null  object
dtypes: int64(2), object(2)
memory usage: 705.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22606 entries, 0 to 22605
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22606 non-null  object
 1   vuln      22606 non-null  int64
 2   cwe       22606 non-null  int64
 3   language  22606 non-null  object
dtypes: int64(2), object(2)
memory usage: 706.6+ KB

In [31]:
pr_sv_train_nocmt_under.to_json("./dataset/MoE/pr_sv_no_cmt/under/primevul_sven_train_nocmt_under.jsonl", orient="records", lines=True)
pr_sv_val_nocmt_under.to_json("./dataset/MoE/pr_sv_no_cmt/under/primevul_sven_val_nocmt_under.jsonl", orient="records", lines=True)
pr_sv_test_nocmt_under.to_json("./dataset/MoE/pr_sv_no_cmt/under/primevul_sven_test_nocmt_under.jsonl", orient="records", lines=True)

In [32]:
pr_sv_train_nocmt.to_json("./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_train_nocmt_nounder.jsonl", orient="records", lines=True)
pr_sv_val_nocmt.to_json("./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_val_nocmt_nounder.jsonl", orient="records", lines=True)
pr_sv_test_nocmt.to_json("./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_test_nocmt_nounder.jsonl", orient="records", lines=True)

In [25]:
import json
import pandas as pd
pr_sv_val_nocmt = []
with open('./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_val_nocmt_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_val_nocmt.append(record)
pr_sv_val_nocmt_df = pd.DataFrame(pr_sv_val_nocmt)
pr_sv_val_nocmt_df.info()

pr_sv_test_nocmt = []
with open('./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_test_nocmt_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test_nocmt.append(record)
pr_sv_test_nocmt_df = pd.DataFrame(pr_sv_test_nocmt)
pr_sv_test_nocmt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22575 entries, 0 to 22574
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22575 non-null  object
 1   vuln      22575 non-null  int64
 2   cwe       22575 non-null  int64
 3   language  22575 non-null  object
dtypes: int64(2), object(2)
memory usage: 705.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22606 entries, 0 to 22605
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22606 non-null  object
 1   vuln      22606 non-null  int64
 2   cwe       22606 non-null  int64
 3   language  22606 non-null  object
dtypes: int64(2), object(2)
memory usage: 706.6+ KB

In [26]:
pr_sv_train_nocmt = []
with open('./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_train_nocmt_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train_nocmt.append(record)
pr_sv_train_nocmt_df = pd.DataFrame(pr_sv_train_nocmt)
pr_sv_train_nocmt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180112 entries, 0 to 180111
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      180112 non-null  object
 1   vuln      180112 non-null  int64
 2   cwe       180112 non-null  int64
 3   language  180112 non-null  object
dtypes: int64(2), object(2)
memory usage: 5.5+ MB

In [27]:
sv_val_nocmt = pr_sv_val_nocmt_df[pr_sv_val_nocmt_df['language'] == 'Python']
sv_test_nocmt = pr_sv_test_nocmt_df[pr_sv_test_nocmt_df['language'] == 'Python']
pr_val_nocmt = pr_sv_val_nocmt_df[pr_sv_val_nocmt_df['language'] == 'CCPP']
pr_test_nocmt = pr_sv_test_nocmt_df[pr_sv_test_nocmt_df['language'] == 'CCPP']

In [28]:
sv_train_nocmt = pr_sv_train_nocmt_df[pr_sv_train_nocmt_df['language'] == 'Python']
pr_train_nocmt = pr_sv_train_nocmt_df[pr_sv_train_nocmt_df['language'] == 'CCPP']

In [29]:
pr_train_nocmt_under = pr_train_nocmt[pr_train_nocmt['vuln'] == 1]
pr_train_nocmt_under = pd.concat([pr_train_nocmt_under, pr_train_nocmt[pr_train_nocmt['vuln'] == 0].sample(n=len(pr_train_nocmt_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_val_nocmt_under = pr_val_nocmt[pr_val_nocmt['vuln'] == 1]
pr_val_nocmt_under = pd.concat([pr_val_nocmt_under, pr_val_nocmt[pr_val_nocmt['vuln'] == 0].sample(n=len(pr_val_nocmt_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_test_nocmt_under = pr_test_nocmt[pr_test_nocmt['vuln'] == 1]
pr_test_nocmt_under = pd.concat([pr_test_nocmt_under, pr_test_nocmt[pr_test_nocmt['vuln'] == 0].sample(n=len(pr_test_nocmt_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_train_nocmt_under.info()
pr_val_nocmt_under.info()
pr_test_nocmt_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9686 entries, 0 to 9685
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9686 non-null   object
 1   vuln      9686 non-null   int64
 2   cwe       9686 non-null   int64
 3   language  9686 non-null   object
dtypes: int64(2), object(2)
memory usage: 302.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1160 entries, 0 to 1159
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1160 non-null   object
 1   vuln      1160 non-null   int64
 2   cwe       1160 non-null   int64
 3   language  1160 non-null   object
dtypes: int64(2), object(2)
memory usage: 36.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1162 entries, 0 to 1161
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1162 non-null   object
 1   vuln      1162 non-null   int64
 2   cwe       1162 non-null   int64
 3   language  1162 non-null   object
dtypes: int64(2), object(2)
memory usage: 36.4+ KB

In [30]:
sv_train_nocmt.info()
sv_val_nocmt.info()
sv_test_nocmt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 486 entries, 342 to 180098
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      486 non-null    object
 1   vuln      486 non-null    int64
 2   cwe       486 non-null    int64
 3   language  486 non-null    object
dtypes: int64(2), object(2)
memory usage: 19.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 326 to 22319
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      122 non-null    object
 1   vuln      122 non-null    int64
 2   cwe       122 non-null    int64
 3   language  122 non-null    object
dtypes: int64(2), object(2)
memory usage: 4.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 114 to 22350
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      152 non-null    object
 1   vuln      152 non-null    int64
 2   cwe       152 non-null    int64
 3   language  152 non-null    object
dtypes: int64(2), object(2)
memory usage: 5.9+ KB

In [31]:
pr_sv_val_nocmt_sample_df = pr_val_nocmt.sample(n=len(pr_val_nocmt) // 20, random_state=45).reset_index(drop=True)
pr_sv_test_nocmt_sample_df = pr_test_nocmt.sample(n=len(pr_test_nocmt) // 20, random_state=45).reset_index(drop=True)
pr_sv_val_nocmt_sample_df = pd.concat([pr_sv_val_nocmt_sample_df, sv_val_nocmt], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_test_nocmt_sample_df = pd.concat([pr_sv_test_nocmt_sample_df, sv_test_nocmt], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_val_nocmt_sample_df.info()
pr_sv_test_nocmt_sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1244 entries, 0 to 1243
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1244 non-null   object
 1   vuln      1244 non-null   int64
 2   cwe       1244 non-null   int64
 3   language  1244 non-null   object
dtypes: int64(2), object(2)
memory usage: 39.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274 entries, 0 to 1273
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1274 non-null   object
 1   vuln      1274 non-null   int64
 2   cwe       1274 non-null   int64
 3   language  1274 non-null   object
dtypes: int64(2), object(2)
memory usage: 39.9+ KB

In [32]:
pr_sv_train_nocmt_sample_df = pr_train_nocmt.sample(n=len(pr_train_nocmt) // 20, random_state=45).reset_index(drop=True)
pr_sv_train_nocmt_sample_df = pd.concat([pr_sv_train_nocmt_sample_df, sv_train_nocmt], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_train_nocmt_sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9467 entries, 0 to 9466
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9467 non-null   object
 1   vuln      9467 non-null   int64
 2   cwe       9467 non-null   int64
 3   language  9467 non-null   object
dtypes: int64(2), object(2)
memory usage: 296.0+ KB

In [20]:
pr_sv_train_nocmt_under_df = pd.concat([pr_train_nocmt_under, sv_train_nocmt], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_val_nocmt_under_df = pd.concat([pr_val_nocmt_under, sv_val_nocmt], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_test_nocmt_under_df = pd.concat([pr_test_nocmt_under, sv_test_nocmt], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
pr_sv_train_nocmt_under_df.info()
pr_sv_val_nocmt_under_df.info()
pr_sv_test_nocmt_under_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10172 entries, 0 to 10171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      10172 non-null  object
 1   vuln      10172 non-null  int64
 2   cwe       10172 non-null  int64
 3   language  10172 non-null  object
dtypes: int64(2), object(2)
memory usage: 318.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1282 entries, 0 to 1281
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1282 non-null   object
 1   vuln      1282 non-null   int64
 2   cwe       1282 non-null   int64
 3   language  1282 non-null   object
dtypes: int64(2), object(2)
memory usage: 40.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314 entries, 0 to 1313
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1314 non-null   object
 1   vuln      1314 non-null   int64
 2   cwe       1314 non-null   int64
 3   language  1314 non-null   object
dtypes: int64(2), object(2)
memory usage: 41.2+ KB

In [33]:
pr_sv_val_nocmt_sample_df.to_json("./dataset/MoE/pr_sv_no_cmt/samples/primevul_sven_val_nocmt_sample_20.jsonl", orient="records", lines=True)
pr_sv_test_nocmt_sample_df.to_json("./dataset/MoE/pr_sv_no_cmt/samples/primevul_sven_test_nocmt_sample_20.jsonl", orient="records", lines=True)

In [34]:
pr_sv_train_nocmt_sample_df.to_json("./dataset/MoE/pr_sv_no_cmt/samples/primevul_sven_train_nocmt_sample_20.jsonl", orient="records", lines=True)

In [36]:
sv = pr_sv_test_nocmt_sample_df[pr_sv_test_nocmt_sample_df['language'] == 'Python']
sv[sv['vuln'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 74 entries, 4 to 1263
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      74 non-null     object
 1   vuln      74 non-null     int64
 2   cwe       74 non-null     int64
 3   language  74 non-null     object
dtypes: int64(2), object(2)
memory usage: 2.9+ KB

In [21]:
pr_sv_train_nocmt_under_df.to_json("./dataset/MoE/pr_sv_no_cmt/undernew/primevul_sven_train_nocmt_under.jsonl", orient="records", lines=True)
pr_sv_val_nocmt_under_df.to_json("./dataset/MoE/pr_sv_no_cmt/undernew/primevul_sven_val_nocmt_under.jsonl", orient="records", lines=True)
pr_sv_test_nocmt_under_df.to_json("./dataset/MoE/pr_sv_no_cmt/undernew/primevul_sven_test_nocmt_under.jsonl", orient="records", lines=True)

In [2]:
import json
import pandas as pd
pr_sv_train_nocmt_under = []
with open('C:/hienlt/treesitter/dataset/MoE/pr_sv_no_cmt/under/primevul_sven_train_nocmt_under.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train_nocmt_under.append(record)
pr_sv_train_nocmt_under_df = pd.DataFrame(pr_sv_train_nocmt_under)
pr_sv_train_nocmt_under_df.info()

pr_sv_val_nocmt_under = []
with open('C:/hienlt/treesitter/dataset/MoE/pr_sv_no_cmt/under/primevul_sven_val_nocmt_under.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_val_nocmt_under.append(record)
pr_sv_val_nocmt_under_df = pd.DataFrame(pr_sv_val_nocmt_under)
pr_sv_val_nocmt_under_df.info()

pr_sv_test_nocmt_under = []
with open('C:/hienlt/treesitter/dataset/MoE/pr_sv_no_cmt/under/primevul_sven_test_nocmt_under.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test_nocmt_under.append(record)
pr_sv_test_nocmt_under_df = pd.DataFrame(pr_sv_test_nocmt_under)
pr_sv_test_nocmt_under_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10172 entries, 0 to 10171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      10172 non-null  object
 1   vuln      10172 non-null  int64
 2   cwe       10172 non-null  int64
 3   language  10172 non-null  object
dtypes: int64(2), object(2)
memory usage: 318.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1282 entries, 0 to 1281
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1282 non-null   object
 1   vuln      1282 non-null   int64
 2   cwe       1282 non-null   int64
 3   language  1282 non-null   object
dtypes: int64(2), object(2)
memory usage: 40.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314 entries, 0 to 1313
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1314 non-null   object
 1   vuln      1314 non-null   int64
 2   cwe       1314 non-null   int64
 3   language  1314 non-null   object
dtypes: int64(2), object(2)
memory usage: 41.2+ KB

In [4]:
pr_sv_train_nocmt_nounder = []
with open('C:/hienlt/treesitter/dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_train_nocmt_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_train_nocmt_nounder.append(record)
pr_sv_train_nocmt_nounder_df = pd.DataFrame(pr_sv_train_nocmt_nounder)
pr_sv_train_nocmt_nounder_df.info()

pr_sv_val_nocmt_nounder = []
with open('C:/hienlt/treesitter/dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_val_nocmt_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_val_nocmt_nounder.append(record)
pr_sv_val_nocmt_nounder_df = pd.DataFrame(pr_sv_val_nocmt_nounder)
pr_sv_val_nocmt_nounder_df.info()

pr_sv_test_nocmt_nounder = []
with open('C:/hienlt/treesitter/dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_test_nocmt_nounder.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test_nocmt_nounder.append(record)
pr_sv_test_nocmt_nounder_df = pd.DataFrame(pr_sv_test_nocmt_nounder)
pr_sv_test_nocmt_nounder_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180112 entries, 0 to 180111
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      180112 non-null  object
 1   vuln      180112 non-null  int64
 2   cwe       180112 non-null  int64
 3   language  180112 non-null  object
dtypes: int64(2), object(2)
memory usage: 5.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22575 entries, 0 to 22574
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22575 non-null  object
 1   vuln      22575 non-null  int64
 2   cwe       22575 non-null  int64
 3   language  22575 non-null  object
dtypes: int64(2), object(2)
memory usage: 705.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22606 entries, 0 to 22605
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      22606 non-null  object
 1   vuln      22606 non-null  int64
 2   cwe       22606 non-null  int64
 3   language  22606 non-null  object
dtypes: int64(2), object(2)
memory usage: 706.6+ KB

In [5]:
pr_sv_test_nocmt_nounder_df[pr_sv_test_nocmt_nounder_df['language'] == 'Python'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 114 to 22350
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      152 non-null    object
 1   vuln      152 non-null    int64
 2   cwe       152 non-null    int64
 3   language  152 non-null    object
dtypes: int64(2), object(2)
memory usage: 5.9+ KB

In [6]:
pr_sv_train_nocmt_under_df.to_csv("./dataset/MoE/pr_sv_no_cmt/under/primevul_sven_train_nocmt_under.csv", index=False)
pr_sv_val_nocmt_under_df.to_csv("./dataset/MoE/pr_sv_no_cmt/under/primevul_sven_val_nocmt_under.csv", index=False)
pr_sv_test_nocmt_under_df.to_csv("./dataset/MoE/pr_sv_no_cmt/under/primevul_sven_test_nocmt_under.csv", index=False)

In [7]:
pr_sv_train_nocmt_nounder_df.to_csv("./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_train_nocmt_nounder.csv", index=False)
pr_sv_val_nocmt_nounder_df.to_csv("./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_val_nocmt_nounder.csv", index=False)
pr_sv_test_nocmt_nounder_df.to_csv("./dataset/MoE/pr_sv_no_cmt/nounder/primevul_sven_test_nocmt_nounder.csv", index=False)

In [5]:
import json
import pandas as pd
from sklearn.model_selection import train_test_split

# reposvul_c_data = []
# with open("C:/hienlt/treesitter/dataset/RespoVul/ReposVul_c.jsonl", "r", encoding="utf-8") as f:
#     for line in f:
#         reposvul_c_data.append(json.loads(line))
# reposvul_c_df = pd.DataFrame(reposvul_c_data)
# reposvul_c_df.info()

In [6]:
cleanvul_t3_df = pd.read_csv("C:\\hienlt\\treesitter\\dataset\\CleanVul\\vulnerability_score_3.csv")
cleanvul_t3_df.info()
cleanvul_t4_df = pd.read_csv("C:\\hienlt\\treesitter\\dataset\\CleanVul\\vulnerability_score_4.csv")
cleanvul_t4_df.info()
cleanvul_t0_df = pd.read_csv("C:\\hienlt\\treesitter\\dataset\\CleanVul\\vulnerability_score_0.csv")
cleanvul_t0_df.info()
cleanvul_t2_df = pd.read_csv("C:\\hienlt\\treesitter\\dataset\\CleanVul\\vulnerability_score_2.csv")
cleanvul_t2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2041 entries, 0 to 2040
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          2041 non-null   object
 1   func_after           2041 non-null   object
 2   commit_msg           2041 non-null   object
 3   commit_url           2041 non-null   object
 4   cve_id               173 non-null    object
 5   cwe_id               173 non-null    object
 6   file_name            2041 non-null   object
 7   vulnerability_score  2041 non-null   int64
 8   extension            2041 non-null   object
 9   is_test              2041 non-null   bool
 10  date                 2015 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 161.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6051 entries, 0 to 6050
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          6051 non-null   object
 1   func_after           6051 non-null   object
 2   commit_msg           6051 non-null   object
 3   commit_url           6051 non-null   object
 4   cve_id               729 non-null    object
 5   cwe_id               729 non-null    object
 6   file_name            6051 non-null   object
 7   vulnerability_score  6051 non-null   int64
 8   extension            6051 non-null   object
 9   is_test              6051 non-null   bool
 10  date                 6004 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 478.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15012 entries, 0 to 15011
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          15012 non-null  object
 1   func_after           15012 non-null  object
 2   commit_msg           15008 non-null  object
 3   commit_url           15012 non-null  object
 4   cve_id               2181 non-null   object
 5   cwe_id               2181 non-null   object
 6   file_name            15012 non-null  object
 7   vulnerability_score  15012 non-null  int64
 8   extension            15012 non-null  object
 9   is_test              15012 non-null  bool
 10  date                 13253 non-null  object
dtypes: bool(1), int64(1), object(9)
memory usage: 1.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2444 entries, 0 to 2443
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          2444 non-null   object
 1   func_after           2444 non-null   object
 2   commit_msg           2444 non-null   object
 3   commit_url           2444 non-null   object
 4   cve_id               154 non-null    object
 5   cwe_id               154 non-null    object
 6   file_name            2444 non-null   object
 7   vulnerability_score  2444 non-null   int64
 8   extension            2444 non-null   object
 9   is_test              2444 non-null   bool
 10  date                 2398 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 193.4+ KB

In [24]:
cleanvul_t2_df['extension'].unique()

array(['c', 'java', 'js', 'py', 'cpp', 'cs'], dtype=object)

array(['c', 'py', 'java', 'cs', 'js', 'cpp'], dtype=object)

In [3]:
cleanvul_ccpp_t3 = cleanvul_t3_df[(cleanvul_t3_df['extension'] == 'c') | (cleanvul_t3_df['extension'] == 'cpp')]
cleanvul_ccpp_t3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 300 entries, 2 to 2039
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          300 non-null    object
 1   func_after           300 non-null    object
 2   commit_msg           300 non-null    object
 3   commit_url           300 non-null    object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            300 non-null    object
 7   vulnerability_score  300 non-null    int64
 8   extension            300 non-null    object
 9   is_test              300 non-null    bool
 10  date                 289 non-null    object
dtypes: bool(1), int64(1), object(9)
memory usage: 26.1+ KB

In [105]:
cleanvul_java_t3 = cleanvul_t3_df[cleanvul_t3_df['extension'] == 'java']
cleanvul_java_t3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1432 entries, 4 to 2040
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          1432 non-null   object
 1   func_after           1432 non-null   object
 2   commit_msg           1432 non-null   object
 3   commit_url           1432 non-null   object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            1432 non-null   object
 7   vulnerability_score  1432 non-null   int64
 8   extension            1432 non-null   object
 9   is_test              1432 non-null   bool
 10  date                 1424 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 124.5+ KB

In [7]:
cleanvul_ccpp_t4 = cleanvul_t4_df[(cleanvul_t4_df['extension'] == 'c') | (cleanvul_t4_df['extension'] == 'cpp')]
cleanvul_ccpp_t4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2951 entries, 0 to 6049
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          2951 non-null   object
 1   func_after           2951 non-null   object
 2   commit_msg           2951 non-null   object
 3   commit_url           2951 non-null   object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            2951 non-null   object
 7   vulnerability_score  2951 non-null   int64
 8   extension            2951 non-null   object
 9   is_test              2951 non-null   bool
 10  date                 2910 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 256.5+ KB

In [5]:
cleanvul_ccpp_t0 = cleanvul_t0_df[(cleanvul_t0_df['extension'] == 'c') | (cleanvul_t0_df['extension'] == 'cpp')]
cleanvul_ccpp_t0.info()
cleanvul_ccpp_t2 = cleanvul_t2_df[(cleanvul_t2_df['extension'] == 'c') | (cleanvul_t2_df['extension'] == 'cpp')]
cleanvul_ccpp_t2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1087 entries, 23 to 15000
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          1087 non-null   object
 1   func_after           1087 non-null   object
 2   commit_msg           1085 non-null   object
 3   commit_url           1087 non-null   object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            1087 non-null   object
 7   vulnerability_score  1087 non-null   int64
 8   extension            1087 non-null   object
 9   is_test              1087 non-null   bool
 10  date                 898 non-null    object
dtypes: bool(1), int64(1), object(9)
memory usage: 94.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 379 entries, 0 to 2442
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          379 non-null    object
 1   func_after           379 non-null    object
 2   commit_msg           379 non-null    object
 3   commit_url           379 non-null    object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            379 non-null    object
 7   vulnerability_score  379 non-null    int64
 8   extension            379 non-null    object
 9   is_test              379 non-null    bool
 10  date                 344 non-null    object
dtypes: bool(1), int64(1), object(9)
memory usage: 32.9+ KB

In [106]:
cleanvul_java_t4 = cleanvul_t4_df[cleanvul_t4_df['extension'] == 'java']
cleanvul_java_t4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1322 entries, 9 to 6032
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          1322 non-null   object
 1   func_after           1322 non-null   object
 2   commit_msg           1322 non-null   object
 3   commit_url           1322 non-null   object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            1322 non-null   object
 7   vulnerability_score  1322 non-null   int64
 8   extension            1322 non-null   object
 9   is_test              1322 non-null   bool
 10  date                 1321 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 114.9+ KB

In [6]:
cleanvul_reliable_df = pd.concat([cleanvul_t3_df, cleanvul_t4_df, cleanvul_t0_df, cleanvul_t2_df], ignore_index=True)
cleanvul_reliable_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25548 entries, 0 to 25547
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          25548 non-null  object
 1   func_after           25548 non-null  object
 2   commit_msg           25544 non-null  object
 3   commit_url           25548 non-null  object
 4   cve_id               3237 non-null   object
 5   cwe_id               3237 non-null   object
 6   file_name            25548 non-null  object
 7   vulnerability_score  25548 non-null  int64
 8   extension            25548 non-null  object
 9   is_test              25548 non-null  bool
 10  date                 23670 non-null  object
dtypes: bool(1), int64(1), object(9)
memory usage: 2.0+ MB

In [7]:
cleanvul_reliable_ccpp_df = cleanvul_reliable_df[(cleanvul_reliable_df['extension'] == 'c') | (cleanvul_reliable_df['extension'] == 'cpp')]
cleanvul_reliable_ccpp_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4717 entries, 2 to 25546
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          4717 non-null   object
 1   func_after           4717 non-null   object
 2   commit_msg           4715 non-null   object
 3   commit_url           4717 non-null   object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            4717 non-null   object
 7   vulnerability_score  4717 non-null   int64
 8   extension            4717 non-null   object
 9   is_test              4717 non-null   bool
 10  date                 4441 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 410.0+ KB

In [107]:
cleanvul_reliable_java_df = cleanvul_reliable_df[(cleanvul_reliable_df['extension'] == 'java')]
cleanvul_reliable_java_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2754 entries, 4 to 8073
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   func_before          2754 non-null   object
 1   func_after           2754 non-null   object
 2   commit_msg           2754 non-null   object
 3   commit_url           2754 non-null   object
 4   cve_id               0 non-null      object
 5   cwe_id               0 non-null      object
 6   file_name            2754 non-null   object
 7   vulnerability_score  2754 non-null   int64
 8   extension            2754 non-null   object
 9   is_test              2754 non-null   bool
 10  date                 2745 non-null   object
dtypes: bool(1), int64(1), object(9)
memory usage: 239.4+ KB

In [8]:
cleanvul_reliable_ccpp_df['vulnerability_score'].unique()

array([3, 4, 0, 2])

In [9]:
cleanvul_ccpp_moe_df = pd.DataFrame(columns=['code', 'vuln', 'cwe', 'language'])

for index, row in cleanvul_reliable_ccpp_df.iterrows():
    vul_code = row['func_before']
    fix_code = row['func_after']
    cwe = 1
    language = 'CCPP'
    vul_df = pd.DataFrame({'code': [vul_code], 'vuln': [1], 'cwe': [cwe], 'language': [language]})
    fix_df = pd.DataFrame({'code': [fix_code], 'vuln': [0], 'cwe': [cwe], 'language': [language]})
    cleanvul_ccpp_moe_df = pd.concat([cleanvul_ccpp_moe_df, vul_df, fix_df], ignore_index=True)

cleanvul_ccpp_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9434 entries, 0 to 9433
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9434 non-null   object
 1   vuln      9434 non-null   object
 2   cwe       9434 non-null   object
 3   language  9434 non-null   object
dtypes: object(4)
memory usage: 294.9+ KB

In [9]:
languages_map = {
    'c': 'CCPP',
    'cpp': 'CCPP',
    'java': 'Java',
    'js': 'JavaScript',
    "py" : "Python",
    'cs': 'CSharp'
}

In [10]:
cleanvul_t4_moe_df = pd.DataFrame(columns=['code', 'vuln', 'cwe', 'language'])

for index, row in cleanvul_t4_df.iterrows():
    vul_code = row['func_before']
    fix_code = row['func_after']
    cwe = 1
    language = languages_map.get(row['extension'], 'Unknown')
    vul_df = pd.DataFrame({'code': [vul_code], 'vuln': [1], 'cwe': [cwe], 'language': [language]})
    fix_df = pd.DataFrame({'code': [fix_code], 'vuln': [0], 'cwe': [cwe], 'language': [language]})
    cleanvul_t4_moe_df = pd.concat([cleanvul_t4_moe_df, vul_df, fix_df], ignore_index=True)

cleanvul_t4_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12102 entries, 0 to 12101
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      12102 non-null  object
 1   vuln      12102 non-null  object
 2   cwe       12102 non-null  object
 3   language  12102 non-null  object
dtypes: object(4)
memory usage: 378.3+ KB

In [11]:
cleanvul_t4_moe_df['language'].unique()

array(['CCPP', 'Python', 'Java', 'CSharp', 'JavaScript'], dtype=object)

In [12]:
cleanvul_t4_moe_train_df, cleanvul_t4_moe_temp_df = train_test_split(cleanvul_t4_moe_df, test_size=0.2, random_state=45)
cleanvul_t4_moe_val_df, cleanvul_t4_moe_test_df = train_test_split(cleanvul_t4_moe_temp_df, test_size=0.5, random_state=45, stratify=cleanvul_t4_moe_temp_df['vuln'])
cleanvul_t4_moe_train_df.info()
cleanvul_t4_moe_val_df.info()
cleanvul_t4_moe_test_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9681 entries, 2442 to 7115
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9681 non-null   object
 1   vuln      9681 non-null   object
 2   cwe       9681 non-null   object
 3   language  9681 non-null   object
dtypes: object(4)
memory usage: 378.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1210 entries, 3575 to 5959
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1210 non-null   object
 1   vuln      1210 non-null   object
 2   cwe       1210 non-null   object
 3   language  1210 non-null   object
dtypes: object(4)
memory usage: 47.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1211 entries, 5583 to 5373
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1211 non-null   object
 1   vuln      1211 non-null   object
 2   cwe       1211 non-null   object
 3   language  1211 non-null   object
dtypes: object(4)
memory usage: 47.3+ KB

In [34]:
cleanvul_t4_moe_train_df[cleanvul_t4_moe_train_df['vuln'] == 0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 4845 entries, 3829 to 7115
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      4845 non-null   object
 1   vuln      4845 non-null   object
 2   cwe       4845 non-null   object
 3   language  4845 non-null   object
dtypes: object(4)
memory usage: 189.3+ KB

In [13]:
cleanvul_t4_moe_train_df.to_json("./dataset/CleanVul/T4/full_comment/cleanvul_t4_moe_train.jsonl", orient="records", lines=True)
cleanvul_t4_moe_val_df.to_json("./dataset/CleanVul/T4/full_comment/cleanvul_t4_moe_val.jsonl", orient="records", lines=True)
cleanvul_t4_moe_test_df.to_json("./dataset/CleanVul/T4/full_comment/cleanvul_t4_moe_test.jsonl", orient="records", lines=True)

In [108]:
cleanvul_java_moe_df = pd.DataFrame(columns=['code', 'vuln', 'cwe', 'language'])

for index, row in cleanvul_reliable_java_df.iterrows():
    vul_code = row['func_before']
    fix_code = row['func_after']
    cwe = 1
    language = 'Java'
    vul_df = pd.DataFrame({'code': [vul_code], 'vuln': [1], 'cwe': [cwe], 'language': [language]})
    fix_df = pd.DataFrame({'code': [fix_code], 'vuln': [0], 'cwe': [cwe], 'language': [language]})
    cleanvul_java_moe_df = pd.concat([cleanvul_java_moe_df, vul_df, fix_df], ignore_index=True)

cleanvul_java_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5508 entries, 0 to 5507
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      5508 non-null   object
 1   vuln      5508 non-null   object
 2   cwe       5508 non-null   object
 3   language  5508 non-null   object
dtypes: object(4)
memory usage: 172.2+ KB

In [10]:
for index, row in cleanvul_ccpp_moe_df.iterrows():
    cleanvul_ccpp_moe_df.at[index, 'cwe'] = int(row['cwe'])
    cleanvul_ccpp_moe_df.at[index, 'vuln'] = int(row['vuln'])
    cleanvul_ccpp_moe_df.at[index, 'code'] = str(row['code'])
    cleanvul_ccpp_moe_df.at[index, 'language'] = str(row['language'])
cleanvul_ccpp_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9434 entries, 0 to 9433
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9434 non-null   object
 1   vuln      9434 non-null   object
 2   cwe       9434 non-null   object
 3   language  9434 non-null   object
dtypes: object(4)
memory usage: 294.9+ KB

In [109]:
for index, row in cleanvul_java_moe_df.iterrows():
    cleanvul_java_moe_df.at[index, 'cwe'] = int(row['cwe'])
    cleanvul_java_moe_df.at[index, 'vuln'] = int(row['vuln'])
    cleanvul_java_moe_df.at[index, 'code'] = str(row['code'])
    cleanvul_java_moe_df.at[index, 'language'] = str(row['language'])
cleanvul_java_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5508 entries, 0 to 5507
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      5508 non-null   object
 1   vuln      5508 non-null   object
 2   cwe       5508 non-null   object
 3   language  5508 non-null   object
dtypes: object(4)
memory usage: 172.2+ KB

In [12]:
import re
# remove comments
cleanvul_ccpp_nocmt_moe_df = cleanvul_ccpp_moe_df.copy()
for index, row in cleanvul_ccpp_nocmt_moe_df.iterrows():
    code = row['code']
    code_no_cmt = remove_comments(code)
    cleanvul_ccpp_nocmt_moe_df.at[index, 'code'] = code_no_cmt
cleanvul_ccpp_nocmt_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9434 entries, 0 to 9433
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      9434 non-null   object
 1   vuln      9434 non-null   object
 2   cwe       9434 non-null   object
 3   language  9434 non-null   object
dtypes: object(4)
memory usage: 294.9+ KB

In [110]:
# remove comments
cleanvul_java_nocmt_moe_df = cleanvul_java_moe_df.copy()
for index, row in cleanvul_java_nocmt_moe_df.iterrows():
    code = row['code']
    code_no_cmt = remove_comments_java(code)
    cleanvul_java_nocmt_moe_df.at[index, 'code'] = code_no_cmt
cleanvul_java_nocmt_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5508 entries, 0 to 5507
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      5508 non-null   object
 1   vuln      5508 non-null   object
 2   cwe       5508 non-null   object
 3   language  5508 non-null   object
dtypes: object(4)
memory usage: 172.2+ KB

In [13]:
cleanvul_ccpp_moe_df['idx'] = cleanvul_ccpp_moe_df.index
cleanvul_ccpp_nocmt_moe_df['idx'] = cleanvul_ccpp_nocmt_moe_df.index

In [111]:
cleanvul_java_moe_df['idx'] = cleanvul_java_moe_df.index
cleanvul_java_nocmt_moe_df['idx'] = cleanvul_java_nocmt_moe_df.index

In [14]:
cleanvul_ccpp_train_moe_df, temp_df = train_test_split(cleanvul_ccpp_moe_df, test_size=0.2, random_state=45, stratify=cleanvul_ccpp_moe_df['vuln'])
cleanvul_ccpp_val_moe_df, cleanvul_ccpp_test_moe_df = train_test_split(temp_df, test_size=0.5, random_state=45, stratify=temp_df['vuln'])
cleanvul_ccpp_train_moe_df.info()
cleanvul_ccpp_val_moe_df.info()
cleanvul_ccpp_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7547 entries, 650 to 3661
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      7547 non-null   object
 1   vuln      7547 non-null   object
 2   cwe       7547 non-null   object
 3   language  7547 non-null   object
 4   idx       7547 non-null   int64
dtypes: int64(1), object(4)
memory usage: 353.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1216 to 2881
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      943 non-null    object
 1   vuln      943 non-null    object
 2   cwe       943 non-null    object
 3   language  943 non-null    object
 4   idx       943 non-null    int64
dtypes: int64(1), object(4)
memory usage: 44.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 944 entries, 5415 to 4984
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      944 non-null    object
 1   vuln      944 non-null    object
 2   cwe       944 non-null    object
 3   language  944 non-null    object
 4   idx       944 non-null    int64
dtypes: int64(1), object(4)
memory usage: 44.2+ KB

In [112]:
cleanvul_java_train_moe_df, temp_df = train_test_split(cleanvul_java_moe_df, test_size=0.2, random_state=45, stratify=cleanvul_java_moe_df['vuln'])
cleanvul_java_val_moe_df, cleanvul_java_test_moe_df = train_test_split(temp_df, test_size=0.5, random_state=45, stratify=temp_df['vuln'])
cleanvul_java_train_moe_df.info()
cleanvul_java_val_moe_df.info()
cleanvul_java_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4406 entries, 119 to 1774
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      4406 non-null   object
 1   vuln      4406 non-null   object
 2   cwe       4406 non-null   object
 3   language  4406 non-null   object
 4   idx       4406 non-null   int64
dtypes: int64(1), object(4)
memory usage: 206.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 551 entries, 4233 to 4000
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      551 non-null    object
 1   vuln      551 non-null    object
 2   cwe       551 non-null    object
 3   language  551 non-null    object
 4   idx       551 non-null    int64
dtypes: int64(1), object(4)
memory usage: 25.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 551 entries, 660 to 963
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      551 non-null    object
 1   vuln      551 non-null    object
 2   cwe       551 non-null    object
 3   language  551 non-null    object
 4   idx       551 non-null    int64
dtypes: int64(1), object(4)
memory usage: 25.8+ KB

In [15]:
cleanvul_ccpp_nocmt_train_moe_df = cleanvul_ccpp_nocmt_moe_df[cleanvul_ccpp_nocmt_moe_df['idx'].isin(cleanvul_ccpp_train_moe_df['idx'])]
cleanvul_ccpp_nocmt_val_moe_df = cleanvul_ccpp_nocmt_moe_df[cleanvul_ccpp_nocmt_moe_df['idx'].isin(cleanvul_ccpp_val_moe_df['idx'])]
cleanvul_ccpp_nocmt_test_moe_df = cleanvul_ccpp_nocmt_moe_df[cleanvul_ccpp_nocmt_moe_df['idx'].isin(cleanvul_ccpp_test_moe_df['idx'])]
cleanvul_ccpp_nocmt_train_moe_df.info()
cleanvul_ccpp_nocmt_val_moe_df.info()
cleanvul_ccpp_nocmt_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7547 entries, 0 to 9433
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      7547 non-null   object
 1   vuln      7547 non-null   object
 2   cwe       7547 non-null   object
 3   language  7547 non-null   object
 4   idx       7547 non-null   int64
dtypes: int64(1), object(4)
memory usage: 353.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 28 to 9426
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      943 non-null    object
 1   vuln      943 non-null    object
 2   cwe       943 non-null    object
 3   language  943 non-null    object
 4   idx       943 non-null    int64
dtypes: int64(1), object(4)
memory usage: 44.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 944 entries, 8 to 9415
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      944 non-null    object
 1   vuln      944 non-null    object
 2   cwe       944 non-null    object
 3   language  944 non-null    object
 4   idx       944 non-null    int64
dtypes: int64(1), object(4)
memory usage: 44.2+ KB

In [113]:
cleanvul_java_nocmt_train_moe_df = cleanvul_java_nocmt_moe_df[cleanvul_java_nocmt_moe_df['idx'].isin(cleanvul_java_train_moe_df['idx'])]
cleanvul_java_nocmt_val_moe_df = cleanvul_java_nocmt_moe_df[cleanvul_java_nocmt_moe_df['idx'].isin(cleanvul_java_val_moe_df['idx'])]
cleanvul_java_nocmt_test_moe_df = cleanvul_java_nocmt_moe_df[cleanvul_java_nocmt_moe_df['idx'].isin(cleanvul_java_test_moe_df['idx'])]
cleanvul_java_nocmt_train_moe_df.info()
cleanvul_java_nocmt_val_moe_df.info()
cleanvul_java_nocmt_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4406 entries, 0 to 5507
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      4406 non-null   object
 1   vuln      4406 non-null   object
 2   cwe       4406 non-null   object
 3   language  4406 non-null   object
 4   idx       4406 non-null   int64
dtypes: int64(1), object(4)
memory usage: 206.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 551 entries, 2 to 5498
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      551 non-null    object
 1   vuln      551 non-null    object
 2   cwe       551 non-null    object
 3   language  551 non-null    object
 4   idx       551 non-null    int64
dtypes: int64(1), object(4)
memory usage: 25.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 551 entries, 31 to 5500
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      551 non-null    object
 1   vuln      551 non-null    object
 2   cwe       551 non-null    object
 3   language  551 non-null    object
 4   idx       551 non-null    int64
dtypes: int64(1), object(4)
memory usage: 25.8+ KB

In [19]:
cleanvul_nocmt_train_moe_df = pd.concat([cleanvul_ccpp_nocmt_train_moe_df, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_nocmt_val_moe_df = pd.concat([cleanvul_ccpp_nocmt_val_moe_df, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_nocmt_test_moe_df = pd.concat([cleanvul_ccpp_nocmt_test_moe_df, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_nocmt_train_moe_df.info()
cleanvul_nocmt_val_moe_df.info()
cleanvul_nocmt_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8033 entries, 0 to 8032
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      8033 non-null   object
 1   vuln      8033 non-null   object
 2   cwe       8033 non-null   object
 3   language  8033 non-null   object
 4   idx       7547 non-null   float64
dtypes: float64(1), object(4)
memory usage: 313.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1065 entries, 0 to 1064
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1065 non-null   object
 1   vuln      1065 non-null   object
 2   cwe       1065 non-null   object
 3   language  1065 non-null   object
 4   idx       943 non-null    float64
dtypes: float64(1), object(4)
memory usage: 41.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1096 non-null   object
 1   vuln      1096 non-null   object
 2   cwe       1096 non-null   object
 3   language  1096 non-null   object
 4   idx       944 non-null    float64
dtypes: float64(1), object(4)
memory usage: 42.9+ KB

In [114]:
cleanvul_java_nocmt_train_moe_df = pd.concat([cleanvul_java_nocmt_train_moe_df, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_java_nocmt_val_moe_df = pd.concat([cleanvul_java_nocmt_val_moe_df, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_java_nocmt_test_moe_df = pd.concat([cleanvul_java_nocmt_test_moe_df, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_java_nocmt_train_moe_df.info()
cleanvul_java_nocmt_val_moe_df.info()
cleanvul_java_nocmt_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4892 entries, 0 to 4891
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      4892 non-null   object
 1   vuln      4892 non-null   object
 2   cwe       4892 non-null   object
 3   language  4892 non-null   object
 4   idx       4406 non-null   float64
dtypes: float64(1), object(4)
memory usage: 191.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      673 non-null    object
 1   vuln      673 non-null    object
 2   cwe       673 non-null    object
 3   language  673 non-null    object
 4   idx       551 non-null    float64
dtypes: float64(1), object(4)
memory usage: 26.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 703 entries, 0 to 702
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      703 non-null    object
 1   vuln      703 non-null    object
 2   cwe       703 non-null    object
 3   language  703 non-null    object
 4   idx       551 non-null    float64
dtypes: float64(1), object(4)
memory usage: 27.6+ KB

In [21]:
cleanvul_nocmt_train_moe_df.to_json("./dataset/CleanVul/CCPP/no_comment/cleanvul_sven_train_nocmt_full.jsonl", orient="records", lines=True)
cleanvul_nocmt_val_moe_df.to_json("./dataset/CleanVul/CCPP/no_comment/cleanvul_sven_val_nocmt_full.jsonl", orient="records", lines=True)
cleanvul_nocmt_test_moe_df.to_json("./dataset/CleanVul/CCPP/no_comment/cleanvul_sven_test_nocmt_full.jsonl", orient="records", lines=True)

In [115]:
cleanvul_java_nocmt_train_moe_df.to_json("./dataset/CleanVul/Java/no_comment/cleanvul_sven_java_train_nocmt.jsonl", orient="records", lines=True)
cleanvul_java_nocmt_val_moe_df.to_json("./dataset/CleanVul/Java/no_comment/cleanvul_sven_java_val_nocmt.jsonl", orient="records", lines=True)
cleanvul_java_nocmt_test_moe_df.to_json("./dataset/CleanVul/Java/no_comment/cleanvul_sven_java_test_nocmt.jsonl", orient="records", lines=True)

In [116]:
cleanvul_java_train_moe_df = pd.concat([cleanvul_java_train_moe_df, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_java_val_moe_df = pd.concat([cleanvul_java_val_moe_df, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_java_test_moe_df = pd.concat([cleanvul_java_test_moe_df, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
cleanvul_java_train_moe_df.info()
cleanvul_java_val_moe_df.info()
cleanvul_java_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4892 entries, 0 to 4891
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      4892 non-null   object
 1   vuln      4892 non-null   object
 2   cwe       4892 non-null   object
 3   language  4892 non-null   object
 4   idx       4406 non-null   float64
dtypes: float64(1), object(4)
memory usage: 191.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      673 non-null    object
 1   vuln      673 non-null    object
 2   cwe       673 non-null    object
 3   language  673 non-null    object
 4   idx       551 non-null    float64
dtypes: float64(1), object(4)
memory usage: 26.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 703 entries, 0 to 702
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      703 non-null    object
 1   vuln      703 non-null    object
 2   cwe       703 non-null    object
 3   language  703 non-null    object
 4   idx       551 non-null    float64
dtypes: float64(1), object(4)
memory usage: 27.6+ KB

In [117]:
cleanvul_java_train_moe_df.to_json("./dataset/CleanVul/Java/full_comment/cleanvul_sven_java_train_fullcomment.jsonl", orient="records", lines=True)
cleanvul_java_val_moe_df.to_json("./dataset/CleanVul/Java/full_comment/cleanvul_sven_java_val_fullcomment.jsonl", orient="records", lines=True)
cleanvul_java_test_moe_df.to_json("./dataset/CleanVul/Java/full_comment/cleanvul_sven_java_test_fullcomment.jsonl", orient="records", lines=True)

In [14]:
reposvul_c = []
with open('C:/hienlt/treesitter/dataset/RespoVul/ReposVul_c.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        reposvul_c.append(record)
reposvul_c_df = pd.DataFrame(reposvul_c)
reposvul_c_df.info()

reposvul_cpp = []
with open('C:/hienlt/treesitter/dataset/RespoVul/ReposVul_cpp.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        reposvul_cpp.append(record)
reposvul_cpp_df = pd.DataFrame(reposvul_cpp)
reposvul_cpp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4010 entries, 0 to 4009
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            4010 non-null   int64
 1   cve_id           4010 non-null   object
 2   cwe_id           4010 non-null   object
 3   cve_language     4010 non-null   object
 4   cve_description  4010 non-null   object
 5   cvss             4010 non-null   object
 6   publish_date     4010 non-null   object
 7   AV               4010 non-null   object
 8   AC               4010 non-null   object
 9   PR               4010 non-null   object
 10  UI               4010 non-null   object
 11  S                4010 non-null   object
 12  C                4010 non-null   object
 13  I                4010 non-null   object
 14  A                4010 non-null   object
 15  commit_id        4010 non-null   object
 16  commit_message   4010 non-null   object
 17  commit_date      4010 non-null   object
 18  project          4010 non-null   object
 19  url              4010 non-null   object
 20  html_url         4010 non-null   object
 21  windows_before   4010 non-null   object
 22  windows_after    4010 non-null   object
 23  parents          4010 non-null   object
 24  details          4010 non-null   object
 25  outdated         4010 non-null   int64
 26  cwe_descripiton  4010 non-null   object
 27  cwe_consequence  4010 non-null   object
 28  cwe_method       4010 non-null   object
 29  cwe_solution     4010 non-null   object
dtypes: int64(2), object(28)
memory usage: 940.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            689 non-null    int64
 1   cve_id           689 non-null    object
 2   cwe_id           689 non-null    object
 3   cve_language     689 non-null    object
 4   cve_description  689 non-null    object
 5   cvss             689 non-null    object
 6   publish_date     689 non-null    object
 7   AV               689 non-null    object
 8   AC               689 non-null    object
 9   PR               689 non-null    object
 10  UI               689 non-null    object
 11  S                689 non-null    object
 12  C                689 non-null    object
 13  I                689 non-null    object
 14  A                689 non-null    object
 15  commit_id        689 non-null    object
 16  commit_message   689 non-null    object
 17  commit_date      689 non-null    object
 18  project          689 non-null    object
 19  url              689 non-null    object
 20  html_url         689 non-null    object
 21  windows_before   689 non-null    object
 22  windows_after    689 non-null    object
 23  parents          689 non-null    object
 24  details          689 non-null    object
 25  outdated         689 non-null    int64
 26  cwe_descripiton  689 non-null    object
 27  cwe_consequence  689 non-null    object
 28  cwe_method       689 non-null    object
 29  cwe_solution     689 non-null    object
dtypes: int64(2), object(28)
memory usage: 161.6+ KB

In [25]:
reposvul_ccpp_df = pd.concat([reposvul_c_df, reposvul_cpp_df], ignore_index=True)

In [31]:
for index, row in reposvul_ccpp_df.iterrows():
    reposvul_ccpp_df.at[index, 'cwe'] = str(row['cwe_id'][0])

reposvul_ccpp_df['cwe'].head()

0    CWE-362
1    CWE-399
2    CWE-399
3    CWE-399
4    CWE-399
Name: cwe, dtype: object

In [32]:
reposvul_ccpp_df['cwe'].unique()

array(['CWE-362', 'CWE-399', 'CWE-119', 'CWE-20', 'CWE-189', 'CWE-264',
       'CWE-200', 'CWE-400', 'CWE-476', 'CWE-190', 'CWE-835',
       'NVD-CWE-noinfo', 'CWE-287', 'CWE-16', 'CWE-310', 'CWE-255',
       'CWE-611', 'CWE-22', 'CWE-59', 'CWE-89', 'CWE-416', 'CWE-754',
       'CWE-415', 'CWE-17', 'CWE-284', 'CWE-19', 'CWE-79', 'CWE-254',
       'CWE-18', 'CWE-134', 'CWE-369', 'CWE-295', 'CWE-125', 'CWE-285',
       'CWE-74', 'CWE-787', 'CWE-502', 'CWE-388', 'CWE-320', 'CWE-275',
       'CWE-532', 'CWE-918', 'CWE-770', 'CWE-191', 'CWE-116', 'CWE-120',
       'CWE-404', 'CWE-358', 'CWE-77', 'CWE-704', 'CWE-129', 'CWE-665',
       'CWE-426', 'CWE-269', 'CWE-494', 'CWE-90', 'CWE-824', 'CWE-682',
       'CWE-347', 'CWE-88', 'CWE-601', 'CWE-732', 'CWE-94', 'CWE-113',
       'CWE-444', 'CWE-326', 'CWE-908', 'CWE-617', 'CWE-401', 'CWE-78',
       'CWE-772', 'CWE-345', 'CWE-674', 'CWE-203', 'CWE-273', 'CWE-434',
       'CWE-755', 'CWE-354', 'CWE-672', 'CWE-670', 'CWE-522', 'CWE-681',
       'CWE-707', 'CWE-121', 'CWE-276', 'CWE-252', 'CWE-552', 'CWE-862',
       'CWE-763', 'CWE-667', 'CWE-459', 'CWE-122', 'CWE-909', 'CWE-367',
       'CWE-327', 'CWE-406', 'CWE-331', 'CWE-834', 'CWE-290', 'CWE-209',
       'CWE-212', 'CWE-863', 'CWE-697', 'CWE-668', 'CWE-193', 'CWE-338',
       'CWE-407', 'CWE-312', 'CWE-457', 'CWE-384', 'CWE-843', 'CWE-281',
       'CWE-1021', 'CWE-769', 'CWE-73', 'CWE-337', 'CWE-436', 'CWE-319',
       'CWE-823', 'CWE-118', 'CWE-330', 'CWE-428', 'CWE-1077', 'CWE-693',
       'CWE-789', 'CWE-943', 'CWE-913', 'CWE-306', 'CWE-922'],
      dtype=object)

In [35]:
for index, row in reposvul_ccpp_df.iterrows():
    cwe_value = str(row['cwe']).split('-')[-1]
    if cwe_value == "noinfo":
        cwe_value = -2
    else:
        cwe_value = int(cwe_value)
    reposvul_ccpp_df.at[index, 'cwe'] = cwe_value

reposvul_ccpp_df['cwe'].unique()

array([362, 399, 119, 20, 189, 264, 200, 400, 476, 190, 835, -2, 287, 16,
       310, 255, 611, 22, 59, 89, 416, 754, 415, 17, 284, 19, 79, 254, 18,
       134, 369, 295, 125, 285, 74, 787, 502, 388, 320, 275, 532, 918,
       770, 191, 116, 120, 404, 358, 77, 704, 129, 665, 426, 269, 494, 90,
       824, 682, 347, 88, 601, 732, 94, 113, 444, 326, 908, 617, 401, 78,
       772, 345, 674, 203, 273, 434, 755, 354, 672, 670, 522, 681, 707,
       121, 276, 252, 552, 862, 763, 667, 459, 122, 909, 367, 327, 406,
       331, 834, 290, 209, 212, 863, 697, 668, 193, 338, 407, 312, 457,
       384, 843, 281, 1021, 769, 73, 337, 436, 319, 823, 118, 330, 428,
       1077, 693, 789, 943, 913, 306, 922], dtype=object)

In [38]:
for index, row in reposvul_ccpp_df.iterrows():
    cur_list = row['details']
    cur_list.append({'cwe': row['cwe']})
    reposvul_ccpp_df.at[index, 'details'] = cur_list
reposvul_ccpp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4699 entries, 0 to 4698
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            4699 non-null   int64
 1   cve_id           4699 non-null   object
 2   cwe_id           4699 non-null   object
 3   cve_language     4699 non-null   object
 4   cve_description  4699 non-null   object
 5   cvss             4699 non-null   object
 6   publish_date     4699 non-null   object
 7   AV               4699 non-null   object
 8   AC               4699 non-null   object
 9   PR               4699 non-null   object
 10  UI               4699 non-null   object
 11  S                4699 non-null   object
 12  C                4699 non-null   object
 13  I                4699 non-null   object
 14  A                4699 non-null   object
 15  commit_id        4699 non-null   object
 16  commit_message   4699 non-null   object
 17  commit_date      4699 non-null   object
 18  project          4699 non-null   object
 19  url              4699 non-null   object
 20  html_url         4699 non-null   object
 21  windows_before   4699 non-null   object
 22  windows_after    4699 non-null   object
 23  parents          4699 non-null   object
 24  details          4699 non-null   object
 25  outdated         4699 non-null   int64
 26  cwe_descripiton  4699 non-null   object
 27  cwe_consequence  4699 non-null   object
 28  cwe_method       4699 non-null   object
 29  cwe_solution     4699 non-null   object
 30  cwe              4699 non-null   object
dtypes: int64(2), object(29)
memory usage: 1.1+ MB

In [81]:
total_funcs = 0
dup_funcs = 0
reposvul_ccpp_moe_df = pd.DataFrame(columns=['code', 'vuln', 'cwe', 'language'])
for index, row in reposvul_ccpp_df.iterrows():
    functions_before = []
    functions_after = []
    details_list = row['details']
    cwe_value = details_list[-1]['cwe']
    details = details_list[0]
    if 'function_before' in details:
        for func in details['function_before']:
            functions_before.append(func)
    if 'function_after' in details:
        for func in details['function_after']:
            functions_after.append(func)
    for i in range(len(functions_before)):
        non_vul_df = pd.DataFrame({'code': [functions_before[i]['function']], 'vuln': [int(functions_before[i]['target'])], 'cwe': [cwe_value], 'language': ['CCPP']})
        if(len(functions_before) == len(functions_after)):
            if functions_before[i] == functions_after[i]:
                    if functions_before[i]['target'] == 0 and functions_after[i]['target'] == 0:
                        dup_funcs += 1
                        continue
        if i < len(functions_after):    
            vul_df = pd.DataFrame({'code': [functions_after[i]['function']], 'vuln': [int(functions_after[i]['target'])], 'cwe': [cwe_value], 'language': ['CCPP']})   
        reposvul_ccpp_moe_df = pd.concat([reposvul_ccpp_moe_df, non_vul_df, vul_df], ignore_index=True)    
        total_funcs += 1
print(f"Total functions: {total_funcs}")
print(f"Duplicate non-vulnerable functions: {dup_funcs}")
reposvul_ccpp_moe_df.info()

Total functions: 6580
Duplicate non-vulnerable functions: 42792
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13160 entries, 0 to 13159
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      13160 non-null  object
 1   vuln      13160 non-null  object
 2   cwe       13160 non-null  object
 3   language  13160 non-null  object
dtypes: object(4)
memory usage: 411.4+ KB

In [83]:
float(len(reposvul_ccpp_moe_df[reposvul_ccpp_moe_df['vuln'] == 1]) / len(reposvul_ccpp_moe_df)) * 100

4.703647416413373

In [62]:
sum_funcs = 0
for index, row in reposvul_ccpp_df.iterrows():
    details_list = row['details']
    details = details_list[0]
    if 'function_before' in details:
        sum_funcs += len(details['function_before'])
    if 'function_after' in details:
        sum_funcs += len(details['function_after'])
sum_funcs

98785

In [88]:
for index, row in reposvul_ccpp_moe_df.iterrows():
    code = row['code']
    code_no_cmt = remove_comments(code)
    reposvul_ccpp_moe_df.at[index, 'code'] = code_no_cmt
reposvul_ccpp_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13160 entries, 0 to 13159
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      13160 non-null  object
 1   vuln      13160 non-null  object
 2   cwe       13160 non-null  object
 3   language  13160 non-null  object
dtypes: object(4)
memory usage: 411.4+ KB

In [89]:
reposvul_ccpp_moe_train_df, temp_df = train_test_split(reposvul_ccpp_moe_df, test_size=0.2, random_state=45, stratify=reposvul_ccpp_moe_df['vuln'])
reposvul_ccpp_val_df, reposvul_ccpp_test_df = train_test_split(temp_df, test_size=0.5, random_state=45, stratify=temp_df['vuln'])
reposvul_ccpp_moe_train_df.info()
reposvul_ccpp_val_df.info()
reposvul_ccpp_test_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10528 entries, 6119 to 10653
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      10528 non-null  object
 1   vuln      10528 non-null  object
 2   cwe       10528 non-null  object
 3   language  10528 non-null  object
dtypes: object(4)
memory usage: 411.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1316 entries, 10109 to 3596
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1316 non-null   object
 1   vuln      1316 non-null   object
 2   cwe       1316 non-null   object
 3   language  1316 non-null   object
dtypes: object(4)
memory usage: 51.4+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1316 entries, 12631 to 1441
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1316 non-null   object
 1   vuln      1316 non-null   object
 2   cwe       1316 non-null   object
 3   language  1316 non-null   object
dtypes: object(4)
memory usage: 51.4+ KB

In [90]:
rp_sv_moe_train_df = pd.concat([reposvul_ccpp_moe_train_df, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
rp_sv_moe_val_df = pd.concat([reposvul_ccpp_val_df, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
rp_sv_moe_test_df = pd.concat([reposvul_ccpp_test_df, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
rp_sv_moe_train_df.info()
rp_sv_moe_val_df.info()
rp_sv_moe_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11014 entries, 0 to 11013
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      11014 non-null  object
 1   vuln      11014 non-null  object
 2   cwe       11014 non-null  object
 3   language  11014 non-null  object
dtypes: object(4)
memory usage: 344.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1438 entries, 0 to 1437
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1438 non-null   object
 1   vuln      1438 non-null   object
 2   cwe       1438 non-null   object
 3   language  1438 non-null   object
dtypes: object(4)
memory usage: 45.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1468 non-null   object
 1   vuln      1468 non-null   object
 2   cwe       1468 non-null   object
 3   language  1468 non-null   object
dtypes: object(4)
memory usage: 46.0+ KB

In [91]:
rp_sv_moe_train_df.to_json("./dataset/RespoVul/no_comment/CCPP/reposvul_sven_train_nocmt.jsonl", orient="records", lines=True)
rp_sv_moe_val_df.to_json("./dataset/RespoVul/no_comment/CCPP/reposvul_sven_val_nocmt.jsonl", orient="records", lines=True)
rp_sv_moe_test_df.to_json("./dataset/RespoVul/no_comment/CCPP/reposvul_sven_test_nocmt.jsonl", orient="records", lines=True)

In [92]:
dv_full_data = []
with open("C:/hienlt/treesitter/dataset/Diverservul/diversevul.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        dv_full_data.append(record)
dv_full_df = pd.DataFrame(dv_full_data)
dv_full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330492 entries, 0 to 330491
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   func       330492 non-null  object
 1   target     330492 non-null  int64
 2   cwe        330492 non-null  object
 3   project    330492 non-null  object
 4   commit_id  330492 non-null  object
 5   hash       330492 non-null  object
 6   size       330492 non-null  int64
 7   message    330492 non-null  object
dtypes: int64(2), object(6)
memory usage: 20.2+ MB

In [93]:
dv_full_df.head()

,func,target,cwe,project,commit_id,hash,size,message
0,int _gnutls_ciphertext2compressed(gnutls_sessi...,1,[],gnutls,7ad6162573ba79a4392c63b453ad0220ca6c5ace,73008646937836648589283922871188272089,157,added an extra check while checking the padding.
1,static char *make_filename_safe(const char *fi...,1,[CWE-264],php-src,055ecbc62878e86287d742c7246c21606cee8183,211824207069112513181516095447837228041,22,Improve check for :memory: pseudo-filename in ...
2,"unpack_Z_stream(int fd_in, int fd_out)\n{\n\tI...",1,[],busybox,251fc70e9722f931eec23a34030d05ba5f747b0e,21401706257394042943815500829552774160,232,uncompress: fix buffer underrun by corrupted i...
3,"static void cirrus_do_copy(CirrusVGAState *s, ...",1,[CWE-787],qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,135590882627853658533498335902319684573,66,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."
4,"glue(cirrus_bitblt_rop_fwd_, ROP_NAME)(CirrusV...",1,[CWE-787],qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,27696392987383562433164405181263025184,18,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."

In [111]:
dv_full_df['code'] = dv_full_df['func']
dv_full_df['vuln'] = dv_full_df['target'].astype(int)
dv_full_df['cwe_processed'] = dv_full_df['cwe']
dv_full_df['language'] = "CCPP"

In [112]:
for index, row in dv_full_df.iterrows():
    cwes = row['cwe']
    if len(cwes) == 0:
        cwe_value = -1
        dv_full_df.at[index, 'cwe_processed'] = cwe_value
    elif len(cwes) >= 1:
        cwe_value = int(cwes[0].split('-')[-1])
        dv_full_df.at[index, 'cwe_processed'] = cwe_value
dv_full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330492 entries, 0 to 330491
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   func           330492 non-null  object
 1   target         330492 non-null  int64
 2   cwe            330492 non-null  object
 3   project        330492 non-null  object
 4   commit_id      330492 non-null  object
 5   hash           330492 non-null  object
 6   size           330492 non-null  int64
 7   message        330492 non-null  object
 8   code           330492 non-null  object
 9   vuln           330492 non-null  int64
 10  cwe_processed  330492 non-null  object
 11  language       330492 non-null  object
dtypes: int64(3), object(9)
memory usage: 30.3+ MB

In [113]:
dv_full_moe_df = pd.DataFrame({
    'code': dv_full_df['code'],
    'vuln': dv_full_df['vuln'],
    'cwe': dv_full_df['cwe_processed'],
    'language': dv_full_df['language']
})
dv_full_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330492 entries, 0 to 330491
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      330492 non-null  object
 1   vuln      330492 non-null  int64
 2   cwe       330492 non-null  object
 3   language  330492 non-null  object
dtypes: int64(1), object(3)
memory usage: 10.1+ MB

In [114]:
float(len(dv_full_moe_df[dv_full_moe_df['vuln'] == 1]) / len(dv_full_moe_df)) * 100

5.732362659307941

In [115]:
for index, row in dv_full_moe_df.iterrows():
    code = row['code']
    code_no_cmt = remove_comments(code)
    dv_full_moe_df.at[index, 'code'] = code_no_cmt

In [116]:
dv_train_moe_df, temp_df = train_test_split(dv_full_moe_df, test_size=0.2, random_state=45, stratify=dv_full_moe_df['vuln'])
dv_val_moe_df, dv_test_moe_df = train_test_split(temp_df, test_size=0.5, random_state=45, stratify=temp_df['vuln'])
dv_train_moe_df.info()
dv_val_moe_df.info()
dv_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 264393 entries, 289292 to 311662
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      264393 non-null  object
 1   vuln      264393 non-null  int64
 2   cwe       264393 non-null  object
 3   language  264393 non-null  object
dtypes: int64(1), object(3)
memory usage: 10.1+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 33049 entries, 189326 to 225564
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      33049 non-null  object
 1   vuln      33049 non-null  int64
 2   cwe       33049 non-null  object
 3   language  33049 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.3+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 33050 entries, 18930 to 272700
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      33050 non-null  object
 1   vuln      33050 non-null  int64
 2   cwe       33050 non-null  object
 3   language  33050 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.3+ MB

In [117]:
dv_train_moe_df_under = dv_train_moe_df[dv_train_moe_df['vuln'] == 1]
dv_train_moe_df_under = pd.concat([dv_train_moe_df_under, dv_train_moe_df[dv_train_moe_df['vuln'] == 0].sample(n=len(dv_train_moe_df_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_val_moe_df_under = dv_val_moe_df[dv_val_moe_df['vuln'] == 1]
dv_val_moe_df_under = pd.concat([dv_val_moe_df_under, dv_val_moe_df[dv_val_moe_df['vuln'] == 0].sample(n=len(dv_val_moe_df_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_test_moe_df_under = dv_test_moe_df[dv_test_moe_df['vuln'] == 1]
dv_test_moe_df_under = pd.concat([dv_test_moe_df_under, dv_test_moe_df[dv_test_moe_df['vuln'] == 0].sample(n=len(dv_test_moe_df_under), random_state=45).reset_index(drop=True)], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_train_moe_df_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30312 entries, 0 to 30311
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      30312 non-null  object
 1   vuln      30312 non-null  int64
 2   cwe       30312 non-null  object
 3   language  30312 non-null  object
dtypes: int64(1), object(3)
memory usage: 947.4+ KB

In [118]:
dv_sv_train_moe_df = pd.concat([dv_train_moe_df, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_sv_val_moe_df = pd.concat([dv_val_moe_df, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_sv_test_moe_df = pd.concat([dv_test_moe_df, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_sv_train_moe_df.info()   
dv_sv_val_moe_df.info()
dv_sv_test_moe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264879 entries, 0 to 264878
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   code      264879 non-null  object
 1   vuln      264879 non-null  int64
 2   cwe       264879 non-null  object
 3   language  264879 non-null  object
dtypes: int64(1), object(3)
memory usage: 8.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33171 entries, 0 to 33170
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      33171 non-null  object
 1   vuln      33171 non-null  int64
 2   cwe       33171 non-null  object
 3   language  33171 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33202 entries, 0 to 33201
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      33202 non-null  object
 1   vuln      33202 non-null  int64
 2   cwe       33202 non-null  object
 3   language  33202 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.0+ MB

In [121]:
dv_sv_train_moe_df_under = pd.concat([dv_train_moe_df_under, df_sv_train], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_sv_val_moe_df_under = pd.concat([dv_val_moe_df_under, df_sv_val], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_sv_test_moe_df_under = pd.concat([dv_test_moe_df_under, df_sv_test], ignore_index=True).sample(frac=1, random_state=45).reset_index(drop=True)
dv_sv_train_moe_df_under.info()
dv_sv_val_moe_df_under.info()
dv_sv_test_moe_df_under.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30798 entries, 0 to 30797
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      30798 non-null  object
 1   vuln      30798 non-null  int64
 2   cwe       30798 non-null  object
 3   language  30798 non-null  object
dtypes: int64(1), object(3)
memory usage: 962.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3910 entries, 0 to 3909
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      3910 non-null   object
 1   vuln      3910 non-null   int64
 2   cwe       3910 non-null   object
 3   language  3910 non-null   object
dtypes: int64(1), object(3)
memory usage: 122.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3942 entries, 0 to 3941
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      3942 non-null   object
 1   vuln      3942 non-null   int64
 2   cwe       3942 non-null   object
 3   language  3942 non-null   object
dtypes: int64(1), object(3)
memory usage: 123.3+ KB

In [122]:
dv_sv_train_moe_df.to_json("./dataset/Diverservul/dv_no_comment/nounder/diversevul_sven_train_nocmt.jsonl", orient="records", lines=True)
dv_sv_val_moe_df.to_json("./dataset/Diverservul/dv_no_comment/nounder/diversevul_sven_val_nocmt.jsonl", orient="records", lines=True)
dv_sv_test_moe_df.to_json("./dataset/Diverservul/dv_no_comment/nounder/diversevul_sven_test_nocmt.jsonl", orient="records", lines=True)

In [123]:
dv_sv_train_moe_df_under.to_json("./dataset/Diverservul/dv_no_comment/under/diversevul_sven_train_nocmt_under.jsonl", orient="records", lines=True)
dv_sv_val_moe_df_under.to_json("./dataset/Diverservul/dv_no_comment/under/diversevul_sven_val_nocmt_under.jsonl", orient="records", lines=True)
dv_sv_test_moe_df_under.to_json("./dataset/Diverservul/dv_no_comment/under/diversevul_sven_test_nocmt_under.jsonl", orient="records", lines=True)

In [133]:
pred_pr_sv_test = pd.read_csv("C:/hienlt/treesitter/dataset/Predictions/predictions_pr_sven_test.csv")
pred_sv_test = pd.read_csv("C:/hienlt/treesitter/dataset/Predictions/predictions_sven_test.csv")
pred_pr_sv_mve_test = pd.read_csv("C:/hienlt/treesitter/dataset/Predictions/predictions_pr_sv_mv.csv")

In [134]:
pred_sv_df = pd.DataFrame({
    'code': pred_sv_test['code'],
    'sven_model_pred': pred_sv_test['predicted_label'],
    'pr_model_pred': pred_pr_sv_test['predicted_label'],
    'pr_sv_mv_pred': pred_pr_sv_mve_test['predicted_label'],
    'pr_sv_mv_prob': pred_pr_sv_mve_test['probability'],
    'sv_model_prob': pred_sv_test['probability'],
    'pr_model_prob': pred_pr_sv_test['probability'],
    'true_label': pred_sv_test['true_label'],
    'cwe': pred_sv_test['cwe']
})
pred_sv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   code             152 non-null    object
 1   sven_model_pred  152 non-null    int64
 2   pr_model_pred    152 non-null    int64
 3   pr_sv_mv_pred    152 non-null    int64
 4   pr_sv_mv_prob    152 non-null    float64
 5   sv_model_prob    152 non-null    float64
 6   pr_model_prob    152 non-null    float64
 7   true_label       152 non-null    int64
 8   cwe              152 non-null    int64
dtypes: float64(3), int64(5), object(1)
memory usage: 10.8+ KB

In [136]:
pred_sv_df.to_csv("C:/hienlt/treesitter/dataset/Predictions/pred_pr_sv_mv_combined_test.csv", index=False)

In [128]:
pred_sv_pr_test = pd.read_csv("C:/hienlt/treesitter/dataset/Predictions/predictions_sv_pr_test.csv")
pred_pr_test = pd.read_csv("C:/hienlt/treesitter/dataset/Predictions/predictions_pr_test.csv")

In [129]:
pred_pr_df = pd.DataFrame({
    'code': pred_pr_test['code'],
    'sven_model_pred': pred_sv_pr_test['predicted_label'],
    'pr_model_pred': pred_pr_test['predicted_label'],
    'sv_model_prob': pred_sv_pr_test['probability'],
    'pr_model_prob': pred_pr_test['probability'],
    'true_label': pred_pr_test['true_label'],
    'cwe': pred_pr_test['cwe']
})
pred_pr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22454 entries, 0 to 22453
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   code             22454 non-null  object
 1   sven_model_pred  22454 non-null  int64
 2   pr_model_pred    22454 non-null  int64
 3   sv_model_prob    22454 non-null  float64
 4   pr_model_prob    22454 non-null  float64
 5   true_label       22454 non-null  int64
 6   cwe              22454 non-null  int64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.2+ MB

In [130]:
pred_sv_df.to_csv("C:/hienlt/treesitter/dataset/Predictions/pred_sv_combined_test.csv", index=False)

In [140]:
pr_correct_sv_wrong_1 = 0
pr_correct_sv_wrong_0 = 0
for index, row in pred_sv_df.iterrows():
    if row['pr_sv_mv_pred'] == row['true_label'] and row['sven_model_pred'] != row['true_label']:
        if row['true_label'] == 1:
            pr_correct_sv_wrong_1 += 1
        else:
            pr_correct_sv_wrong_0 += 1
pr_correct_sv_wrong_0

0

In [132]:
pr_correct_sv_wrong_0

19

In [16]:
# ccpp_moe3_preds = []
# with open("C:/hienlt/treesitter/dataset/Predictions/prediction_file_ccpp_20260411_133345.jsonl", "r", encoding="utf-8") as f:
#     for line in f:
#         record = json.loads(line)
#         ccpp_moe3_preds.append(record)
# ccpp_moe3_preds_df = pd.DataFrame(ccpp_moe3_preds)

py_moe4th_preds = []
with open("C:/hienlt/treesitter/dataset/Predictions/prediction_file_expert_1_20260412_211926.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        py_moe4th_preds.append(record)
py_moe4th_preds_df = pd.DataFrame(py_moe4th_preds)

vulpy_moe4th_preds = []
with open("C:/hienlt/treesitter/dataset/Predictions/prediction_file_expert_2_20260413_125214.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        vulpy_moe4th_preds.append(record)
vulpy_moe4th_preds_df = pd.DataFrame(vulpy_moe4th_preds)

In [18]:
all_sample_ids = py_moe4th_preds_df['sample_id'].unique()

In [19]:
pr_sv_test = []
with open("C:/hienlt/treesitter/dataset/Predictions/primevul_sven_test_nocmt_nounder.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        pr_sv_test.append(record)
pr_sv_test_df = pd.DataFrame(pr_sv_test)
pr_sv_test_df.head()

                                                code  vuln  cwe language
0  LoadPage::LoadErrorHandling strToLoadErrorHand...     0   22     CCPP
1  gen11_emit_fini_breadcrumb_rcs(struct i915_req...     0   -2     CCPP
2  const char *imap_parser_get_error(struct imap_...     0  787     CCPP
3  ImagingLibTiffEncodeInit(ImagingCodecState sta...     0  787     CCPP
4  static int max_sectors_bytes(struct request_qu...     0  189     CCPP

In [23]:
for index, row in pr_sv_test_df.iterrows():
    sample_id = row['sample_id']
    if sample_id in all_sample_ids and row['language'] == 'CCPP':
        print(f"Sample ID: {sample_id}")

Sample ID: 8393
Sample ID: 10417

In [12]:
pred_sv_moe4th_df = pd.DataFrame({
    'py_expert_pred': py_moe4th_preds_df['predicted_label'],
    'vulpy_expert_pred': vulpy_moe4th_preds_df['predicted_label'],
    'py_expert_prob': py_moe4th_preds_df['probability'],
    'vulpy_expert_prob': vulpy_moe4th_preds_df['probability'],
    'true_label': py_moe4th_preds_df['real_label'],
    'cwe': py_moe4th_preds_df['cwe_id']
})
pred_sv_moe4th_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   py_expert_pred     152 non-null    int64
 1   vulpy_expert_pred  152 non-null    int64
 2   py_expert_prob     152 non-null    float64
 3   vulpy_expert_prob  152 non-null    float64
 4   true_label         152 non-null    int64
 5   cwe                152 non-null    int64
dtypes: float64(2), int64(4)
memory usage: 7.2 KB

In [13]:
vulpy_pred_correct_sv_wrong_1 = 0
vulpy_pred_correct_sv_wrong_0 = 0
sv_pred_correct_vulpy_wrong_1 = 0
for index, row in pred_sv_moe4th_df.iterrows():
    if row['vulpy_expert_pred'] == row['true_label'] and row['py_expert_pred'] != row['true_label']:
        if row['true_label'] == 1:
            vulpy_pred_correct_sv_wrong_1 += 1
        else:
            vulpy_pred_correct_sv_wrong_0 += 1
    if row['py_expert_pred'] == row['true_label'] and row['vulpy_expert_pred'] != row['true_label']:
        if row['true_label'] == 1:
            sv_pred_correct_vulpy_wrong_1 += 1

In [14]:
vulpy_pred_correct_sv_wrong_1

25

In [15]:
pred_sv_moe4th_df.to_csv("C:/hienlt/treesitter/dataset/Predictions/pred_sv_moe4threshold05_combined_test.csv", index=False)

In [27]:
import json
import pandas as pd

In [28]:
pv_train_161_df = pd.read_csv("C:/hienlt/treesitter/dataset/MVD/primevul161/primevul_train.csv")
pv_val_161_df = pd.read_csv("C:/hienlt/treesitter/dataset/MVD/primevul161/primevul_val.csv")
pv_test_161_df = pd.read_csv("C:/hienlt/treesitter/dataset/MVD/primevul161/primevul_test.csv")
sv_train_161_df = pd.read_csv("C:/hienlt/treesitter/dataset/MVD/sven161/sven_train.csv")
sv_val_161_df = pd.read_csv("C:/hienlt/treesitter/dataset/MVD/sven161/sven_val.csv")
sv_test_161_df = pd.read_csv("C:/hienlt/treesitter/dataset/MVD/sven161/sven_test.csv")

In [40]:
pv_train_161_df['cwe_processed'] = pv_train_161_df['cwe']
pv_val_161_df['cwe_processed'] = pv_val_161_df['cwe']
pv_test_161_df['cwe_processed'] = pv_test_161_df['cwe']
for index, row in pv_train_161_df.iterrows():
    cwe = str(row['cwe'][2:-2])
    if(len(cwe) == 0):
        cwe = -1
    elif cwe.startswith("NVD"):
        cwe = -2
    else:
        cwe = int(cwe.split('-')[-1])
    pv_train_161_df.at[index, 'cwe_processed'] = cwe

for index, row in pv_val_161_df.iterrows():
    cwe = str(row['cwe'][2:-2])
    if(len(cwe) == 0):
        cwe = -1
    elif cwe.startswith("NVD"):
        cwe = -2
    else:
        cwe = int(cwe.split('-')[-1])
    pv_val_161_df.at[index, 'cwe_processed'] = cwe

for index, row in pv_test_161_df.iterrows():
    cwe = str(row['cwe'][2:-2])
    if(len(cwe) == 0):
        cwe = -1
    elif cwe.startswith("NVD"):
        cwe = -2
    else:
        cwe = int(cwe.split('-')[-1])
    pv_test_161_df.at[index, 'cwe_processed'] = cwe
pv_train_161_df.info()
pv_val_161_df.info()
pv_test_161_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7889 non-null   int64
 1   project         7889 non-null   object
 2   commit_id       7889 non-null   object
 3   project_url     7759 non-null   object
 4   commit_url      7887 non-null   object
 5   commit_message  5460 non-null   object
 6   target          7889 non-null   int64
 7   func            7889 non-null   object
 8   func_hash       7889 non-null   object
 9   file_name       4699 non-null   object
 10  file_hash       4699 non-null   object
 11  cwe             7889 non-null   object
 12  cve             7888 non-null   object
 13  cve_desc        7888 non-null   object
 14  nvd_url         7889 non-null   object
 15  code            7889 non-null   object
 16  label           7889 non-null   int64
 17  cwe_processed   7889 non-null   object
dtypes: int64(3), object(15)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             986 non-null    int64
 1   project         986 non-null    object
 2   commit_id       986 non-null    object
 3   project_url     977 non-null    object
 4   commit_url      986 non-null    object
 5   commit_message  684 non-null    object
 6   target          986 non-null    int64
 7   func            986 non-null    object
 8   func_hash       986 non-null    object
 9   file_name       600 non-null    object
 10  file_hash       600 non-null    float64
 11  cwe             986 non-null    object
 12  cve             986 non-null    object
 13  cve_desc        986 non-null    object
 14  nvd_url         986 non-null    object
 15  code            986 non-null    object
 16  label           986 non-null    int64
 17  cwe_processed   986 non-null    object
dtypes: float64(1), int64(3), object(14)
memory usage: 138.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             987 non-null    int64
 1   project         987 non-null    object
 2   commit_id       987 non-null    object
 3   project_url     965 non-null    object
 4   commit_url      986 non-null    object
 5   commit_message  660 non-null    object
 6   target          987 non-null    int64
 7   func            987 non-null    object
 8   func_hash       987 non-null    object
 9   file_name       583 non-null    object
 10  file_hash       583 non-null    float64
 11  cwe             987 non-null    object
 12  cve             986 non-null    object
 13  cve_desc        986 non-null    object
 14  nvd_url         987 non-null    object
 15  code            987 non-null    object
 16  label           987 non-null    int64
 17  language        987 non-null    object
 18  cwe_processed   987 non-null    object
dtypes: float64(1), int64(3), object(15)
memory usage: 146.6+ KB

In [44]:
sv_train_161_df['cwe_processed'] = sv_train_161_df['vul_type']
sv_val_161_df['cwe_processed'] = sv_val_161_df['vul_type']
sv_test_161_df['cwe_processed'] = sv_test_161_df['vul_type']
for index, row in sv_train_161_df.iterrows():
    cwe = row['vul_type'].split('-')[-1]
    match cwe:
        case "079":   
             cwe_value = 79
        case "089":
            cwe_value = 89
        case "078":
            cwe_value = 78
        case "022":
            cwe_value = 22
    sv_train_161_df.at[index, 'cwe_processed'] = cwe_value
for index, row in sv_val_161_df.iterrows():
    cwe = row['vul_type'].split('-')[-1]
    match cwe:
        case "079":   
             cwe_value = 79
        case "089":
            cwe_value = 89
        case "078":
            cwe_value = 78
        case "022":
            cwe_value = 22
    sv_val_161_df.at[index, 'cwe_processed'] = cwe_value
for index, row in sv_test_161_df.iterrows():
    cwe = row['vul_type'].split('-')[-1]
    match cwe:
        case "079":   
             cwe_value = 79
        case "089":
            cwe_value = 89
        case "078":
            cwe_value = 78
        case "022":
            cwe_value = 22
    sv_test_161_df.at[index, 'cwe_processed'] = cwe_value
sv_train_161_df.info()
sv_val_161_df.info()
sv_test_161_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   func           486 non-null    object
 1   target         486 non-null    int64
 2   vul_type       486 non-null    object
 3   code           486 non-null    object
 4   label          486 non-null    int64
 5   cwe_processed  486 non-null    object
dtypes: int64(2), object(4)
memory usage: 22.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   func           122 non-null    object
 1   target         122 non-null    int64
 2   vul_type       122 non-null    object
 3   code           122 non-null    object
 4   label          122 non-null    int64
 5   cwe_processed  122 non-null    object
dtypes: int64(2), object(4)
memory usage: 5.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   func           152 non-null    object
 1   target         152 non-null    int64
 2   vul_type       152 non-null    object
 3   code           152 non-null    object
 4   label          152 non-null    int64
 5   language       152 non-null    object
 6   cwe_processed  152 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.4+ KB

In [46]:
pr_sv_train_moe_mvd_df = pd.DataFrame({
    'code': pd.concat([pv_train_161_df['func'], sv_train_161_df['code']], ignore_index=True),
    'vuln': pd.concat([pv_train_161_df['target'], sv_train_161_df['label']], ignore_index=True),
    'cwe': pd.concat([pv_train_161_df['cwe_processed'], sv_train_161_df['cwe_processed']], ignore_index=True),
    'language': pd.concat([pd.Series(['CCPP'] * len(pv_train_161_df)), pd.Series(['Python'] * len(sv_train_161_df))], ignore_index=True)
})
pr_sv_val_moe_mvd_df = pd.DataFrame({
    'code': pd.concat([pv_val_161_df['func'], sv_val_161_df['code']], ignore_index=True),
    'vuln': pd.concat([pv_val_161_df['target'], sv_val_161_df['label']], ignore_index=True),
    'cwe': pd.concat([pv_val_161_df['cwe_processed'], sv_val_161_df['cwe_processed']], ignore_index=True),
    'language': pd.concat([pd.Series(['CCPP'] * len(pv_val_161_df)), pd.Series(['Python'] * len(sv_val_161_df))], ignore_index=True)
})
pr_sv_test_moe_mvd_df = pd.DataFrame({
    'code': pd.concat([pv_test_161_df['func'], sv_test_161_df['code']], ignore_index=True),
    'vuln': pd.concat([pv_test_161_df['target'], sv_test_161_df['label']], ignore_index=True),
    'cwe': pd.concat([pv_test_161_df['cwe_processed'], sv_test_161_df['cwe_processed']], ignore_index=True),
    'language': pd.concat([pd.Series(['CCPP'] * len(pv_test_161_df)), pd.Series(['Python'] * len(sv_test_161_df))], ignore_index=True)
})
pr_sv_train_moe_mvd_df.info()
pr_sv_val_moe_mvd_df.info()
pr_sv_test_moe_mvd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8375 entries, 0 to 8374
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      8375 non-null   object
 1   vuln      8375 non-null   int64
 2   cwe       8375 non-null   object
 3   language  8375 non-null   object
dtypes: int64(1), object(3)
memory usage: 261.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1108 entries, 0 to 1107
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1108 non-null   object
 1   vuln      1108 non-null   int64
 2   cwe       1108 non-null   object
 3   language  1108 non-null   object
dtypes: int64(1), object(3)
memory usage: 34.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      1139 non-null   object
 1   vuln      1139 non-null   int64
 2   cwe       1139 non-null   object
 3   language  1139 non-null   object
dtypes: int64(1), object(3)
memory usage: 35.7+ KB

In [49]:
pr_sv_train_moe_mvd_df.to_json("C:/hienlt/treesitter/dataset/MVD/primevul161/primevul_sven_train_mvd.jsonl", orient="records", lines=True)
pr_sv_val_moe_mvd_df.to_json("C:/hienlt/treesitter/dataset/MVD/primevul161/primevul_sven_val_mvd.jsonl", orient="records", lines=True)
pr_sv_test_moe_mvd_df.to_json("C:/hienlt/treesitter/dataset/MVD/primevul161/primevul_sven_test_mvd.jsonl", orient="records", lines=True)